### ISSUE TITLE
Can't install Azure CLI with APT

### ISSUE THREAD

**Issue by brunoborges** [MicrosoftDocs/vsonline#101]
Following documentation, can't install Azure CLI for Linux with APT:

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#install-with-one-command

`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

**Comment by bjbennet** [comment]
The install script you mentioned uses a command "lsb_release" that our derived distribution of Linux cannot understand. Please refer to this troubleshooting section for azure cli install: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#lsb_release-does-not-return-the-correct-base-distribution-version

You will have to use the manual install steps on the above page.
For Step 3-Add the Azure CLI software repository, use: `AZ_REPO=stretch`

**Comment by legomushroom** [comment]
Hi @brunoborges, thanks for filing the issue! The machine does have multiple python versions installed so the error you see is the common issue in such cases.

You can run the installation with the specific python version like this (and you will have to elevate the command with sudo):

```bash
sudo python3 -m pip install azure-cli
```

**Comment by brunoborges** [comment]
@legomushroom You either add this command to the Azure CLI documentation, or ensure the Azure CLI already documented instruction works ootb :-)

Even better, make Azure CLI always available on VS Online environments.

**Comment by srivatsn** [comment]
> Even better, make Azure CLI always available on VS Online environments.

We should just do that.

**Comment by jkeech** [comment]
Yes, we are going to provide the Azure CLI in the base image soon. The the primary reason the install doesn't work today is related to microsoft/Oryx#404.

**Comment by asw101** [comment]
@legomushroom an issue I'm facing here is that `sudo python3 -m pip install azure-cli` will install the Azure CLI, and it'll even `az login`, but commands, including `az group list` (below) are not compatible with Python 3.8 due to things like the previously deprecated `time.clock()`'s [removal in Python 3.8](https://bugs.python.org/issue36895):

```
$ az group list
Traceback (most recent call last):
  File "/opt/python/3.8.0/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/python/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/python/3.8.0/lib/python3.8/site-packages/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/opt/python/3.8.0/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 546, in get_default_cli
    return AzCli(cli_name='az',
  File "/opt/python/3.8.0/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 55, in __init__
    SESSION.load(os.path.join(azure_folder, 'az.sess'), max_age=3600)
  File "/opt/python/3.8.0/lib/python3.8/site-packages/azure/cli/core/_session.py", line 46, in load
    if st.st_mtime + max_age < time.clock():
AttributeError: module 'time' has no attribute 'clock'
```

We also need a working `apt` for many other things, so I am hoping Oryx restores the default system Python asap.

**Comment by jkeech** [comment]
@asw101, we are working around the Oryx base image issue for now and adding Python back in until we get a proper upstream fix. Testing is underway now. If everything looks good, we will roll this out tomorrow for all new environment creations. We'll follow up here once it's deployed.

**Comment by asw101** [comment]
@jkeech that is great news, thank you!

**Comment by rajkumar42** [comment]
@brunoborges & @asw101 , correct versions of python are available in the Oryx image now. You'll get the updated image when you create a new environment. Also az cli is now installed by default.

**Comment by lostintangent** [comment]
@rajkumar42 Do we auto-auth the user in with the Az CLI? If not, we should file a new issue to track that, since that’s a key part of the experience, beyond installing the bits.
