### ISSUE TITLE
Extension not displaying in VS Code activity bar

### ISSUE THREAD

**Issue by tjnix** [MicrosoftDocs/vsonline#106]
After installing the vsonline extension, I am unable to get the extension to show up in the activity bar even after reload. I get two errors:

1. "No view is registered with id: vsonline.explorerDetails"
2: "No view is registered with id: vsonline.explorer"

See the screen shot below. 

<img width="960" alt="2019-11-06_10-20-19" src="https://user-images.githubusercontent.com/12632796/68356403-3af48880-00e0-11ea-8104-34bceb04df98.png">

VS Code details:
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by jkeech** [comment]
Could you try upgrading to the latest stable VS Code version 1.39.2? I believe we have some dependencies on newer VS Code features -- specifically the new Remote Explorer view, although it looks like it's not formally declared in our package.json. We'll update our package.json in the next release with the correct minimum VS code engine version.
