### ISSUE TITLE
Add support for Safari (iPad)

### ISSUE THREAD

**Issue by formulahendry** [MicrosoftDocs/vsonline#108]
Is there any timeline to support VS Online in browser of iPad?

**Comment by jkeech** [comment]
There's no timeline published, but it's a top priority for us to expand browser support, including Safari.

**Comment by formulahendry** [comment]
Awesome! Look forward to it! 😄

**Comment by wazybr** [comment]
@jkeech Does this includes adding support for mobile browsers to Monaco?

**Comment by Chuxel** [comment]
Regarding the browser-based editor itself, work is actively going on to support shortcomings. See:

https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+safari+label%3Asafari
...and...
https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+safari+label%3Aios

...for known issues on Safari and additional issues specific to iOS respectively.

**Comment by Uncle-Justice** [comment]
Please！！！Make it on top！！！

**Comment by nikmd23** [comment]
Closing this issue in favor of #33
