### ISSUE TITLE
Environment creation do not complete

### ISSUE THREAD

**Issue by ridomin** [MicrosoftDocs/vsonline#109]
I tried to setup a new environment from this repo https://github.com/jonmikeli/azureiotdevicesimulator3 but after 24h it's still in the "creating" phase.

Is there any option to collect diagnostic logs?

**Comment by jkeech** [comment]
Sorry you are experiencing issues. Can you please provide the environment id so we can see what happened? This is almost certainly a service issue and not anything related to the repo you are trying to create an environment for. The easiest way to get the environment id is to login to online.visualstudio.com and open the network tab in F12 tools. You should see some regular polling of the environment state for the one which is stuck in "Creating". The endpoint should look something like `/api/v1/environments/{guid}`, where the guid is the environment id.

Also, could you try creating a new environment for the same repo? It is expected to complete within 20-30 seconds in most cases.

**Comment by ridomin** [comment]
Thanks for the reply. 

I tried again with the same repo and now  it succeed, yay !! . 
Here is the ID of the failed environment 1c63a056-1760-4267-8cb3-3f7e83934591 

Thank you !!
