### ISSUE TITLE
Repeat Microsoft logo at titlebar

### ISSUE THREAD

**Issue by LokiSharp** [MicrosoftDocs/vsonline#110]
I think your must set `background-repeat` to `no-repeat`.

![](https://i.imgur.com/74IFDES.png)

**Comment by kumarz** [comment]
@LokiSharp 
Thanks for reporting the issue, Can you please share the browser details. we would like to reproduce this for our investigation. As I am not seeing this issue chrome, firefox & edge.

**Comment by LokiSharp** [comment]
Windows 7
Chrome 78.0.3904.97 64bit
Resolution 2560*1080

**Comment by jkeech** [comment]
@LokiSharp, we've made some changes that should fix this issue. Can you confirm it's displaying correctly for you now?

**Comment by LokiSharp** [comment]
@jkeech It's fixed
