### ISSUE TITLE
PWA-ize the VSO and release it in Microsoft Store?

### ISSUE THREAD

**Issue by tclzcja** [MicrosoftDocs/vsonline#115]
Hi there, this is more like a question instead of issue.

It seems like currently VS Online is not a PWA yet, is there any plan to PWA-ize it so in the future we can simply add it to home screen on Mobile/Pad? And even more, download it from Microsoft Store?

Plus, if there is a PWA plan, is it currently being "blocked" by the Jan 15th Edge/Chromium release?

Thank you!

**Comment by cmbrose** [comment]
Thanks for the question! We do plan to have PWA support - see #43 for more details.
