### ISSUE TITLE
Blazor 

### ISSUE THREAD

**Issue by joshmccall221** [MicrosoftDocs/vsonline#120]
Blazor project runs but redirects to "This site can’t be reached".

https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli

![image](https://user-images.githubusercontent.com/7776611/68435584-7b9be280-0170-11ea-86ee-c34c9bd357b8.png)

![image](https://user-images.githubusercontent.com/7776611/68435603-8b1b2b80-0170-11ea-9e79-7e737ac019a6.png)

![image](https://user-images.githubusercontent.com/7776611/68435621-95d5c080-0170-11ea-9231-65cce79a6658.png)

**Comment by jkeech** [comment]
I think the server is issuing an HTTP redirect on the client to localhost:5001. So the port-forwarding re-write that sees localhost and rewrites it to the *.app.online.visualstudio.com url has no opportunity to intercept the redirect. I've seen this happen before when HTTP redirect is enabled by default in `startup.cs`.

Can you try disabling the automatic https redirect to a different port for the dev inner loop? The port-forwarding implementation itself is only exposed over an encrypted HTTPS connection, so .NET Core doesn't need to do the TLS termination or HTTPS redirect from inside the app.

**Comment by joshmccall221** [comment]
startup.cs
``` 
  // app.UseHttpsRedirection();
```
> dotnet run 

![image](https://user-images.githubusercontent.com/7776611/68491749-fbbd5900-01ff-11ea-9601-7cc711843e39.png)

Works... Kinda!!!!

Port forwarding is working but it looks like the azure resource does not have websockets enabled (The counter example doesn't increment which requires websockets). 

Can we get websockets enabled?

**Comment by jkeech** [comment]
Great! Websockets support is being tracked in #19.

**Comment by joshmccall221** [comment]
Thank you @jkeech, I will track the other issue for websockets!
