### ISSUE TITLE
Unable to connect or restore a self-hosted environment

### ISSUE THREAD

**Issue by martemorfosis** [MicrosoftDocs/vsonline#125]
It was working perfectly yesterday but today I was unable to connect to or restore my registered local environment:

![image](https://user-images.githubusercontent.com/2488715/68448224-680c6e00-01a8-11ea-8993-be08a62bee67.png)

Things I've tried with no success:

* Unregister my self-hosted environment and succesfully register it again
* Reinstalling both the Azure Account and the VS Online extensions
* Sing Out and Sign In multiple times

I'm able to create a cloud environment and connect to it with no problems tho.

**Comment by Chuxel** [comment]
@taiyosogawa I started seeing this as well as of this morning. Things were working fine yesterday.

Output window for VS Online
```text
[Client I] Trace log: /var/folders/j7/bm3_5r713hq0_x8c3d3y7wg00000gn/T/vsonline_logs/20191108_151058_15732258586590_VSCode.log
[Client I] User logged in as clantz@microsoft.com
[Command:SelectPlan I] Decorator starting: ErrorNotification
[Command:SelectPlan I] Decorator starting: Telemetry
[Command:RestoreLocalEnvironment I] Decorator starting: ErrorNotification
[Command:RestoreLocalEnvironment I] Decorator starting: Telemetry
[Command:RestoreLocalEnvironment E] Command [Unabled to restore local environment]: Restore local environment Failure: Unable to authenticate (1652ms)
[Command:RestoreLocalEnvironment I] Decorator finishing: Telemetry. Duration: 34ms (0 + 34)
[Command:SelectPlan E] Command [Failed to select a plan.]: Select Plan Cancelled:  (7983ms)
[Command:SelectPlan I] Decorator finishing: Telemetry. Duration: 1ms (0 + 1)
[Command:SelectPlan I] Decorator finishing: ErrorNotification. Duration: 0ms (0 + 0)
[Command:RestoreLocalEnvironment I] Decorator finishing: ErrorNotification. Duration: 46653ms (0 + 46653)
```

I see no agent logs at all.

**Comment by Chuxel** [comment]
@martemorfosis I just retried this today and things seem to be working.  Are you still hitting the problem?

**Comment by martemorfosis** [comment]
@Chuxel 

Well, it worked fine late night yesterday for a little time, but today I was unable to connect via browser again so I proceeded to unregister the local environment, re-registered it and tried to connect unsuccesfully:

![image](https://user-images.githubusercontent.com/2488715/68637995-d06b9000-04c5-11ea-906b-35a4b7853366.png)

Whenever I tried to restore it I got the same error message:

![image](https://user-images.githubusercontent.com/2488715/68637639-d8770000-04c4-11ea-8441-69c27faae13b.png)

**Comment by zhaoxin** [comment]
Similar problem here. The error I get is 'Sharing environment failed'.

**Comment by taiyosogawa** [comment]
@martemorfosis, @zhaoxin, sorry for the very late reply and thank you for your patience. We're working on diagnosing and resolving this issue. If you have the opportunity, could you try the following to see if it allows you to register and connect? 

1) If it exists, delete the file .vs-liveshare-keychain in your home directory.
2) Go to your OS's Keychain or Credential Manager, and delete any credentials that start with "Microsoft_VS_LiveShare".
3) Give unregister/register (or restore) another shot.

**Comment by mikeburgh** [comment]
@taiyosogawa just responding here as you are right this looks more like my issue. 

I followed the above again, and still cannot get this to work, I can register an enviroment, but then any attempt to connect to it gives me: 

```
Failed to connect to the remote extension host server (Error: Failed to connect to relay: wss://vsls-prod-ins-use-private-relay.servicebus.windows.net:443/$hc/xxx--31c8f8a1-dd53-423c-b031-7f9aed9b38be?sb-hc-action=connect&sb-hc-token=SharedAccessSignature%20sr%3Dsb%253A%252F%252Fvsls-prod-ins-use-private-relay.servicebus.windows.net%25xxxx13--31c8f8a1-dd53-423c-b031-7f9aed9b3xxxxxxx%253D%26se%3xxxxaceShareKey)
```

Then trying to restore it I get the same issue as reported: 

```
Unable to restore local environment: Unable to authenticate
```

I was also originally testing this with the free trial sub which had expired, so I created a new pay as you go sub, new plan in VSOnline for that sub and same result there.

**Comment by jkeech** [comment]
@martemorfosis, @mikeburgh are you still experiencing this problem with the latest version of the extension?

**Comment by mikeburgh** [comment]
Nope, been very reliable lately!

**Comment by jkeech** [comment]
@mikeburgh, thanks for confirming! I'm going to go ahead and close this issue. Feel free to open another one if you run into any problems.
