### ISSUE TITLE
visual Studio Online - Dev contianer doesnot execute 

### ISSUE THREAD

**Issue by medampudi** [MicrosoftDocs/vsonline#126]
the following are the configurations that have been copied from the docs and minor mods to it lead to them not getting executed at all. 

```
/* Contents of {repository-root}/.devcontainer/devcontainer.json */
{
    // Open port 3000 by default
    "appPort": 8000,
    // Install ESLint and Peacock extensions
    "extensions": [
        "formulahendry.auto-close-tag",
        "formulahendry.auto-rename-tag",
    ],
    // Run Bash script in .devcontainer directory
    "postCreateCommand": "npm install -g gulp-cli serverless gatsby-cli",
}
```

Can anyone please guide me to how this is to be done with proper configuration in the settings if need be.,

**Comment by nikmd23** [comment]
Hi @medampudi.
Sorry things aren’t working as expected. 

Would you mind letting us know what you’ve named this file, where it’s stored (path), and how you tried to create the environment? (Code or browser)

Thanks!

**Comment by medampudi** [comment]
Hello @nikmd23,

After looking at your response to create the environment, i did try it, and it worked. However i have to have a hard time running a few apps running inside of it, Gatsby, for example, even after i opened up Port 8000 from dev container. 

Thanks for the comment, though.

**Comment by srivatsn** [comment]
@medampudi what error are you seeing? Is it similar to https://github.com/MicrosoftDocs/vsonline/issues/117?

**Comment by medampudi** [comment]
@srivatsn Yes that is the one. So i think we can close this issue for now. As The .devcontainer file only work on init no on restart.

**Comment by srivatsn** [comment]
@medampudi We are also tracking making the devcontainer refresh experience better here - https://github.com/MicrosoftDocs/vsonline/issues/51
