### ISSUE TITLE
Incorrect Version of .NET Core installed

### ISSUE THREAD

**Issue by kunalbabre** [MicrosoftDocs/vsonline#127]
I checked out https://github.com/kunalbabre/fireworks project it uses .NET Core 2.2 however, the vsonline started with .NET Core 2.1. Also, the project uses docker and should I expecting docker to be available as well?

My environment GUID: edf64443-c0cd-4599-8030-00dba463d5d6

**Comment by srivatsn** [comment]
.NET Core 2.2 is installed in the environment but is not very discoverable (it's under /opt/dotnet/sdks). I've filed https://github.com/microsoft/Oryx/issues/425 to make this work better for `dotnet`. We'll use this issue to track that for VSOnline.

As for docker, the work to enable that is tracked by https://github.com/MicrosoftDocs/vsonline/issues/40. Please follow that issue for updates.

**Comment by NCC1701M** [comment]
I have the same problem. A Version 2.2 app which can not be restored because there is no 2.2 SDK installed. Can I activate it?

**Comment by srivatsn** [comment]
You can use the other sdks from /opt/dotnet/sdks by setting that in PATH. We are also close to releasing a fix for this issue by flattening out all the SDK directories.

**Comment by rajkumar42** [comment]
@kunalbabre , @NCC1701M this issue is fixed. New environments created now will have 1.1, 2.1, 2.2, 3.0 sdks installed.
