### ISSUE TITLE
Differentiate subscriptions with the same name

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#129]
See this tweet:

https://twitter.com/get_hariharan/status/1192738967512174593?s=21

**Comment by srivatsn** [comment]
@cmbrose, add a tooltip with the id similar to the one you added for plans?

**Comment by cmbrose** [comment]
@srivatsn, yeah that's easy to do - just the Subscription Id (Guid) is enough to dedupe.  Is there a more user friendly text that would also dedupe?

**Comment by jkeech** [comment]
The subscription Id is what other UX show

**Comment by jkeech** [comment]
We've added a tooltip on hover in the plan and subscription dropdown lists. This can help users differentiate multiple subscriptions or plans with the same name.
