### ISSUE TITLE
Fails to show environments

### ISSUE THREAD

**Issue by Chuxel** [MicrosoftDocs/vsonline#131]
Transferred from https://github.com/microsoft/vscode-remote-release/issues/1788 @brianlowe 

----

Issue Type: <b>Bug</b>

Follow the tutorial at https://docs.microsoft.com/en-us/visualstudio/online/quickstarts/vscode

Step 5 suggests right-clicking the environment name in the "VS Online" panel of "Remote Explorer" to call a context menu with the "Delete" option, but the current environment is not shown. Right-click has no effect.

VS Code pops up this error... "Error running command extension.refreshObjectExplorerNode: command 'extension.refreshObjectExplorerNode' not found. This is likely caused by the extension that contributes extension.refreshObjectExplorerNode."

Extension version: 0.81.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by cmbrose** [comment]
@Chuxel - that's a pretty old version of the extension.  Does this repro in a more recent version?  Is there a need to support that old of a version?

**Comment by jkeech** [comment]
@cmbrose, I think the original poster was showing the version of the vscode-remote extension, not the VSO extension.

**Comment by cmbrose** [comment]
@brianlowe - I'm not able to repro the behavior.  Can you me me know what version of the VS Online extension you are using (assuming that `0.81.1` is indeed vscode-remote).  Could you also confirm whether or not you are inside an environment when you are trying to perform the delete? Thanks!

**Comment by brianlowe** [comment]
VS Code updated at startup this morning to 1.40 and now I can't reproduce the issue. I think it's time to call this fixed. Thanks!

**Comment by cmbrose** [comment]
Awesome! Let us know if it you see it again
