### ISSUE TITLE
Cannot debug (with dlv) using Go extension for Visual Studio Code 

### ISSUE THREAD

**Issue by asw101** [MicrosoftDocs/vsonline#140]
When trying to debug using the [Go extension for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go) you will see the following error in the `Debug Console`:

```
API server listening at: 127.0.0.1:6576
could not launch process: fork/exec /home/vsonline/workspace/__debug_bin: operation not permitted
Process exiting with code: 1
```

The same error will occur if you run `dlv` directly.

It is likely because we are running inside a container, which would need to be run with the `--security-opt seccomp=unconfined` flag in order to work (see: https://github.com/go-delve/delve/issues/515) (note this has security implications if relying on container isolation).

**Comment by jkeech** [comment]
We do not rely on container isolation for hostile multi-tenant scenarios. We use VM isolation for each environment/tenant, so there's not much harm in opening this up if it enables important scenarios.

There are other scenarios we are considering, such as enabling docker-outside-of-docker scenarios via bind mounting the host's docker daemon socket into the container, so that `docker run` from the environment would spin up a sibling container on the host. In this case, the same security considerations apply.

**Comment by lostintangent** [comment]
We don’t “officially” support Go right now, but the plan is to add support for it very soon. Based on your report, it sounds like we’d need to set this Docker flag, since debugging would be critical for being able to claim support. Thanks for reporting this issue!

**Comment by asw101** [comment]
> We do not rely on container isolation for hostile multi-tenant scenarios. We use VM isolation for each environment/tenant, so there's not much harm in opening this up if it enables important scenarios.
> 
> There are other scenarios we are considering, such as enabling docker-outside-of-docker scenarios via bind mounting the host's docker daemon socket into the container, so that `docker run` from the environment would spin up a sibling container on the host. In this case, the same security considerations apply.

@jkeech This would be incredibly useful, and in fact the very next scenario on my list after Python and Go! It would find it particularly handy for bringing along various developer toolchains ad-hoc as I currently do during local development, as well as accelerating container development.

**Comment by asw101** [comment]
> We don’t “officially” support Go right now, but the plan is to add support for it very soon. Based on your report, it sounds like we’d need to set this Docker flag, since debugging would be critical for being able to claim support. Thanks for reporting this issue!

@lostintangent This is great to hear! The extension itself, and other parts like the language server, etc, seem to be working quite well so far.

**Comment by egamma** [comment]
FYI, this is how go debugging in enabled for VS Code Remote Containers 
https://github.com/microsoft/vscode-dev-containers/blob/328d48644e3094eda053f08689f20577d1d6fbda/containers/go/.devcontainer/devcontainer.json#L10

**Comment by jkeech** [comment]
@asw101, this issue should be fixed now for new environments (we will set those docker arguments when creating the environment's container). Can you try recreating the environment?

**Comment by asw101** [comment]
Delve is working well now, thank you very much!

<img width="710" src="https://user-images.githubusercontent.com/345712/68982940-d53a8780-07d6-11ea-845e-16240ab352a9.png">
