### ISSUE TITLE
"Create Environment" with a specific Git repository branch

### ISSUE THREAD

**Issue by asw101** [MicrosoftDocs/vsonline#143]
I would like the ability to be able to specify a Git Repository branch when I Create Environment (see below):

<img width="340" alt="create-environment" src="https://user-images.githubusercontent.com/345712/68522735-b7bc6980-027c-11ea-8802-7016e1e8b35b.png">

This would enable me to maintain a single repository with various branches for particular environments I can spin up on-demand.

**Comment by lostintangent** [comment]
@asw101 Hey! We’re already tracking this request via #81, so maybe we could close this as a dupe? Let us know if that issue covers your requirements.

**Comment by lostintangent** [comment]
I’m going to close this as a duplicate of #81, but please re-open this issue if #81 doesn’t accurately reflect your request. Thanks!

**Comment by asw101** [comment]
@lostintangent that's excellent, thank you. Sorry I missed the duplicate!
