### ISSUE TITLE
cant run electron tests : SUID sandbox not configured correctly

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/vsonline#144]
Hi,
I'm trying to run a test for a electron application and it fails with the below error 

```
PS /home/vsonline/workspace> npx electron ./test/index.js 
[1202:1109/155045.076440:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/vsonline/workspace/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
```
also an attent to workaround fby avoiding the sandbox fails
```
PS /home/vsonline/workspace> npx electron ./test/index.js --no-sandbox
(electron:1947): Gtk-WARNING **: cannot open display: 
```

source: Josverl/electron-serialport
forked from serialport/electron-serialport

Likely related to :
https://github.com/electron/electron/issues/17972

**Comment by lostintangent** [comment]
@Josverl Thanks for reporting this! If you run the commands in [this comment](https://github.com/electron/electron/issues/17972#issuecomment-486927073), does that unblock you?

**Comment by bjbennet** [comment]
Hi @Josverl 

The error "cannot open display" is being shown because the `npx electron` command is trying to open a seperate window for running the electron app. There is no additional display available for it to use. The only display available is the VS Code window, any additional displays mechanisms are not supported.

**Comment by bjbennet** [comment]
Closing issue. The display behavior is as expected.
