### ISSUE TITLE
Docker image and dockerfile customization

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#15]
Expand the availability of using docker images and dockerfiles to customize an environment.

**Comment by connorshea** [comment]
Sorry if this is the wrong place to leave this feedback, but the `The below Docker related properties require the customContainers experimental feature flag to be set to true.` bit in the note on that page doesn't seem to actually link to any existing section, and I'm not sure where I'm supposed to set this feature flag.

**Comment by chrfrenning** [comment]
+1 on docker support. Specifying container images to download and load would help create isolated development environments, e.g. by running mongod/sqlserver or other app dependencies within the environment. Containers should load before the init script so that data e.g. can be loaded prior to the environment becoming ready.

Alternatively, support for a teardown script would allow me to init containers in ACI as the environment spins up, and take them down when the environment suspends/is killed.

**Comment by bergmeister** [comment]
The docs states that this is possible but following the issues here, it seems it is not?
https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring#visual-studio-online-configuration-reference

**Comment by julioct** [comment]
Hey folks, spend at least two hours trying to use the [.net core 3.1 SDK image](https://hub.docker.com/_/microsoft-dotnet-core-sdk) for my environment following the docs [here](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring#docker-properties) but it looks like such support has not been shipped. Can we ship this support or at least update the docs to mention that using your own image is not really supported?

**Comment by Uili-Simteau** [comment]
@lostintangent Hi Jonathan, any indication when this functionality will be shipped?  I'm asking you in reference to your closing comment from issue: [Custom environments from dockerfile #216](https://github.com/MicrosoftDocs/vsonline/issues/216).

Cheers,

Uili

**Comment by simondmorias** [comment]
When you create an environment with a custom container and it fails to create - is there anyway to see the logs to work out what failed? I have a container that builds locally, but when I try to use in vsonline it says "The custom container could not be built".

**Comment by edgonmsft** [comment]
Hi @simondmorias! When you create the environment from our extension on VSCode after about 30 seconds you should see a terminal appear with all the commands we run to create the container and their output, that should give you a clue. We are working on improving the experience and porting it to VSO.

If you have any specific questions about the process please let me know! Also if the repository is public would you mind giving me the link to take a look?

**Comment by simondmorias** [comment]
Thanks @edgonmsft I actually just realised the in experience in app is actually better. I got to the bottom of my issue (after a lot of attempts!). The repo is here https://github.com/simondmorias/testing-vsoDocker. 
I'm trying to get a pyspark container with PSCore - almost there.
Is it possible to create a container from a specific branch?

**Comment by edgonmsft** [comment]
Great! That's good to know.

On the branch question, we don't support it right now but will in the future. For now we clone the default branch, as a workaround I'm pretty sure that if you change the default branch on GitHub to the branch you need it will work.

**Comment by welliegeee** [comment]
Any updates on this? Our team is waiting on this function before adoption.

**Comment by jkeech** [comment]
@welliegeee, if you create the environment in VS Code desktop with the latest version of the VSO extension installed, it will honor devcontainer.json. We are working on enabling it for environments created from the VSO web portal soon.

**Comment by Uili-Simteau** [comment]
Thanks for the update @jkeech

**Comment by jkeech** [comment]
The web portal now supports `devcontainer.json` for customizing environments. 🎉

**Comment by jonnyhork** [comment]
@jkeech Should we expect to see any extensions listed in the `devcontainer.json` installed when the environment starts up at this point? Unfortunately that does not seem to be the case in my tests. Thanks!

**Comment by jonnyhork** [comment]
Never mind ☝️
I was directed to this issue #334
