### ISSUE TITLE
git push not working

### ISSUE THREAD

**Issue by vermegi** [MicrosoftDocs/vsonline#150]
When trying to push from VSO to one of my repo's, I get the following error: 

vsonline:~/workspace$ git push
remote: Permission to beluxappdev/azure-spring-cloud-training.git denied to vermegi.
fatal: unable to access 'https://github.com/beluxappdev/azure-spring-cloud-training.git/': The requested URL returned error: 403

I am a member of the beluxappdev organization and am able to push to it from another VM., with the same account.

Also, in the same VSO environment, I am able to clone and push to one of my own repo's (github.com/vermegi).

**Comment by edgonmsft** [comment]
Hi Gitte! 

Just a couple of questions, was the repository cloned automatically when you created the environment? 

Are you able to clone the repository locally on the computer from which you are connected to the environment? We proxy your local credentials so that's a good indicator of where the problem is.

Thanks!

**Comment by jkeech** [comment]
It sounds to me like the Visual Studio Online OAuth app might not be approved for that organization. You could confirm in your GitHub settings whether the app is approved (or is pending approval) in that org. If that’s the case, you would need an org admin to approve the app.

________________________________

**Comment by vermegi** [comment]
I tried both ways for accessing the repo. First try was linking it directly to my VSO environment on creation. When that didn't work, I deleted all folders in the workspace and did a git clone of the repo. In both cases clone and pull worked just fine, only push to the repo is not allowed. 

Also, when looking at the settings of the beluxappdev github organization, I don't see VSO as a Thrid-party application: 

![image](https://user-images.githubusercontent.com/1042817/68540232-9d72b080-038e-11ea-8144-1c51ea447c24.png)

There is also nothing at: 

![image](https://user-images.githubusercontent.com/1042817/68540241-cbf08b80-038e-11ea-8c92-06c44cc5168c.png)

In which of these two views would the VSO app need to pop up?

**Comment by jkeech** [comment]
@vermegi, can you try following the instructions at https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/requesting-organization-approval-for-oauth-apps to request access for the application in your organization?

**Comment by vermegi** [comment]
Yes, excellent, that made it work. First time granting and giving in my password did get me to a page stating 'something went wrong'. But then refreshing and re-granting did the trick. 
I am wondering whether something similar happened from VSO the very first time. In any case, at that time, I wasn't able to re-trigger the authorization process from VSO. 

Thanks a lot for the help!
