### ISSUE TITLE
self-hosted environment from running docker container

### ISSUE THREAD

**Issue by mac2000** [MicrosoftDocs/vsonline#152]
Wondering whether it will be possible to have an preconfigured docker image as an environment

e.g. I have docker for windows installed on my PC and wish to expose one of its containers as an evironment to vscode online to use it in browser from laptop

intent here to have reusable image which can be shared between team members also it is not always desirable to expose local machine docker seems to be an better option here

**Comment by taiyosogawa** [comment]
@mac2000 thank you very much for the feedback - the input is very helpful in helping us prioritize. 

We don't yet support this use case, but we've gotten a few similar requests, which we're tracking on #116. To help us consolidate and organize, we'd love to continue the discussion on that issue.
