### ISSUE TITLE
Cannot "Open a remote window" from VS Code

### ISSUE THREAD

**Issue by MarcSkovMadsen** [MicrosoftDocs/vsonline#153]
Hi 

I'm trying to work in VS Code and connect to an already existing Visual Studio Online Environment

![image](https://user-images.githubusercontent.com/42288570/68541894-78d60300-03a5-11ea-8545-144f05b94055.png)

I click the "yellow" "Open a remote window" icon at the bottom left and select the "streamlit" environment.

![image](https://user-images.githubusercontent.com/42288570/68541901-a753de00-03a5-11ea-89c8-91af567c358a.png)

![image](https://user-images.githubusercontent.com/42288570/68541906-b33fa000-03a5-11ea-9d01-a5967ea90900.png)

![image](https://user-images.githubusercontent.com/42288570/68541916-c81c3380-03a5-11ea-8cfd-c3542e6898d0.png)

It just continues with the "Opening Remote" command.

I can't find any more information.

One potential cause could be that I have also been trying out the online experience at 

https://online.visualstudio.com/environment/MYUIDHERE

But I don't know.

**Comment by MarcSkovMadsen** [comment]
And again

![image](https://user-images.githubusercontent.com/42288570/68542406-8478f800-03ac-11ea-8eba-12cbcdaa0582.png)

**Comment by MarcSkovMadsen** [comment]
I have experienced a few times that if I `toggle Developer Tools` under the `Help` menu item then it starts reconnecting and succeeds. Strange :-)

![image](https://user-images.githubusercontent.com/42288570/68542554-103f5400-03ae-11ea-9646-00b7cd93330f.png)

**Comment by MarcSkovMadsen** [comment]
This is my VC Code settings

![image](https://user-images.githubusercontent.com/42288570/68542564-2fd67c80-03ae-11ea-9b55-c559d56d3f2f.png)

**Comment by lostintangent** [comment]
I’m going to close this since I believe this issue has been resolved, and we haven’t heard other reports of it. However, please re-open this if you’re still encountering the bug. Thanks!
