### ISSUE TITLE
Port forwarding (proxy) in vsonline

### ISSUE THREAD

**Issue by loiane** [MicrosoftDocs/vsonline#157]
I tested the proxy support between a JavaScript/TypeScript front-end application and a node.js application within the same repository and it does not seems to work. 

Example:
Front-end running on localhost:3001
Back-end (Node) running on localhost 3000

Both apps running on the same vsonline workspace.

By default, we would need CORS, but Webpack has a dev-server configuration that allows to use proxy, thus, removing the requirement for CORS (https://webpack.js.org/configuration/dev-server/#devserver-proxy)

This would be a nice functionality to have for developers that work with front-end frameworks (Angular, React, Vue) and Node.js in the same repo.

**Comment by jkeech** [comment]
I haven't tried this scenario myself, but quickly looking at the docs makes it seem like this scenario should work with the current port forwarding implementation. What issues are you seeing when this webpack proxy is enabled on the server side?

**Comment by DanTup** [comment]
I just opened https://github.com/MicrosoftDocs/vsonline/issues/164 which may be the same as this. The request to the backend gets a "You need to sign in first, redirecting..." page which has no CORS headers. That means the request fails from an app on a different host/port.

**Comment by loiane** [comment]
It seems it's working now.
Sample repo: https://github.com/loiane/vsonline-port-forwarding

**Comment by DanTup** [comment]
This doesn't seem to work for me - it seems worse than before - it won't even load the simple page:

![Screenshot 2020-05-06 at 15 28 57](https://user-images.githubusercontent.com/1078012/81189405-6b917e00-8fae-11ea-87df-aa38f9e54e88.png)

Yet if I use `curl` in a terminal window in the VS Codespace window, it works fine:

![Screenshot 2020-05-06 at 15 29 15](https://user-images.githubusercontent.com/1078012/81189448-79470380-8fae-11ea-936d-80c6063399b6.png)

This first bit (loading the app) used to work, and it failed on the next step (where a service made a call to the backend).
