### ISSUE TITLE
Suspended environments aren’t automatically resumed when connected to from the “Open recent” list

### ISSUE THREAD

**Issue by timheuer** [MicrosoftDocs/vsonline#159]
When opening up a recent folder using VS Code after a weekend I am not able to due to this error:
![image](https://user-images.githubusercontent.com/4821/68624715-4ce17d00-048c-11ea-835a-1121402986b4.png)
It would be nice if the error:
- Was actionable: provide me with the option to click a link to online.visualstudio.com/ to restart my environment or a direct "start" option here
- maybe automatically started it and showed me progress

**Comment by lostintangent** [comment]
Did you see this error when trying to connect to a self-hosted environment? It would be unexpected if you saw this error for a cloud-hosted environment, so I just wanted to double-check.

**Comment by timheuer** [comment]
@lostintangent I'm not sure I know the difference between self-hosted and cloud-hosted :-) -- I assume it is cloud hosted as I *initially* connected to it from that environment.  After a weekend passed, I launch VS Code, Open Recent and choose the project:
![image](https://user-images.githubusercontent.com/4821/68625350-c29a1880-048d-11ea-8a2b-5278f1370fb2.png)

**Comment by lostintangent** [comment]
Hmm, OK, you should have never seen this error! So this is a bug that we need to fix :) Thanks for reporting it!

**Comment by jkeech** [comment]
The environment is probably suspended. We don't currently unsuspend if you enter through that path. Can you instead find the environment in the Remote Explorer view (or in the web portal at online.visualstudio.com) and connect from there? If you do that, it will first unsuspend the environment and then connect to it.

**Comment by timheuer** [comment]
@jkeech I suppose I could but a few things on that experience:
- This assumes I track immediately to what icon is 'remote explorer' and that I use those icons and it's getting a little crowded:
![image](https://user-images.githubusercontent.com/4821/68628985-0f362180-0497-11ea-87a6-34ff10fff957.png)

- That I change my familiar workflow in opening a project to NOT use the natural means to do so and instead go to an extension and connect to an environment.

I would assume that if you are going to put my project/environment in the MRU list, that it should work as expected...otherwise (and a possible solution) is to not put an entry in MRU.

**Comment by jkeech** [comment]
@timheuer, totally agree. We have a separate issue tracking the work to make it automatically unsuspend in the places where it currently doesn't (can't find the reference offhand right now). I didn't mean to imply that the current behavior is good.

My comment was more related to troubleshooting your issue. If my recommendation works, then it's definitely the same issue I mentioned. For reference, the remote explorer icon is the 5th from the top in your activity bar screenshot. It's the one with the computer and the "><" symbol that VS Code uses for remote environments.

**Comment by timheuer** [comment]
@jkeech yep, from a troubleshooting standpoint, using the extension UI and/or re-activating from the site works.  Thanks for listening to the feedback on the desired flow though

**Comment by jkeech** [comment]
Thanks for confirming!

**Comment by jkeech** [comment]
This issue was fixed a while back 🎉. Closing, but feel free to file a new issue if you see this happen again.
