### ISSUE TITLE
Random error when opening a recent folder

### ISSUE THREAD

**Issue by timheuer** [MicrosoftDocs/vsonline#160]
When opening a recent folder using VSCode I'm getting an unactionable error message:
![image](https://user-images.githubusercontent.com/4821/68624831-90d48200-048c-11ea-9e3f-7a605b321c15.png)
This doesn't tell me anything and uses terminology the user is not seeing in any of the portions of the client.

**Comment by rajkumar42** [comment]
Same as #130. Please track that issue for updates.

**Comment by timheuer** [comment]
@rajkumar42 can you explain how they are related?  one seems to be talking about a user/login authority and the other bug #130 is talking about unclear naming in the MRU.
