### ISSUE TITLE
Visual studio online billing error

### ISSUE THREAD

**Issue by photonn** [MicrosoftDocs/vsonline#166]
Hi guys,

   Tried the new Visual Studio Online service on Friday after the Microsoft Ignite. I only did a quick test, configured an environment, connect it to a git repository, and changed the readme.md file. I closed the environment and went home for the weekend. 

   On Monday morning budget alert email came to me saying that I consumed all my subscription budget over the weekend. That should be not possible because when you are not using your Visual studio online resources, you should be charged only a nominal fee (I did the math and I should have been charged less than an euro till Monday). I deleted everything at azure portal and contacted support on this, but today the costs are still pilling up! support said that are going to contact the visual studio team on this.

   I'm a little bit worried because the projected costs at the end of the month are more than 200€ and I dont want to involve my bank on this. Does this happened to any of you? Thanks in advance for your help.

**Comment by jkeech** [comment]
Hi @photonn, sincere apologies for this issue. We have identified an issue in the way the billing is calculated for a portion of environments. We are actively rolling out a fix, and will be working with support to fix the billing (reverse the extra charges) for all affected users.

**Comment by photonn** [comment]
Thanks jkeech. I'm less worried now. I'll add this ticket to my support request so they can have more info on the issue. 

Regards.

**Comment by photonn** [comment]
Closing this issue. I'll continue at my support ticket. Thanks again for the info.

**Comment by photonn** [comment]
Checked today and cost and analisys is showing the right data. Thanks for the effort.

Regards.

**Comment by jkeech** [comment]
@photonn, thanks for confirming! We are continuing to work with support to process the refunds/credits for the amount that was overcharged prior to the fix rolling out. Again, I’m really sorry for the issue and any inconvenience it caused.
