### ISSUE TITLE
Indicate when an environment contains uncommitted/unpushed changes

### ISSUE THREAD

**Issue by lostintangent** [MicrosoftDocs/vsonline#168]
We want to enable developers to treat their environments as ephemeral, and therefore, delete them as soon as they've finished a specific task (e.g. PR review, prototyping, bug fix). With support for `devcontainer.json` and dotfiles, the repository is already the "source of truth", and therefore, enables a fully repeatable setup process, that allows the codebase to be a ["pet"](http://cloudscaling.com/blog/cloud-computing/the-history-of-pets-vs-cattle/) and the environment to simply be ["cattle"](http://cloudscaling.com/blog/cloud-computing/the-history-of-pets-vs-cattle/).

However, in order to assist developers in not losing their work, we need to explore how to best raise awareness of uncommitted code changes, so that folks don't accidentally lose work if/when they delete an environment. For example, we could discuss doing the following things:

1. When a user disconnects from an environment, we could ask them if they'd like to push their uncommitted changes (if there are any). Furthermore, we could even explore allowing a user to opt-in to having VSO automatically push changes on disconnect

1. When a user attempts to delete an environment, we would warn them if there were uncommitted changes, and if so, allow them to push them automatically

1. Once we implement #151, we would likely want to enable users to specify that they don't want environments automatically deleted, if they have uncommitted changes

**Comment by arjun27** [comment]
This would be very helpful for my workflow. In addition to uncommitted changes, it would be useful to know if there are commits that haven't been pushed to the repo remote.

**Comment by lostintangent** [comment]
@arjun27 Good call! Just updated the title to call out unpushed changes as well.

**Comment by cmbrose** [comment]
@lostintangent  - you touched this I think in the 2nd item, but it could also be useful to have a setting to auto-commit/push any changes.  That helps the user could avoid getting a lot of shutdown prompts.  It also protects in the 3rd scenario - the admin can still force the delete, but the dev can override and say "before this is auto-deleted, push all my changes."

**Comment by lostintangent** [comment]
Yeah exactly. I think the auto-push is where this becomes extremely compelling. Then, we could actually enable an E2E where the environments can be entirely disposable, with their lifetimes managed by the service, without any work being lost, and without incurring productivity drops when having to re-create the environments (since we can spin them up quickly, to the same state you were in before).

**Comment by nikmd23** [comment]
I'll also add, it would be helpful to know if there are any dirty files (that haven't been saved yet so Git doesn't know about the change). This is usually handled by a local editor - either by warning you about dirty files when you close the tab, or by auto saving.

**Comment by bowdenk7** [comment]
This happened to me this morning. Dumpstered an environment that had un-pushed changes. Came to ask for exactly #2 above.

**Comment by lostintangent** [comment]
@bowdenk7 Yeah we need to prioritize this soon. I’ve heard the same story (accidentally losing work) from two other users this week, so we obviously need to be much more assistive here.

**Comment by lostintangent** [comment]
This has now been shipped 🤗
