### ISSUE TITLE
Ctrl + mouse scroll up/down is not working for a connected environment page

### ISSUE THREAD

**Issue by kumarz** [MicrosoftDocs/vsonline#173]
Ctrl + (keyboard +/-) works fine for  scaling the page up and down 

but it is not working with ctrl + mouse scroll up/down.

steps to reproduce:

1) login to VSO
2) select a billing plan that has an environment
3) press CTRL + mouse scroll for either up / down
4) connect to an environment
5) press CTRL + mouse scroll for either up / down to make it normal

it wont come back to normal.

workaround: to use CTRL + keyboard (+/-) to bring it back to normal.

![image](https://user-images.githubusercontent.com/22509606/68719410-c9459000-0560-11ea-9791-32353f8b63aa.png)

**Comment by legomushroom** [comment]
@kumarz is it the VSO Web issue? It seems to be a VSCode workbench problem, so it makes sense to file the issue on VSCode repo.

**Comment by kumarz** [comment]
Tested it with VScode web server version and came to know that its not an issue with VSO portal. Hence closing the issue.

**Comment by srivatsn** [comment]
@kumarz can you file this issue in the vscode repo?

**Comment by kumarz** [comment]
@srivatsn I looked it up and found that there is an existing [issue](https://github.com/microsoft/vscode/issues/37727) with Vscode team.
