### ISSUE TITLE
Doc on dotfiles needs update

### ISSUE THREAD

**Issue by KSiig** [MicrosoftDocs/vsonline#179]
[Doc Link](https://docs.microsoft.com/en-us/visualstudio/online/reference/personalizing)

In the current doc it shows the `dotfiles command` as being able to run from anywhere.

![image](https://user-images.githubusercontent.com/47949712/68805705-a4d2dc00-0664-11ea-8dd2-41ee7184085d.png)
It seems that it's since been changed to run from inside the cloned dotfiles repo

**Comment by jkeech** [comment]
@KSiig, can you clarify the issue? I don't think the screenshot is wrong today. The settings show where the dotfiles will be cloned as well as which script is executed. There is no setting for changing the working directory, which is currently the dotfiles target path. Let me know if I misunderstood what you were saying.

**Comment by KSiig** [comment]
Yeah of course. It may be that this is an anomaly and only happened to me, but here's my experience:
If I were to insert the exact same thing as shown in the screenshot, it would clone the repo to `/home/vsonline/dotfiles`, as it should. However it would try to run the script from `/home/vsonline/dotfiles/~/dotfiles/install.sh`.

I changed it to remove the `~/dotfiles/` in the `Dotfiles Install Command` option, and it worked as it should. 

Honestly I think it makes sense that the the install command is run from inside the cloned repo, that's just not what is documented. At least in my case.

**Comment by jkeech** [comment]
Ah oh. Yes, I agree that the dotfiles install command should be something within the cloned dotfiles repo. We can make it clearer that the path needs to be a relative path from the repo root, and also fix up the screenshot to provide a working example. Thanks!
