### ISSUE TITLE
Allow definition of user upon environment creation

### ISSUE THREAD

**Issue by KSiig** [MicrosoftDocs/vsonline#180]
Instead of having to use the default `vsonline` user, I'd like to use my own username. Both for vanity reasons but also some practical. Especially if SSH-key passthrough is enabled in the future.

I imagine it could be another filed within settings. An example config could be:
```
{
  "vsonline.linux.userName": "<username>",
  "vsonline.linux.userGroups": "<username>, sudo"
}
```
Then the password for the user could either be retrieved by asking for it upon creating a new environment, or through an environment variable on the local host.

**Comment by lostintangent** [comment]
This has been resolved, and you can now set the “containerUser” or “remoteUser” setting in your repo’s devcontainer.json file 👍 You can find more details here: https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference.
