### ISSUE TITLE
Cannot select Azure subscription from a different Azure Directory

### ISSUE THREAD

**Issue by yaakov-h** [MicrosoftDocs/vsonline#181]
My personal Microsoft Account is linked to two different Azure Directories. One is my personal account with a single Pay-As-You-Go subscription, and other is delegated control of my corporate MSDN account with the MSDN complimentary subscription.

When I sign in to Visual Studio Online with my personal account, the Create A Billing Plan dialog only lets me select the MSDN subscription. It doesn't let me select my PAYG subscription, or even seem aware that it exists.

It seems like VSO has found the MSDN AAD and is stuck in there.

**Comment by jkeech** [comment]
This is a current limitation in VSO -- it only allows you to use the default tenant. Supporting multiple tenants is something we are actively working on, but it will probably take about a month to roll out. This feature is being tracked in #39. Thanks!
