### ISSUE TITLE
I can't Sign in Visual Studio Online website

### ISSUE THREAD

**Issue by Innei** [MicrosoftDocs/vsonline#184]
webiste: <https://online.visualstudio.com/login>

when I click the Sign in btn, and then open a window which let  me login. But after I log in, web page does not redirect happen. It always let me login and login ...

I am using Chrome, MacOS 10.14.5.

![image](https://user-images.githubusercontent.com/41265413/68817475-c364c180-06bc-11ea-83de-87a07f842ccf.png)

**Comment by 0ut0fcontrol** [comment]
Try: removing Chinese characters from account name.

**Comment by Innei** [comment]
> Try: removing Chinese characters from account name.

OK, it works.

**Comment by legomushroom** [comment]
We want to enable high-end characters in the names if AAD supports this. Reopening.

**Comment by albingroen** [comment]
I am having the same issue here. Although I don't have any Chinese characters in my account name. Any other ideas of what could cause this @legomushroom? It's basically just a loop of sign in windows.

**Comment by albingroen** [comment]
This seems to work: https://github.com/MicrosoftDocs/vsonline/issues/345#issuecomment-600177981

**Comment by rido-min** [comment]
Same issue here, no extended chars.

**Comment by sevakraynov** [comment]
Same issue, but i have cyrillic chars in account name
Win10 x64, Microsoft Edge on Chromium 83.0.478.25
![image](https://user-images.githubusercontent.com/23610614/81259497-20787900-9049-11ea-98f6-e2d6c6dc0e93.png)

**Comment by legomushroom** [comment]
@sevakraynov can you try incognito mode (without being logged in into Edge)?

**Comment by dmostert** [comment]
It works with my personal account, but not with my work account - even in incognito mode.

**Comment by klvnraju** [comment]
Can you try reproducing the issue again? We changed our auth flow and hence wanted to check if that has fixed the issue or not.

**Comment by rido-min** [comment]
I cannot repro anymore

**Comment by sevakraynov** [comment]
@klvnraju @legomushroom 
can not reproduced, i logged in

**Comment by klvnraju** [comment]
Thanks a lot for letting us know.

**Comment by legomushroom** [comment]
Great, closing the issue.

**Comment by inkerinmaa** [comment]
![image](https://user-images.githubusercontent.com/5521235/85603449-0de9eb80-b659-11ea-8f05-0ffa5e7e1efa.png)
Same issue. Cannot login - when I enter my email and push "Next" page is just reloading and everything repeats
