### ISSUE TITLE
Only one subscription available in dropdown when creating a billing plan

### ISSUE THREAD

**Issue by brennaman** [MicrosoftDocs/vsonline#186]
I have multiple Azure subscriptions but only one subscription is available in the dropdown when creating a billing plan.

**Comment by jkeech** [comment]
Are your subscriptions in different AAD directories? If so, this is probably related to #39.

**Comment by brennaman** [comment]
Yes they are.  I just looked at #39 and I like the tenant dropdown idea.  Thanks.
