### ISSUE TITLE
devcontainer.json Docker settings have no effect

### ISSUE THREAD

**Issue by erickpeirson** [MicrosoftDocs/vsonline#194]
It appears that neither the `image` nor `dockerFile` parameters in `devcontainer.json` have any impact on environment creation on VS Online.

# Expected behavior

The `image` and `dockerFile` settings should be used to control the image that is used to create the environment, as described in this documentation: https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring

# Steps to reproduce:

1. Create a new GitHub repository
2. Copy `devcontainer.json` and `Dockerfile` from https://github.com/microsoft/vscode-dev-containers/blob/master/containers/go/.devcontainer/ into `{repo root}/.devcontainer`. In the example below, I uncommented the `postCreateCommand` on L24.
3. Create a new environment via https://online.visualstudio.com/environments
4. Once the environment is created, open a terminal. Here is the output from the `VS Only` read-only terminal:

```
vsonline:~$ OPERATION_ID=1f7cd637-789a-40ee-b91a-8821b5140ee4 /.vsonline/bin/vso exec git ls-remote https://github.com/erickpeirson/foo.git heads/master
[2019-11-17 00:41:04.616 CLI I] vso v1.0.1287.3736 (pid: 107)
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[VS Online][1f7cd637-789a-40ee-b91a-8821b5140ee4] Process exited with non - zero result (128).
vsonline:~$ OPERATION_ID=1f37e2d7-6c58-45ad-9c8d-8318d5f1bad4 /.vsonline/bin/vso exec git ls-remote https://github.com/erickpeirson/foo.git heads/master
[2019-11-17 00:41:25.272 CLI I] vso v1.0.1287.3736 (pid: 232)
0887bd2477e4d894191ac88cd033868266ddf189        refs/heads/master
[VS Online][1f37e2d7-6c58-45ad-9c8d-8318d5f1bad4] Process finished successfully.
vsonline:~$ OPERATION_ID=845bf9fb-496b-492f-9c3f-4d6669aefd13 /.vsonline/bin/vso exec git clone  https://github.com/erickpeirson/foo.git /home/vsonline/workspace
[2019-11-17 00:41:29.709 CLI I] vso v1.0.1287.3736 (pid: 316)
Cloning into '/home/vsonline/workspace'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 39 (delta 12), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (39/39), done.
[VS Online][845bf9fb-496b-492f-9c3f-4d6669aefd13] Process finished successfully.
vsonline:~$ OPERATION_ID=0b859baf-7a64-4745-9bda-36eaa3c38376 /.vsonline/bin/vso exec sourcer.sh /home/vsonline/.vsonline/.cloudenv-scripts/postCreateCommand.sh
[2019-11-17 00:41:34.052 CLI I] vso v1.0.1287.3736 (pid: 391)
/home/vsonline/.vsonline/.cloudenv-scripts/postCreateCommand.sh: line 3: go: command not found
[VS Online][0b859baf-7a64-4745-9bda-36eaa3c38376] Process finished successfully.
``` 

Note that the repository was cloned successfully and is at the most recent commit.

I also tried using `"image": "golang:1.13.4-buster"` in place of the `dockerFile` parameter. The result was the same.

**Comment by edgonmsft** [comment]
Hi Erick!

This feature is currently under development and should be ready in a preview way in the next couple of weeks.

We are tracking that development on https://github.com/MicrosoftDocs/vsonline/issues/15

That way we can also give updates on all the variations as they are supported and get feedback. Thanks!
