### ISSUE TITLE
unable to resume suspended environments

### ISSUE THREAD

**Issue by afeld** [MicrosoftDocs/vsonline#197]
Steps to reproduce:

1. Create an environment
1. Open the web-based editor
1. Open the command palette and type `suspend`
1. Click `VS Online: Suspend environment`
1. Click the current environment
1. Click `Disconnect and suspend`
1. Go back to [the dashboard](https://online.visualstudio.com/environments)
1. Click the environment

The environment then seems to hang in its `Starting` state. I'm having the same problem with auto-suspended environments, so kind of surprised I couldn't find a report of this.

**Microsoft account email:** aidan.feldman@gmail.com
**Visual Studio Online plan:** `vso-plan-eastus`

Thanks!

**Comment by jkeech** [comment]
Sorry you are having issues. Adding @edgonmsft to help investigate.

**Comment by edgonmsft** [comment]
Hi Aidan!

Thanks for the report, we now have a pretty good idea of what caused the issue but wanted to verify with one of your environments. If you did not delete them could you send us your environment id?

To get it go to the management portal, and go to developer tools and see on network tab the get environments request, the response will have the environment Id. Also if you try to start the environment again you would see us polling the id for status.

Thanks!

**Comment by afeld** [comment]
I've been cleaning them up, but will leave the one with ID of `1943216b-f181-453b-844c-1362d3f0e104` there. Thanks!

**Comment by carl-parrish** [comment]
I'm running into this as well would love to give you the environment IDs (I have two of them) but have no idea how to get to the management portal to get what you are asking for. 

![image](https://user-images.githubusercontent.com/4809833/69263096-e0e4d000-0b81-11ea-9c9e-e9e2322b8d98.png)

**Comment by edgonmsft** [comment]
@carl-parrish If you refresh the page with the network tab open you should be able to see a request named environments, that one will have the id and name.

Thanks!

**Comment by carl-parrish** [comment]
@edgonmsft Here they are. 

02b86295-1816-4896-97f8-5a89de47b1d1
&
92501f1d-0b6f-4465-9179-8823c610730b

**Comment by edgonmsft** [comment]
Hi @afeld and @carl-parrish could any of you confirm if you have signed out from LiveShare while connected to the environment?

**Comment by afeld** [comment]
I didn't touch LiveShare.

**Comment by carl-parrish** [comment]
Don't believe I ever turned LiveShare on either.

**Comment by carl-parrish** [comment]
I was flat out wrong I **did** use LiveShare to view my app. and I never did anything special to sign out.

**Comment by edgonmsft** [comment]
Thanks for your help!

We are in the process of testing the fix that should allow you to resume this environments and prevent this from happening again.

I'll let you know once its out.

**Comment by jkeech** [comment]
@afeld @carl-parrish we rolled out a fix to the West US 2 and East US regions. If your environments are in either of these regions, can you retry? Suspend and then start again and they should come back up.

**Comment by afeld** [comment]
Starting the environments I created before wasn't successful, but I was able to create, suspend, then restart a new one. That's fine for my purposes, so feel free to close the issue if that's a "good enough" fix. Thanks!

**Comment by edgonmsft** [comment]
Mmmm specifically the environment with the Id you gave us initialy? There might be another additional issue here, I'll keep this one open while I continue to investigate.

**Comment by afeld** [comment]
Correct.

**Comment by carl-parrish** [comment]
I haven't been able to resume any of the environments I had created before. I'll try with a new one. My issue may also be related to https://github.com/MicrosoftDocs/vsonline/issues/19 as I have websockets in my app.

**Comment by edgonmsft** [comment]
@carl-parrish Could you let us know if new ones work fine?
I tried checking the environments you reported initially but they looked to be deleted. Do you have any environment with the issue that has not been deleted?

**Comment by carl-parrish** [comment]
Here are two that seem to still have the issues. 
"id": "bc8ba15b-c0c2-4b69-9cba-0fa9dc234a54",
"id": "92501f1d-0b6f-4465-9179-8823c610730b",

Error message I get when trying to open one of the new environments. 
The webpage at https://online.visualstudio.com/environment/bc65cf7e-1585-4676-8edf-e2a0d9d6c522?correlationId=656ae48f-f2ba-4e17-82b4-4d01a941ea87 might be temporarily down or it may have moved permanently to a new web address.

Same thing for this one. 
This site can’t be reached The webpage at https://online.visualstudio.com/environment/28c66ce0-622b-4d38-83b3-6f0d6dafa5f2?correlationId=cda23419-4b08-4395-b3b9-42771b7bd09a might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED

**Comment by edgonmsft** [comment]
Hi @carl-parrish thanks for your response.

Could you start those environments? If they get stuck in starting you wont get charged and then I can investigate.

As an additional check could you start them from the portal or from VSCode using the extension?

Thanks!

**Comment by carl-parrish** [comment]
Progress of sorts. Now I can start each environment. So that it says that the environment is Available. But now I'm getting the "...might be temporarily down..." error message even for brand new environments. I'm currently on a GoogleOS laptop so it might be a while before I can check them from VSCode. Not sure how to start from the portal but if you can provide instructions I'm willing to try.

**Comment by carl-parrish** [comment]
```
[
  {
    "id": "92501f1d-0b6f-4465-9179-8823c610730b",
    "type": "CloudEnvironment",
    "friendlyName": "advinow2",
    "created": "2019-11-19T22:13:00.5728829Z",
    "updated": "2019-12-10T21:36:10.3225549Z",
    "state": "Starting",
    "seed": {
      "type": "Git",
      "moniker": ""
    },
    "connection": {
      "sessionId": "0C66B44E53F101D1F7A267D2A77812058274"
    },
    "location": "WestUs2",
    "autoShutdownDelayMinutes": 30,
    "skuName": "standardLinux",
    "skuDisplayName": "Standard (Linux): 4 cores, 8 GB RAM"
  },
  {
    "id": "bc8ba15b-c0c2-4b69-9cba-0fa9dc234a54",
    "type": "CloudEnvironment",
    "friendlyName": "sandbox",
    "created": "2019-11-21T19:17:44.8135591Z",
    "updated": "2019-12-10T21:08:04.5233738Z",
  
    "state": "Shutdown",
    "seed": {
      "type": "Git",
      "moniker": "https://github.com/carl-parrish/ng7-complete-course.git",
      "gitConfig": {
        "userName": "Carl Parrish",
        "userEmail": "cparrish@carlparrish.com"
      }
    },
    "connection": {
      "sessionId": "E05BDA005FE896A761D57FB4BE457D1B4385"
    },
    "location": "WestUs2",
    "autoShutdownDelayMinutes": 30,
    "skuName": "standardLinux",
    "skuDisplayName": "Standard (Linux): 4 cores, 8 GB RAM"
  },
  {
    "id": "28c66ce0-622b-4d38-83b3-6f0d6dafa5f2",
    "type": "CloudEnvironment",
    "friendlyName": "NG-communication",
    "created": "2019-11-23T14:58:40.7534245Z",
    "updated": "2019-12-10T21:30:00.7318141Z",
    "ownerId": "cc174677-08e6-4f89-9b44-61e5418d9408",
    "state": "Available",
    "seed": {
      "type": "Git",
      "moniker": "https://github.com/DeborahK/Angular-Communication.git",
      "gitConfig": {
        "userName": "Carl Parrish",
        "userEmail": "cparrish@carlparrish.com"
      }
    },
    "connection": {
      "sessionId": "460659261C4893A802D3778348ADC20AA5DC",
      "sessionPath": "/home/vsonline/workspace"
    },
    "location": "WestUs2",
    "autoShutdownDelayMinutes": 30,
    "skuName": "standardLinux",
    "skuDisplayName": "Standard (Linux): 4 cores, 8 GB RAM"
  },
  {
    "id": "bc65cf7e-1585-4676-8edf-e2a0d9d6c522",
    "type": "CloudEnvironment",
    "friendlyName": "Advinow",
    "created": "2019-12-05T18:13:59.7056704Z",
    "updated": "2019-12-10T21:29:16.7652693Z",
     "state": "Available",
    "seed": {
      "type": "Git",
      "moniker": "",
    
    },
    "connection": {
      "sessionId": "A0CC810BD235DCF1E5728CCE0C58078CA3C9",
      "sessionPath": "/home/vsonline/workspace"
    },
    "location": "WestUs2",
    "autoShutdownDelayMinutes": 30,
    "skuName": "standardLinux",
    "skuDisplayName": "Standard (Linux): 4 cores, 8 GB RAM"
  },
  {
    "id": "c8795c12-562a-4de8-8f0e-83d5cb140a72",
    "type": "CloudEnvironment",
    "friendlyName": "NewTest",
    "created": "2019-12-10T21:34:19.564263Z",
    "updated": "2019-12-10T21:34:42.7530943Z",
    "state": "Available",
    "seed": {
      "type": "Git",
      "moniker": "",
      
    },
    "connection": {
      "sessionId": "ED69066F729139BBC1FB47AD0D0685248B9F",
      "sessionPath": "/home/vsonline/workspace"
    },
    "location": "WestUs2",
    "autoShutdownDelayMinutes": 30,
    "skuName": "standardLinux",
    "skuDisplayName": "Standard (Linux): 4 cores, 8 GB RAM"
  }
]

**Comment by carl-parrish** [comment]
FYI - not sure if you guys made changes but it seems that I can now resume each environment (even the old ones)

**Comment by jkeech** [comment]
@carl-parrish Glad to hear! I’m going to go ahead and close this issue since the fix has rolled out everywhere.
