### ISSUE TITLE
Allow deleting plans from within the management clients

### ISSUE THREAD

**Issue by lostintangent** [MicrosoftDocs/vsonline#199]
Currently, we allow creating plans as part of our VSO onboarding experience, but in order to delete a plan, a user needs to go into the Azure portal. To improve this experience, we should allow deleting a plan within VS/VS Code and the web management portal. That way, a user doesn't need to navigate the Azure portal in order to perform common developer tasks.

**Comment by jkeech** [comment]
Plan deletion is now available from the VSO web portal and the VS Code extension in the command palette. 🎉
