### ISSUE TITLE
~/.bash_profile not loaded in new integrated terminal sessions

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/vsonline#20]
In a new Visual Studio Online environment, when launching a new integrated terminal session, the current users' `~/.bash_profile` script isn't getting called:

```bash
vsonline:~/workspace$ echo 'echo "!!!"' > ~/.bash_profile
vsonline:~/workspace$ bash
vsonline:~/workspace$
```

**Comment by jkeech** [comment]
This seems expected to me. `~/.bash_profile` is only executed for login shells. You probably want to put values in `~/.bashrc` instead.

More context:
* https://stackoverflow.com/questions/415403/whats-the-difference-between-bashrc-bash-profile-and-environment
* https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc

**Comment by srivatsn** [comment]
Closing this issue per the comment above. Please reopen if this doesn't work.
