### ISSUE TITLE
Could not connect to VSCode on my machine

### ISSUE THREAD

**Issue by cartermp** [MicrosoftDocs/vsonline#208]
I have the following environment:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/6309070/69443548-76f43400-0d03-11ea-8329-27bb61e6f71a.png">

But when I try to open VSCode from the browser, it open VSCode and asks for a link only for nothing to happen.

Would any diagnostics help? Also I'm in building 18, so I'm easy to grab in-person.

**Comment by jkeech** [comment]
@osortega

**Comment by cartermp** [comment]
Thanks for confirming that the sign-in issue was the root cause. I confirmed that this now works for me. Thanks!
