### ISSUE TITLE
Environment failed to load

### ISSUE THREAD

**Issue by bowdenk7** [MicrosoftDocs/vsonline#215]
3:55PM PST I created an environment from lostintangent/conduit to test something unrelated. After it was created I tried to connect but the environment never loaded with the following errors. 

![image](https://user-images.githubusercontent.com/820883/69487150-084dce00-0e0a-11ea-804c-5767447050bf.png)

Refreshing twice gave me just a black screen. Going to online.visualstudio.com/environments didn't show me any environments. After waiting a few minutes, everything was working again. 

I definitely can't reproduce this, but figured maybe you can look at my environment ID or logs from around the timestamp to see if there are any service side issues.

If this is completely un-actionable feel free to close the issue.

**Comment by lostintangent** [comment]
@srivatsn Is this possibly the VS Code Server timing out? The Conduit repo is really large, and I used to run into this all the time when creating new environments for it.

**Comment by srivatsn** [comment]
Ya I think it's the same issue. We need to have different timeouts for connection vs reconnection.

**Comment by lostintangent** [comment]
This issue has been resolved 👍
