### ISSUE TITLE
Custom environments from dockerfile

### ISSUE THREAD

**Issue by bowdenk7** [MicrosoftDocs/vsonline#216]
I'm having some trouble creating an environment from a non-oryx Dockerfile.

I created this [test repo ](https://github.com/bowdenk7/vso-devcontainer-test) which only contains the following `.devcontainer/devcontainer.json`:
```
{
	"image": "node:8"
}
```

If this works like I expect, creating an VSO environment from this repo would give me an environment with Node 8.

Using the remote containers extension, when I open this folder I get Node 8 like expected:
![image](https://user-images.githubusercontent.com/820883/69487456-25d16680-0e0f-11ea-959a-5e44c947a054.png)

When I use VSO I get the default oryx image (node 12):
![image](https://user-images.githubusercontent.com/820883/69487468-44cff880-0e0f-11ea-83b3-7ced3e92ca74.png)

Am I missing something? The [docs](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring#docker-properties) suggest that this should be supported.

**Comment by lostintangent** [comment]
We don’t currently support custom Docker files or images, though this will be enabled very soon. I’ll ping you as soon as it is deployed 😁 In the meantime, we’re tracking this via #15, so I’ll close this as a duplicate. Please re-open it if that issue doesn’t capture the issue/request fully though!
