### ISSUE TITLE
Self hosted evironments without azure account

### ISSUE THREAD

**Issue by Mister-Hope** [MicrosoftDocs/vsonline#220]
I met a problem here,Since I am a college student in China it’s very hard for me to get my credit card because I don’t have any income so I need to my parents to become my guarantors which my parents don’t want to.So I can not register my account which means I cannot use  vscode online on my server.It seems Vscode can self host a server when using it’s source code, but I cannot find docs about it.

So I just want to use vscode online without a credit card. At present I have no way. The servers I own are all remote severs without GUI. I wonder if anyone could help me, or give me some solutions, thanks.

**Comment by nikmd23** [comment]
Hello @Mister-Hope!

I believe you're in luck. The [Azure for Students](https://azure.microsoft.com/en-us/free/students/) program not only provides free Azure credits, but it allows you to sign up without a credit card. 

Please take a look at that program and let us know how things go.

**Comment by Mister-Hope** [comment]
I tried before, The problem is, azure did not recognize  my university email.
![0CD8DDFD-0BB8-4A5D-8C1A-652916420DFC](https://user-images.githubusercontent.com/33315834/69687258-3c243e80-10fd-11ea-8f56-69d95265ecb9.png)
My email is ending with @nenu.edu.cn, and I used it to get access with webstorm, orginlab and so on. But maybe not in the azure list?

**Comment by Mister-Hope** [comment]
After all, my university is in the top 50 university in China, rank is at around 35, so I have to guess azure pay less attention at chinese universities, I filled in a form on the website trying to get some support, but no one contacted me since

**Comment by Mister-Hope** [comment]
It seems that vscode online is sticked to azure for some reasons(we all know), but we can make a server from the source code right?

**Comment by Mister-Hope** [comment]
Hello, really need some helps here. I tried feedback again and didn't get any reply. So I guess it's still hard for me to have an azure account.

**Comment by nikmd23** [comment]
> we can make a server from the source code right?

You can use [the VS Code Remote Development tools](https://code.visualstudio.com/docs/remote/remote-overview) - no Azure subscription required. Hopefully that helps.
