### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by syado** [MicrosoftDocs/vsonline#222]
Issue Type: <b>Bug</b>

Procedure
Sign in and sign out
Symptoms
I can't sign in again
Extension does not work

Extension version: 1.0.1287
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by syado** [comment]
There is no problem with the network, but the following message is displayed:
You appear to be offline. Please check your network connection.
The network is online.
There is no proxy.

**Comment by nikmd23** [comment]
Are you still experiencing this issue @syado?

**Comment by syado** [comment]
Yes
Enabling the extension will cause a network failure.

**Comment by lostintangent** [comment]
This issue has been fixed 👍 Please re-open it if you’re still experiencing issues. Thanks!
