### ISSUE TITLE
Environment variables for the VS Code process aren't configured by .profile or .bashrc, only .env

### ISSUE THREAD

**Issue by vivlim** [MicrosoftDocs/vsonline#224]
I set up a Rust environment in VS Online using `rustup` and noticed that while I was able to call `cargo` from `bash`, my extensions (specifically, `rust-analyzer`) weren't able to locate `cargo`.

I had added `source $HOME/.cargo/env` to my path in `~/.profile` and `~/.bashrc`, and expected at least one of those to also apply to the VS Code process, but they did not.

The thing that ended up working was creating a `~/.env`, which I tried after reading #100:

```
. $HOME/.cargo/env
```
(note the use of `.` instead of `source`, `/bin/sh` on Ubuntu is implemented by dash)

The login shell configured for the `vsonline` user is `/bin/bash`, it would be nice if the VS Code server were launched by the login shell.

**Comment by jkeech** [comment]
@vivlim, the VS Code server is launched from a non-interactive, non-login shell by the vsonline agent that is running on the backend container. So neither the `~/.profile` or `~/.bashrc` will work. This is why the `~/.env` workaround exists today. The good news is that there are a couple changes in the works to make this better:

1) Custom Dockerfile and pre-built docker image support. This will enable you use a Rust-specific image that already has cargo installed and on the PATH.
2) VS Code is working on formalizing the environment variable requirements for remote containers in `devcontainer.json`, so once that is in place and VS Online is updated to support it, then you could create a `devcontainer.json` that has the required environment variables pre-set, so when the VS Code server is spun up, those variables are added to the shell prior to launching the VS Code server process.

**Comment by lostintangent** [comment]
You can now set environment variables in your devcontainer.json file, using either the “containerEnv” or “remoteEnv” properties. You can find more info on that here: https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference. I’m going to close this as resolved, but please let us know if you run into any issues or feedback 👍
