### ISSUE TITLE
Pls adopt the new extensionKind format in the 'ms-online.vsonline' extension

### ISSUE THREAD

**Issue by egamma** [MicrosoftDocs/vsonline#228]
As of VS Code 1.40 the `extensionKind` attribute in the `package.json` of the extension can be an array, pls see the [documentation](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location). 

We will be deprecating the `string` type for `extensionKind` property in favour of `string array` type.

The `extensionKind` attribute should be set to `["ui", "workspace"]`. Indicating that the extension can run both as a UI extension and as a workspace extension (e.g. in the browser).

More details can be found here https://github.com/microsoft/vscode/issues/85819.

**Comment by lostintangent** [comment]
Thanks for the heads up! 👍

**Comment by jkeech** [comment]
This will be fixed in our next extension release. Thanks!

**Comment by jkeech** [comment]
The latest version of the extension in the marketplace uses the new `extensionKind` format.
