### ISSUE TITLE
Colorization takes longer than language service to kick in when starting cold in the browser

### ISSUE THREAD

**Issue by cartermp** [MicrosoftDocs/vsonline#233]
I noticed this with the XPlot project. You can create an environment with the repo by clicking the VSCode button here: https://github.com/fslaborg/xplot#xplot - then navigating to `src/XPlot.Plotly/Main.fs`.

See below:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/6309070/69926182-75540a00-1481-11ea-803c-45831bd2b53b.png">

The tooltip (and link rendering of the token) comes from a full typecheck of the project, meaning the F# compiler service has already computed what it needs to power all other tooling.

However, the colorization from VSCode that uses Regex has not yet kicked in, giving the impression that the IDE is not yet ready.

**Comment by nikmd23** [comment]
@cartermp, do you always experience this, or is it intermittent? I've been unable to repro this so far.

**Comment by cartermp** [comment]
Looks like the issue was resolved! I can't reproduce it either.
