### ISSUE TITLE
Language service inconsistently started / not started in online environment

### ISSUE THREAD

**Issue by cartermp** [MicrosoftDocs/vsonline#234]
I have two separate environments created from this repo (the Create button): https://github.com/fslaborg/xplot#xplot

Not sure if it helps to list them, but here are the links with GUIDs:

(not working)
https://online.visualstudio.com/environment/0e558e69-d68c-4af9-a134-9167b9293de0

(working)
https://online.visualstudio.com/environment/ff5b46d3-4f24-4d86-85e1-e538890f087a

In the first one, it appears that the language service was never started. Navigating to `src/XPlot.Plotly/Main.fs` and line `114`, attempting to Go to Definition on `jsTemplate` results in a failure - no definition is found.

In the second one, the same action succeeds.

I noticed this happen earlier today but figured it might have been a fluke since I couldn't reproduce it, but I just noticed it again in a new environment.

**Comment by pineapplemango** [comment]
I can consistently repro this issue.

**Comment by pineapplemango** [comment]
@cartermp This issue should be resolved now, can you confirm?

**Comment by cartermp** [comment]
Works now!
