### ISSUE TITLE
Self-hosted environment "Failed to connect to relay"

### ISSUE THREAD

**Issue by JtMotoX** [MicrosoftDocs/vsonline#235]
**Host 1:**
Windows 10
Version 1.40.2

**Host 2:**
macOS 10.14.6
Version 1.40.2

---
I have registered 2 self-hosted environments (details above) and getting the same errors when trying to connect to either of them.  I have tried to restore local environment as well as unregister and again register.  I am able to see both of them in my environments page online but when I try to "Open in VS Code" or "Connect" I get the following errors:

**Connect:**
```
Error: Failed to connect to relay: wss://vsls-prod-ins-usw2-private-relay.servicebus.windows.net:443/$hc/e42***fda?sb-hc-action=connect&sb-hc-token=***61%26skn%3DWorkspaceShareKey
    at WebSocket.n.onerror (https://online.visualstudio.com/static/js/main.ae914e17.chunk.js:1:137546)
```

**Open in VS Code:**
```
Resolving the authority `vsonline` failed

[2019-12-02 01:00:47.351] [renderer3] [error] Error: The environment is currently offline.
	at WebSocketClient.module.exports../node_modules/websocket/lib/WebSocketClient.js.WebSocketClient.failHandshake (c:\Users\***\.vscode\extensions\ms-vsonline.vsonline-1.0.1287\out\prod\extension-prod.js:180587:32)
	at ClientRequest.<anonymous> (c:\Users\***\.vscode\extensions\ms-vsonline.vsonline-1.0.1287\out\prod\extension-prod.js:180526:18)
	at ClientRequest.emit (events.js:205:15)
	at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
	at TLSSocket.socketOnData (_http_client.js:452:22)
	at TLSSocket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at TLSSocket.Readable.push (_stream_readable.js:210:10)
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by jkeech** [comment]
@JtMotoX, the first error looks like a firewall/network issue from the client connecting to the cloud relay to the environment. When you register the environment, it establishes an authenticated connection to a cloud relay so that you can connect to the environment from anywhere. The relay connection itself is authenticated and end-to-end encrypted.

The second failure looks like the environment (host side) was not online or connected to the relay at the time when the client tried to connect. Was the process still running on the host side? Did you see any errors in the logs when trying to register it as a self-hosted environment? Does re-registering it bring it back up?

/cc @taiyosogawa

**Comment by JtMotoX** [comment]
> the first error looks like a firewall/network issue from the client connecting to the cloud relay to the environment.

I registered the VSC instance running on my Desktop here at home. Minutes later I tried connecting to it from my laptop when I get this error.  I don't have any firewall aside from the Windows 10 fw.


> 
> The second failure looks like the environment (host side) was not online or connected to the relay at the time when the client tried to connect. Was the process still running on the host side? Did you see any errors in the logs when trying to register it as a self-hosted environment? Does re-registering it bring it back up?

I never closed the VSC instance running on my desktop.  I registered it, left it open and running, went over to my laptop and when it showed up in the "environments" I tried to connect and got the errors.

**Comment by jkeech** [comment]
Do connections from the browser work to either host, or do those fail as well?

**Comment by JtMotoX** [comment]
The first error was when I tried to use the "Connect" option which opens it in my browser.  The 2nd error is when I try the "Open in VS Code" option which tries to open the connection in my local VSC instance.  I registered my primary desktop and primary laptop, then tried to connect to each of them from my secondary laptop, both of which provides the same errors.
![image](https://user-images.githubusercontent.com/7191259/70089059-4c8c5b80-15cc-11ea-9a8a-b83678deba89.png)

**Comment by mikeburgh** [comment]
If it's any help, I am suddenly having similar issues.. on the host I can register a new self hosted environment, but I cannot connect to it from web or client VS Code install (same errors as initial post)

If I try to restore the local environment on the host, I get an authentication error: 

```
[Command:RestoreLocalEnvironment I] Decorator finishing: Telemetry. Duration: 3ms (0 + 3)
[Command:RestoreLocalEnvironment I] Decorator finishing: ErrorNotification. Duration: 7477082ms (0 + 7477082)
[Command:RestoreLocalEnvironment I] Decorator starting: ErrorNotification
[Command:RestoreLocalEnvironment I] Decorator starting: Telemetry
[Command:RestoreLocalEnvironment E] Command [Unable to restore local environment]: Restore local environment Failure: Unable to authenticate (3520ms)
[Command:RestoreLocalEnvironment I] Decorator finishing: Telemetry. Duration: 1ms (0 + 1)
[Command:RestoreLocalEnvironment I] Decorator finishing: ErrorNotification. Duration: 8225600ms (0 + 8225600)
```

Tried uninstalling and re installing the extensions, as well as signing in and out of Azure.

**Comment by taiyosogawa** [comment]
@mikeburgh, thanks for posting. Your issue looks like the one we are tracking on @#125.

@JtMotoX, I've been able to repro the error messages you're seeing, but I haven't been able to repro the failing restore. It shouldn't have to do with your firewall. It simply appears that the web UI and the desktop app show two different messages for the same problem. We'll look into that separately.

For your immediate issue, I'm wondering if something is killing the process we start when you register your machine. As you register your machine, would you be able to watch running processes using [SysInternals](https://docs.microsoft.com/en-us/sysinternals/) or any tool of your choice? You should see a process called "vsls-agent" spawn from: `<TEMP>/vso/VSOAgent_<OS>_<Version>/vsls-agent` where `<TEMP>` is your temp directory. Note that you might have multiple instances of vsls-agent running, so the path is important here.

Do you see that process start? Does it stop before you connect?

**Comment by JtMotoX** [comment]
@taiyosogawa, I unregistered and then registered again (logs below).  When I register I do see a vsls-agent.exe process spawned (%TEMP%\vso\VSOAgent_win_3264864\vsls-agent.exe) but then it dies within about 2 seconds.

Unregister:
```
[Command:UnregisterEnvironment I] Decorator starting: ErrorNotification
[Command:UnregisterEnvironment I] Decorator starting: Telemetry
[Command:UnregisterEnvironment I] Command [Failed to unregister local environment]: Unregister Environment Success (5612ms)
[Command:UnregisterEnvironment I] Decorator finishing: Telemetry. Duration: 2ms (1 + 1)
[Command:UnregisterEnvironment I] Decorator finishing: ErrorNotification. Duration: 0ms (0 + 0)
```

Register:
```
[Command:RegisterLocalEnvironment I] Decorator starting: ErrorNotification
[Command:RegisterLocalEnvironment I] Decorator starting: Telemetry
[Command:RegisterLocalEnvironment I] Command [Failed to register local environment]: Register local Environment Success (19069ms)
[Command:RegisterLocalEnvironment I] Decorator finishing: Telemetry. Duration: 0ms (0 + 0)
[Command:RegisterLocalEnvironment I] Decorator finishing: ErrorNotification. Duration: 0ms (0 + 0)
```

Not sure if this helps at all but when I launch it manually this is the results:
```
> cd "%LOCALAPPDATA%\Programs\Microsoft VS Code"
> "%TEMP%\vso\VSOAgent_win_3264864\vsls-agent.exe" --pipe "VSLS" --service "https://prod.liveshare.vsengsaas.visualstudio.com/" --autoexit --verbosity All --agentExtensionPath "%TEMP%\vso\VSOAgent_win_3264864\AgentExtensions"
[Agent I] (1002) Trace log: C:\Users\jonathaf\AppData\Local\Temp\VSFeedbackVSRTCLogs\20191203_223637_Agent.log
[Agent I] vsls-agent v1.0.1315.65159 (pid: 4708)
[Agent I] Reminder: You may only use this software with Visual Studio and Visual Studio Code, as described in the license (https://go.microsoft.com/fwlink/?linkid=872556).
[Agent I] Start time: 12/3/2019 10:36:37 PM
[Agent I] Using VSLS service: https://prod.liveshare.vsengsaas.visualstudio.com/
[Agent I] VSLSAgent/1.0.1315.65159 VSLS/2.2 PlatformName/Microsoft Windows 10.0.18362 PlatformVersion/6.2.9200.0
[Agent I]
[Agent V] Loaded assembly: Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost v1.0.1315.65159
[Agent.Proxy I] Proxy settings from env variable: http_proxy was null and https_proxy was null
[Agent V] KeepAlive-> reason:AgentStarted delay:10000
[Agent-ObjectTracker V] Add item:KeepAliveAgent reason:AgentStarted delay:10000 count:1
[Agent I] (1001) Listening on pipe "VSLS"
[Agent-ObjectTracker V] Remove item:KeepAliveAgent reason:AgentStarted delay:10000 count:0 others:[]
[Agent I] Shutting down because there are no active sessions or shared or joined workspaces.
```

**Comment by taiyosogawa** [comment]
@JtMotoX - Thanks for the details! I'm taking a look into it and will get back.

**Comment by taiyosogawa** [comment]
@JtMotoX, it looks like this _could_ be an authentication issue that isn't surfacing correctly. Could you try the following:

1. If it exists, delete the file `.vs-liveshare-keychain` in your home directory.
2. Go to your Windows Credential Manager (or Mac keychain), and delete any credentials that start with "Microsoft_VS_LiveShare".
3. Give unregister/register another shot.

In the meantime, I'll fix the silent failure issue that we have.

@mikeburgh, this might unblock you too, but I think the issue you're seeing is slightly different. If I understood correctly, you saw those console logs _and_ a toast notification saying that register failed, right?

**Comment by mikeburgh** [comment]
@taiyosogawa when I try to restore a local environment I get the toast about failure to authenticate and the following logs: 

```
[Command:RestoreLocalEnvironment I] Decorator starting: ErrorNotification
[Command:RestoreLocalEnvironment I] Decorator starting: Telemetry
[Command:RestoreLocalEnvironment E] Command [Unable to restore local environment]: Restore local environment Failure: Unable to authenticate (6476ms)
[Command:RestoreLocalEnvironment I] Decorator finishing: Telemetry. Duration: 25ms (0 + 25)
```
I tried the above steps, and then resetting up a local environment it walked me back through all the auth, but same issue.. I can register a local environment initially, but if i try to connect to it from a client I get a toast with : Resolving the authority 'vsonline' failed.

Any attempts to then restore the local environment on the host result in that same auth error.

**Comment by JtMotoX** [comment]
@taiyosogawa, I performed the following:

1) Made sure VSC was closed
2) Deleted the `.vs-liveshare-keychain` file from the home directory on both my Windows and Mac
3) Removed 5 entries from Windows Credential Manager which started with "Microsoft_VS_LiveShare" (I could not find anything like this in my Mac keychain)
4) Unregistered (got same logs)
5) Registered (got same logs)

One interesting thing is I was expecting it to require me to sign in again but it never asked.

It did re-create that liveshare file and also the 5 entries in credential manager.

**Comment by JtMotoX** [comment]
@taiyosogawa,
In some additional troubleshooting, I executed the "VS Online: Sign Out", then deleted the `.vs-liveshare-keychain` file, removed the entries in Credential Manager, then executed the "VS Online: Sign In" which opened my browser.  I signed in, and clicked "Continue" which switched back to VSC and displayed the output below.

Sign Out: `[Command:SignOut I] Command [Failed to sign out.]: sign out. Success (4ms)`

Sign In Toast:  `Failed to sign in.: Unable to authenticate`

Sign In Output:

```
[Command:SignInAndUpdateEnvList I] Command [Failed to sign in.]: sign in. Success (7004ms)
[Client I] User logged in as ***@outlook.com
```

**Comment by taiyosogawa** [comment]
This helps a lot in narrowing potential causes for our problem. Another thing that would be helpful to check is whether you can host/join a [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) session. 

Do either of you use Live Share? Probably the most straightforward way to check is to create a session, then choose the option to join it yourself. If you can successfully share/connect, it can help us narrow the search further.

**Comment by mikeburgh** [comment]
I had not previously used live share on this install (it was a clean VM just for VS Online and one project I need to host on a windows machine with IIS). 

I installed the live share extension, and was able to create a session and then join it using the 'join it yourself' option, as well as copying the link and joining from a different computer. 

Tried again after that to restore the local environment, and got the failed to auth error again.

**Comment by mikeburgh** [comment]
Not sure if this is related, but I rebooted and tried again to register a local environment and now I get: 

```
[Command:p I] Decorator starting: l
[Command:p I] Decorator starting: a
[Command:p E] Command [Failed to restore local environment]: Restore local environment Failure: vso login failed: Error:
  An assembly specified in the application dependencies manifest (vso.deps.json) was not found:
    package: 'Docker.DotNet', version: '3.125.2'
    path: 'lib/netstandard2.0/Docker.DotNet.dll'
 (1600ms)
[Command:p I] Decorator finishing: a. Duration: 555ms (0 + 555)
```

Removed and reinstalled the vsonline extension and now I just get the error above.

**Comment by taiyosogawa** [comment]
Sorry for the radio silence. I believe I've figured out the issue and am patching it now. The fix will require an update to the extension, so I'll let you know when it's published. Thanks again for your help and patience!

**Comment by taiyosogawa** [comment]
The updates should be available in the extension some time next week. I'll post specific instructions when it's available.

**Comment by JtMotoX** [comment]
Thanks for the updates @taiyosogawa 🙂

**Comment by sionicion** [comment]
I've been having this issue since the beta went public with self-hosted systems. It's very consistent, it works for a while once I restore the local environment. But when I come back to Visual Studio Online later, it shows this error. And I have to go and restore the local environment each time. Once I do that, it works for a while until later it has issues again.

I leave Visual Studio Code running all the time, and even after reopening the app, it doesn't work until I manually restore the local environment.

> Failed to connect to the remote extension host server (Error: Failed to connect to relay: wss://vsls-prod-ins-use-private-relay.servicebus.windows.net:443/$hc/c840002520357cdf2410da16147ad7016ef6--3c277ebb-3587-4547-83f2-c7befc0ae3c1?sb-hc-action=connect&sb-hc-token=SharedAccessSignature%20sr%3Dsb%253A%252F%252Fvsls-prod-ins-use-private-relay.servicebus.windows.net%252Fc840002520357cdf2410da16147ad7016ef6--3c277ebb-3587-4547-83f2-c7befc0ae3c1%26sig%3D4ecTP%252FCl%252BTQjEzlAZKSRtOEsfbgy%252BA4sDyjpOH%252BOIK8%253D%26se%3D1576612397%26skn%3DWorkspaceShareKey)

**Comment by taiyosogawa** [comment]
@sionicion, thanks for reaching out and sharing your experience. We're working on a few things to make the self-hosted feature more robust, and I want to make sure we properly capture the problem you're encountering:

1) Approximately how long does it take for connections to start failing? Are we talking minutes, hours, or days?
2) Is your machine ever shut down or logged off between connections? (Locked screen okay).
3) When the failed connection occurs, could you check to see if there is a `vsls-agent` process running from your temp directory?

**Comment by mikeburgh** [comment]
@taiyosogawa  just installed the latest version of the extension (as VSCode) and it's back and working!

**Comment by taiyosogawa** [comment]
@mikeburgh, fantastic! Thank you so much for your help and patience. You've helped make self-hosted environments better!

@JtMotoX, hopefully you get a chance to try it out and see if the update worked for you, too.

**Comment by JtMotoX** [comment]
@taiyosogawa, the registration process seemed like it was successful, however I no longer see the VSOnline option in the debug output dropdown so I don't know how to check the logs anymore so I can't provide you with any output that would determine if it was actually successful.  When I try to connect the the newly registered environment, I get the error "Failed to connect to the remote extension host server (Error: Time limit reached)".  Again, since the dropdown option in Output tab is gone, I can't provide you with any more details.

**Comment by taiyosogawa** [comment]
Ah, gotcha. I think what you're seeing now is #87. If so, it should work after a few minutes. Apologies for the string of issues - that one is being worked on.

**Comment by JtMotoX** [comment]
@taiyosogawa, after a few minutes I was able to connect without getting that timeout error which is indeed #87.  I am now able to access my self-hosted environments.  Thank you so much!

**Comment by taiyosogawa** [comment]
Great! Thank you so much for trying out a few different things and giving feedback. It has helped a ton!
