### ISSUE TITLE
Unable to connect to environment

### ISSUE THREAD

**Issue by arjun27** [MicrosoftDocs/vsonline#237]
I've been using this environment `fc5744aa-1546-485a-a8b7-77946469886f` on and off, and it's been working well so far - except for the last couple of mins, where I've been unable to connect to it. Tried a hard reload as well.

![Screen Shot 2019-12-02 at 2 44 11 PM](https://user-images.githubusercontent.com/284612/70001473-3fab3180-1512-11ea-8369-a2fc1ea244b2.png)

**Comment by arjun27** [comment]
Looks like the environment is now "unavailable", and I'm not sure if I can do something to recover from this state

![Screen Shot 2019-12-02 at 3 06 18 PM](https://user-images.githubusercontent.com/284612/70002593-51420880-1515-11ea-93b7-345e3a2d3f07.png)

**Comment by edgonmsft** [comment]
Hi Arjun! Let me take a look at your environment.

**Comment by edgonmsft** [comment]
Hi Arjun!, I'm checking the environment you reported to us, it looks like the environment restarted and we didn't recover correctly, could you suspend the environment and start it again and tell me if it comes back up correctly?

**Comment by arjun27** [comment]
suspending and then connecting worked it for me. thanks!
