### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#24]
**Repo**
1. After logging in
1. Visit https://online.visualstudio.com/nosuch

**Bug**
Blank white page. 

This should show a 404 message of some sort

**Comment by samanoha** [comment]
Thanks for reporting this issue, we will have a page not found option to handle all 404s.

**Comment by nikmd23** [comment]
And we've got a design! 🎉

![image](https://user-images.githubusercontent.com/199026/68439273-fd056c00-0194-11ea-8d66-5724485e9aa1.png)

This should be implemented soon.

**Comment by kumarz** [comment]
The fix should be available for public in the next prod deployment.
