### ISSUE TITLE
Support new VS Code / Remote - Containers v1.41 devcontainer.json properties

### ISSUE THREAD

**Issue by Chuxel** [MicrosoftDocs/vsonline#247]
As custom Dockerfile support lands, there are some new properties for devcontainer.json in the upcoming 1.41 VS Code / Remote - Containers release that are likely of interest to VS Online users as well.

Specifically:

| GH # | Property | Details |
|------|---------|--------|
| [vscode-remote-release#1201](https://github.com/microsoft/vscode-remote-release/issues/1201), [#46](https://github.com/microsoftdocs/vsonline/issues/46), [#95](https://github.com/microsoftdocs/vsonline/issues/95), [#100](https://github.com/microsoftdocs/vsonline/issues/100) | `containerEnv`, `remoteEnv` | Sets environment variables insider the container / environment. `remoteEnv` would apply whenever the server was restarted, while `containerEnv` is on the container rebuild (equivalent to `docker run -e`). <br /><br />The `containerEnv` property is most useful for scenarios where the image/Dockerfile itself starts a process up that requires an environment variable.<br /><br /> Both properties support `${localEnv:VARIABLE}` to access local env vars, `remoteEnv` also supports `${containerEnv:VARIABLE}` so that it can update existing container variables like `PATH`. However, for VSO, I would assume `${localEnv:VARIABLE}` would only apply for environments used from VS Code. |
|[vscode-remote-release#538](https://github.com/microsoft/vscode-remote-release/issues/538), [vscode-remote-release#1155](https://github.com/microsoft/vscode-remote-release/issues/1155) | `containerUser`, `remoteUser`, `updateRemoteUserUID` | `remoteUser` applies to server startup, while `containerUser` is for container create (equivalent to `docker run -u`). `updateRemoteUserUID` tells VS Code to update the UID/GID of the container user to match the local user on Linux - this likely is not directly applicable to VS Online.<br/><br /> Why:<br /> 1. Generally specifying an alternate user than the default in the image (e.g. in node). Very common.<br /> 2. Being able to start the container as root so startup commands can run, but connecting VS Code as a non-root user.<br />3. Dynamically setting the right UID/GID for Linux (root bind mount problem) - Currently non-issue for VSO. |

The property was also added, but may not apply to VS Online initially.

| GH # | Property | Details |
|------|---------|--------|
| [#1201](https://github.com/microsoft/vscode-remote-release/issues/1201) | `mounts` | Mounts are one of the most common reasons for "runArgs", are used for .NET SSL certs, performance workarounds, access to shared locations, and more. Near term is specific to Remote - Containers, but could change as Dockerfile support in VSO goes live. |

//cc: @lostintangent @nikmd23 @srivatsn

**Comment by nikmd23** [comment]
Thanks for the heads up @Chuxel!

**Comment by jkeech** [comment]
Closing this issue since we now support `containerEnv`, `remoteEnv`, `containerUser`, and `remoteUser`. The others are not applicable to VSO at this time.
