### ISSUE TITLE
Cryptic error message with invalid characters in env name

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#254]
If I put an invalid character (like an emoji) in the environment's name in VSO, instead of a validation error message appearing under the input box, I instead get a cryptic error message about invalid JSON.

![image](https://user-images.githubusercontent.com/199026/70567910-d5733c00-1b64-11ea-9f93-d99b166ca151.png)

**Comment by jkeech** [comment]
@wangjaso

**Comment by wy1024** [comment]
@nikmd23 Hi Nick, can you paste here the emoji you used? Or how you typed it.

I could not repro with my heart emoji 
![image](https://user-images.githubusercontent.com/4050204/70576243-47478780-1b5d-11ea-9d8f-b36cfcb2fa24.png)

**Comment by nikmd23** [comment]
Here's some that do the trick:

- [Baseball](https://online.visualstudio.com/environments/new?name=%E2%9A%BE%20Ballpark%20Tracker&repo=nikmd23/ballpark-tracker)
- [Heart](https://online.visualstudio.com/environments/new?name=%E2%9D%A4%20Ballpark%20Tracker&repo=nikmd23/ballpark-tracker)
- `Win+;` - Alternatively, on Windows you can press `Win+;` to get the soft emoji keyboard. It seems like any emoji I pick from that list gives this error.

FWIW, in Code desktop I get a validation error telling me these characters are not allowed.

**Comment by wy1024** [comment]
Still unable to repro your link :( Asked peter to try the link too and he sees the same behavior I do.
![image](https://user-images.githubusercontent.com/4050204/70647579-1c614000-1bfe-11ea-843c-4e4adf33f1b8.png)

Perhaps your browser is caching the old website? You can try 
F12 -> Application -> Clear storage -> Clear site data

**Comment by nikmd23** [comment]
FWIW, there was lots of users/machines that were running into this issue at NJSI, but I can no longer repro it.

I'm going to close this as fixed. Thanks!
