### ISSUE TITLE
Registering local environment fails with spaces in workspace directory

### ISSUE THREAD

**Issue by oliversalzburg** [MicrosoftDocs/vsonline#258]
When using the "Register local environment" command, the process fails:
```
[Command:l E] Command [Failed to register local environment]: Register local Environment Failure: vso share failed: Unrecognized command or argument 'Projects\hub-ui'
 (567721ms)
```

The error message seems to indicate an issue with spaces in the local workspace directory:
```shell
$ pwd
/c/Users/OliverSalzburg/FairManager Projects/hub-ui
```

**Comment by taiyosogawa** [comment]
Hi @oliversalzburg, thank for very much for reporting this issue. We are working on this and will have a fix in place for the next extension deployment. I'll update this issue when it is published.

**Comment by taiyosogawa** [comment]
Thanks again for alerting us to this issue - it should be resolved in extension version 1.0.1424. We'd love for you to give it another try!

**Comment by oliversalzburg** [comment]
@taiyosogawa That worked flawlessly. Thanks for the quick turnaround!

**Comment by AaronFriel** [comment]
@taiyosogawa It looks like there was a regression because I am seeing this exact error when configuring VS Online:

```
[2020-02-17 19:12:59.395 Command:u E] Command [Register Local Environment]: Register Local Environment Failure: vso login failed: 'C:\Users\Aaron' is not recognized as an internal or external command,
operable program or batch file.
```

My user directory has a space.

**Comment by taiyosogawa** [comment]
@AaronFriel, thanks for reporting this - we're looking into it!

**Comment by AaronFriel** [comment]
@taiyosogawa @smvanderweide should this issue be reopened?

**Comment by taiyosogawa** [comment]
@AaronFriel, The issue you're seeing looks very similar to this one, but it is slightly different, so I've created #316 for tracking.
