### ISSUE TITLE
Allow to copy forwarded port via command

### ISSUE THREAD

**Issue by Maxim-Filimonov** [MicrosoftDocs/vsonline#260]
Right now, I cannot find a command to copy URL for specific forwarded port without using mouse. 
I imagine workflow like this 
1. In the command panel "VS Online: copy forwarded port URL"
2. Select from forwarded ports.
3. Port URL automatically added to copy/paste buffer - similar to how "start collaboration session" command works.

**Comment by nikmd23** [comment]
Great idea @Maxim-Filimonov! We'll add this to the backlog and try to implement it ASAP!

**Comment by fara-nak** [comment]
@Maxim-Filimonov  the command already exist as "Copy Port Url", this is only active when you're connected to an environment. is this what you mean or you were thinking of something in addition to this command?

**Comment by nikmd23** [comment]
At the time, this command did not exist (or was missing from the built at that time). 

@Maxim-Filimonov, are you able to use this command now?

**Comment by Maxim-Filimonov** [comment]
Yes it's working, thank you!
