### ISSUE TITLE
Copy server URL not working on safari iOS 

### ISSUE THREAD

**Issue by Maxim-Filimonov** [MicrosoftDocs/vsonline#264]
Specific issue I have noticed on iPadOS 13.3. 
When clicked on copy port URL it doesn't get copied into copy/paste buffer on mobile safari. Somehow in the past i used to be able to double tap on it and get some window where I can copy the URL from, not being able to do it now makes it impossible to get port URL on ipad.

**Comment by nikmd23** [comment]
Thanks for taking the time to file this issue @Maxim-Filimonov! We really appreciate your feedback.

Unfortunately, VSO doesn't officially support Safari at this time. While many of the feature to happen to work, as you've found, there are also some that do not.

We have a specific issue in place for tracking Safari support (#33), so I'm going to close this issue in favor of that one.
