### ISSUE TITLE
Azure Data Studio in "browser mode" as Visual Studio Code

### ISSUE THREAD

**Issue by qubicaamf** [MicrosoftDocs/vsonline#267]
I would like to use Azure Data Studio in "browser mode" as Visual Studio Code, with no local installation and no port forwarding, should works mainly with local engine for development purpose like sql server docker image... but also with remote engine like Azure SQL.
I know, is already there a similar extension for VS Code (mssql) but it is not the same thing.

**Comment by jkeech** [comment]
@qubicaamf, I would recommend opening a feature request on the Azure Data Studio repo https://github.com/Microsoft/azuredatastudio, since it is a separate product from Visual Studio Online.
