### ISSUE TITLE
I register a local environment but can't see it online to connect in browser

### ISSUE THREAD

**Issue by dotnetdreamer** [MicrosoftDocs/vsonline#268]
here is the environment i created:
![Capture](https://user-images.githubusercontent.com/10280821/71611586-85135b00-2bb3-11ea-8d14-70011ddc31bb.PNG)
And i can't see it online!
![Capture](https://user-images.githubusercontent.com/10280821/71611598-98262b00-2bb3-11ea-9187-5b24f03ba0fc.PNG)

**Comment by jkeech** [comment]
@dotnetdreamer, can you double check two things:

1) You are signed in with the same account on both sides (VS Code and the browser). You can sign out of both and re-sign in to confirm. In VS Code, run the commands "VS Online: Sign Out" and "VS Online: Sign In". In the web portal, click on the profile in the top right corner and then "Sign out".
2) You have the same plan selected on both sides. In VS Code, it looks like the self-hosted environment is registered within the "VSO-PLAN-SOUTHEASTASIA-GENERAL-..." plan. Make sure that same plan is selected from the plan selector drop down in the top navigation bar. The plans view in the portal and in VS Code is always scoped to the currently-selected plan.

**Comment by dotnetdreamer** [comment]
Hello, 
I couldn't see the plans list but today i see it and my plan was only 1, so it was pre-selected which is nice. And as my plan is selected, i can now see my environment.
