### ISSUE TITLE
Incorrectly detected links in js file

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#28]
**repo**
1. Set up a new environment for vsls-contrib/guestbook
1. Create a new js file with the content:

```js
// ssad
```

**Bug**
Notice `ssad` this being detected as a link:

![Screen Shot 2019-11-01 at 5 06 30 PM](https://user-images.githubusercontent.com/12821956/68062836-f9bc3d00-fcc9-11e9-85ca-7ccdfc5c1cde.png)

Clicking the link does nothing.

This bug seems go away when I disable gitlens but I don't know how gitlens is connected

**Comment by eamodio** [comment]
I think this might be related to: https://github.com/microsoft/vscode/issues/83410

**Comment by mjbvz** [comment]
Yes doesn't seem like it should be VSO specific. Closing in favor ohttps://github.com/microsoft/vscode/issues/83410
