### ISSUE TITLE
Register local environment failed timeout

### ISSUE THREAD

**Issue by Fireant456** [MicrosoftDocs/vsonline#284]
Just trying to register my local self-hosted environment and I keep getting the following error in my VS Online logs...

`[2020-01-20 05:43:23.660 Command:u I] Decorator starting: l
[2020-01-20 05:43:23.660 Command:u I] Decorator starting: a
[2020-01-20 05:44:34.655 Command:u E] Command [Register Local Environment]: Register Local Environment Failure: vso share timeout exceeded (30000 ms) (70995ms)`

**Comment by Fireant456** [comment]
VS Online Version: 1.0.1507
VS Code Version: 1.41.1
Windows 10 Pro 1903.18362.592

Path to workspace: `S:\GLG\GLG-Workspace-secondary.code-workspace`

**Comment by taiyosogawa** [comment]
Thanks for the details - the error message helps narrow things down. I'm wondering if you see a credential in your credential manager (Windows credentials) that starts with Microsoft_VS_LiveShare? I'll see if I can repro the issue.

**Comment by Fireant456** [comment]
Yes @taiyosogawa I have the following entries in my credential manager... 
![image](https://user-images.githubusercontent.com/1479965/72761525-e9697f00-3ba1-11ea-9315-77b24ffd76c8.png)
I also have...
![image](https://user-images.githubusercontent.com/1479965/72761584-0dc55b80-3ba2-11ea-9ae0-51fdcc0ba2c6.png)

**Comment by taiyosogawa** [comment]
Sorry for the late reply. There might be a caching issue going on here that is preventing the registration connection from being established. Could you try deleting the 8 "Microsoft_VS_LiveShare" credentials, signing out, then trying again? You should see them repopulate when you do.

**Comment by Fireant456** [comment]
Okay @taiyosogawa it seems that did the trick!

As instructed I removed the 8 MS_VS_LiveShare entries in the cred manager, opened back up VS Code and without being instructed to reenter credentials everything worked and the environment registered without and issues. Thank you for your help sir!

**Comment by taiyosogawa** [comment]
That's awesome, and thank _you_ for reporting this issue. Your responsiveness really helped us identify and understand a problem that we can now fix! 🔧
