### ISSUE TITLE
VS Online environment not loading in Dev Container

### ISSUE THREAD

**Issue by s-leonard** [MicrosoftDocs/vsonline#287]
I have a basic repo here: https://github.com/s-leonard/VSCodeOnline which has the dockerfile and extensions configured at `VSCodeOnline/.devcontainer/devcontainer.json`

If I download this repo and open in VS Code on my desktop, I'm prompted to re-open in dev container, and after that I can open a terminal window at `~/workspace/env/dev$ ` and run the command `terraform init`

This works because the docker file describes a container that has Terraform installed. 

However, if I create an environment at https://online.visualstudio.com/environments which points to my same repo and open the terminal in the same location and run the same command it returns `bash: terraform: command not found`

I know its picking some of it up, because I can see my extensions, but I don't think its running in my container?

**Comment by nikmd23** [comment]
Hi @s-leonard. You are correct. 😕 At the moment, VS Online's web management experience is not picking up the `devcontainer`'s Docker file. (It does support many other `devcontainer` properties, as you've noticed.)

This support should land in the next few weeks.

In the meantime, there is a workaround. If you use [the VS Online extension for VS Code](https://marketplace.visualstudio.com/items?itemName=MS-vsonline.vsonline) to create your environment, we will respect the Docker file setting. From there you can connect to the environment in the browser - and it will have terraform and your other customizations in it

**Comment by s-leonard** [comment]
Thanks @nikmd23 for the update. At least now I know I'm not going crazy. 

My use case is for teaching people code without giving them a bunch of prereqs, like installing docker. So I'm happy to wait for the feature to land 😃. 

Do you know if there is somewhere we can track the features and their progress?

**Comment by nikmd23** [comment]
This repo and its set of issues is the best way to track. Issue #2 also shows a good high level overview.

FWIW, the workaround I'm suggesting does not require Docker, but it does require VS Code to be installed. I totally understand why you'd want to wait for the full browser support, but wanted to be sure  you knew of all your options to help you succeeded ASAP.

**Comment by jkeech** [comment]
The web portal now supports `devcontainer.json` for customizing the docker image used for the environment's runtime. Please give it a shot and file a new issue if you have any problems. Closing this issue.

**Comment by s-leonard** [comment]
Just tested it and works great. Thanks

**Comment by sharif1093** [comment]
Do self-hosted environments also support `devcontainer.json`'s Dockerfile? I tried it on a self-hosted environment but seemingly it had no effects on it.
Particularly I wonder about setting my environment using Docker when using self-hosted ...
