### ISSUE TITLE
Unable to git push on self hosted vs online project

### ISSUE THREAD

**Issue by jaydeboer** [MicrosoftDocs/vsonline#290]
Issue Type: <b>Bug</b>

## Description

I am using a mac to host the environment using the VS code vsonline extension.

When running on a remote, everything seems to be working up to the point where I want to push changes to my remote git repository (hosted in my personal Azure DevOps account).  I've tried to use the VS Code interface to push, as well as the terminal, both give the following error:
```
> git show :HomeschoolBlazor.SharedKernel/Interfaces/IHandle.cs
> git check-ignore -v -z --stdin
> git show :HomeschoolBlazor.SharedKernel/IgnoreMemberAttribute.cs
> git check-ignore -v -z --stdin
> git add -A -- .
> git commit --quiet --allow-empty-message --file -
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git config --get commit.template
> git pull --tags origin master
No user exists for uid 502
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
> git pull --tags origin master
No user exists for uid 502
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I've tried this two times.   Each time, I can log into the host and do the push from there.

## Remote Details

- macOS Catalina 10.15.2
- VS Code Version: 1.41.1

## Host Details

- macOS Catalina 10.15.2
- VS Code Version: 1.41.1
- Current version of VS Online extension

Extension version: 1.0.1507
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0
Remote OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (15.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|VS Online: DeBoers-Mac-Pro.local|
|OS|Darwin x64 19.2.0|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|Memory (System)|32.00GB (7.25GB free)|
|VM|0%|
</details>

**Comment by jkeech** [comment]
Are you using iTerm2? I’ve never seen this error before, but lots of others have reported similar issues with iTerm online, and the solution to all of them seems to be to restart the terminal. In your case, you might need to kill the VSO/VSLS agent process on the remote side and re-register the self-hosted environment from a clean terminal if the permissions are messed up on the current agent process that is running.

Reference: https://stackoverflow.com/questions/53013667/no-user-exists-for-uid-502

**Comment by jaydeboer** [comment]
@jkeech, I don't have iTerm2 installed on either machine.  I am away from the remote machine, but when I return, I will try restarting things and see if that resolves the issues.  

I did think of a couple of other details, but I don't know if they matter.  
- I am running bash shells, not zsh, the new default from Apple.
- I am also using ssh for my connection to git.  

Thanks for the ideas to try.

**Comment by jaydeboer** [comment]
It is working now.  This is what I did to the host.
- I stopped vslsagent
- Rebooted the host
- Clicked the ```Restore Local Environment``` menu option in VS Code

It works like a charm now.  I am not sure what put it into that state, but I will pay closer attention if that happens again.
