### ISSUE TITLE
VS code setting "enableSuspendOnIdleConnection" doesn't seem to work (can't disable)

### ISSUE THREAD

**Issue by olivermt** [MicrosoftDocs/vsonline#293]
Every 30 minutes I get the "cannot load environment" dialogue box with reload window or cancel as the choice.

This has been happening pretty consequently since the update that moved the "you are inactive, do you want to suspend" dialogue down into the lower right toast notification area.

The environment doesn't actually suspend, but I need to reload window to be able to reconnect.

More of a nuisance than a real problem, other than having to re-start all services because it kills my terminals.

Let me know what kind of information I can provide to help debug this.

**Comment by olivermt** [comment]
Scratch that, the environment actually spins down and needs to spin back up again.
There are no other active editors spinning it down for me (I know its an ongoing issue that clientside timeouts will disconnect other editors).

**Comment by jkeech** [comment]
@olivermt, can you provide some more details about which client are you using? VS Code desktop or the web client? VS Code version and VS Online extension version info would also be useful.

I'd like to understand what is going wrong with the client-side idle detection on your machine, but if you want to turn that feature off altogether, you can set the VS Code setting `"vsonline.enableSuspendOnIdleConnection": false`.

**Comment by olivermt** [comment]
Hi!

I am using VS Code desktop, newest stable.
```
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```
Not sure where I check what current release is, but the one BELOW current release (previous would be logical?) is 1.0.1424.

Account is a private microsoft account running a MSDN subscription, although I don't think that should affect it.

Setting suspend setting to false across all three setting domains did nothing and environment still suspended.

I will attempt to create a new environment from the same repo to see if there might be some nuances in using a environment created towards a previous version?
I'll keep this environment alive if you figure out some regression checks you want me to run.

**Comment by olivermt** [comment]
Also if it is relevant, this computer is intuned to my microsoft account, but I am not using that at all for this stuff. Not sure if there is some collision between "work and school account" stuff and whatever I do here. I am not logged into Microsoft account at all in Chrome, which is my default browser and where I did all my authorization towards both VSOnline plugin and the Azure plugin (to get subscriptions up and running).

**Comment by olivermt** [comment]
Update, the environment now behaves as it should. Doing actions delays shutdown etc. The suspend false still does nothing however.

**Comment by jkeech** [comment]
@olivermt, apologies for the delay here. We are looking into why the false setting does not seem to work.

**Comment by jkeech** [comment]
@dmgardiner25 merged a fix that allows the `enableSuspendOnIdleConnection` setting changes to be picked up while VS Code is running. Previously, it only picked up the changes on reload, so if you changed the setting value while VS Code was running, it wouldn't apply until the next restart/reload. That fix should be deployed this week.

**Comment by jkeech** [comment]
The fix for this has been uploaded to the marketplace. 🚀
