### ISSUE TITLE
Paste is missing in the editor. Is this a bug?

### ISSUE THREAD

**Issue by tikaro** [MicrosoftDocs/vsonline#299]
Hello, VS Online!

For me, the "Paste" command is missing altogether in the editor window.

Here's an example. I've taken this screenshot while working with a file that is open and _not_ read-only.  

You can see that the "paste" context option is just missing altogether:

![image](https://user-images.githubusercontent.com/30852/73794620-dc8a8500-4776-11ea-8f83-d52718cd6bf8.png)

I'm able to copy and paste in the _terminal_ pane without any trouble. Here, you can see the context menu inside the terminal pane, with both "copy" and "paste" available:

![image](https://user-images.githubusercontent.com/30852/73794692-fa57ea00-4776-11ea-9091-59eef3c0f0ed.png)

I'm using Visual Studio Online in the browser window, in Chrome, and on a Chromebook.  

I've done a bunch of searching and found some mention of "paste" going missing on Mac OS... but I can't find anything relevant to Chrome OS.

Is this a bug, or is there something that I'm just overlooking?

Thanks very much for any help or guidance you can provide!

**Comment by jkeech** [comment]
I can reproduce this on the new Edge browser on Windows as well. The keyboard shortcut for paste works fine, but there is no context menu for paste. I think this is likely a VS Code Web issue. I'm going to open an issue on the VS Code repo for this.

**Comment by jkeech** [comment]
Actually, it looks like there is already an open issue for this: https://github.com/microsoft/vscode/issues/82604

**Comment by tikaro** [comment]
Aha! @jkeech, thanks very much -- I think that the resolution here is that this is _not_ a bug, it is a feature that hasn't been implemented yet, so I'm going to close this issue in favor of https://github.com/microsoft/vscode/issues/82604
