### ISSUE TITLE
Can't compile native modules

### ISSUE THREAD

**Issue by dbaeumer** [MicrosoftDocs/vsonline#30]
Steps to reproduce:

- create an environment
- clone https://github.com/Microsoft/lsif-node
- run npm install

Observe: the native compile fails inside node-gyp

**Comment by Chuxel** [comment]
@dbaeumer  Could this be related to https://github.com/microsoft/Oryx/issues/404 (this is the image used by default)?

**Comment by dbaeumer** [comment]
Yes, looks similar.

**Comment by jkeech** [comment]
This is now fixed in the base image. Any new environment that you create will have the updated base image.

**Comment by dbaeumer** [comment]
Thanks!
