### ISSUE TITLE
Plans to release online IDE code

### ISSUE THREAD

**Issue by jgbradley1** [MicrosoftDocs/vsonline#300]
Thanks for a great product. Are there any plans to release the code for the [browser-based editor](https://docs.microsoft.com/en-us/visualstudio/online/quickstarts/browser) portion of VSCode Online? I'm familiar with [monaco](https://github.com/microsoft/monaco-editor) but based on the private preview, there appears to be additional functionality built on top of monaco.

I'm specifically thinking about on-prem use cases where a user would want to build VSCode Online into a docker image and then access the docker container environment via the browser IDE.

**Comment by nikmd23** [comment]
Hi @jgbradley1!

We don't currently have plans to release the code for browser based editor which is based on the VS Code source (which itself uses Monaco as the editor component).

For your scenario, I'm wondering if the CLI based self-hosted environment registration path (#69) would do the trick? We're working on that right now and it should be available shortly.
