### ISSUE TITLE
@recommened in Extensions window doesn't show the workspace recommendations

### ISSUE THREAD

**Issue by praksb** [MicrosoftDocs/vsonline#303]
Searching for @recommended extensions shows up empty and doesn't list the workspace recommendations from my extnesions.json when I open my workspace in VS Online.

See screenshot below:
<img width="1418" alt="Screen Shot 2020-02-13 at 1 11 06 PM" src="https://user-images.githubusercontent.com/10749920/74479116-7df29480-4e63-11ea-90c7-5666936630eb.png">

Expected: List of extensions from "extensions.json"
Actual: Empty

It does work when I connect to this environment remotely from VS Code client. Seems to be an issue specific to vs online.

**Comment by srivatsn** [comment]
I think this was just recently fixed in VSCode. Can you try using the insiders channel to see if that works for you. You can enable from online.visualstudio.com from the settings menu:

![image](https://user-images.githubusercontent.com/20570/74480214-5dc3d500-4e65-11ea-9604-ce69158428e4.png)

**Comment by praksb** [comment]
Tried insiders and it didn't work for me.

<img width="1131" alt="Screen Shot 2020-02-13 at 2 32 21 PM" src="https://user-images.githubusercontent.com/10749920/74484692-e9416400-4e6d-11ea-9969-115d9ecb4874.png">

**Comment by srivatsn** [comment]
@bpasero should this have been fixed with your recent change?

**Comment by bpasero** [comment]
@srivatsn fix went in Feb 11: https://github.com/microsoft/vscode/commit/8a997f7321ae6612fc0e6eb3eac4f358a6233bfb

**Comment by nikmd23** [comment]
FYI @bradygaster. This might address the issue you raised to me the other day.

**Comment by srivatsn** [comment]
The update vscode hasn't been deployed yet and should happen later this week.

**Comment by srivatsn** [comment]
The updated vscode should now be in prod- @praksb can you verify if this is fixed for you with insiders? Thanks

**Comment by praksb** [comment]
@srivatsn works for me now in the insiders version.
