### ISSUE TITLE
Cannot push to a repository after cloning it

### ISSUE THREAD

**Issue by connor4312** [MicrosoftDocs/vsonline#307]
After cloning a repo, I would expect VSO to be able to cache the token it uses to clone the repo to let me push to it again later. However, when trying to push changes back up, I get a standard "Authentication failed" message. For my projects I've put a personal access token in the remote's uri, which is somewhat annoying to do and probably less secure than a credential manager.

**Comment by lostintangent** [comment]
@connor4312 You should be able to push your repo, so this issue is unexpected. Just to confirm: were you using the VS Code desktop extension and/or the web? And also, was the repo you cloned public or private?

**Comment by edgonmsft** [comment]
@connor4312 Just to add. We don't cache credentials at this moment. Every time you do an operation we proxy them from your machine. So if that process fails then its possible to get this subsequent failures, for example, by connecting from a different place where you are not logged in.

**Comment by connor4312** [comment]
It's been a while since I've seen this (on the repos I work with I've added PATs as mentioned). Opening a new repo seems like everything works. I'll reopen this with more details if I run into it again.
