### ISSUE TITLE
devcontainer.json seems to be ignored

### ISSUE THREAD

**Issue by connor4312** [MicrosoftDocs/vsonline#308]
On [the docs](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring) it says we should be able to configure the environment by adding a devcontainer.json. I've added one to [my repo](https://github.com/connor4312/mopidy-azure.git), but it appears to have no effect. I've deleted and recreated the VS Online environment, but it doesn't seem to have an effect; I should be getting Debian buster with Python 3.8, but I get the same Debian stretch with 3.5 as if I had no container configuration.

**Comment by jkeech** [comment]
@connor4312, the documentation is not accurate right now. Custom devcontainer.json is supported for environments created from VS Code, but not from the web portal. The web portal will support devcontainer.json in about a week though.

Could you confirm that it's working correctly if you create the environment from VS Code via the VSO extension?

**Comment by connor4312** [comment]
Okay, thanks. I'll create an environment from vscode this evening and let you know.

**Comment by connor4312** [comment]
Seems to work in VS Code.

**Comment by Uili-Simteau** [comment]
Hi, is this the same as [Allow devcontainer.json to specify a docker compose file #35](https://github.com/MicrosoftDocs/vsonline/issues/35) ?  Cheers,
Uili

**Comment by jkeech** [comment]
@connor4312, the web portal now supports devcontainer.json as well. Closing this issue.

@Uili-Simteau, docker compose support is a separate feature, so I'll leave that issue open for tracking.
