### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by ianjanicki** [MicrosoftDocs/vsonline#309]
Machine: MacBook Pro (Retina, 13-inch, Late 2012)
Browser: Chrome, Version 79.0.3945.130 (Official Build) (64-bit)

Just spun up a new instance and was trying a `create-react-app` and used the typical script I employ for hot reloading:

**index.js**
```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';

const rootEl = document.getElementById('root');

ReactDOM.render(<App />, rootEl);

// Hot reloading
if (module.hot) {
  module.hot.accept('./App', () => {
    const NextApp = require('./App').default;
    ReactDOM.render(<NextApp />, rootEl);
  });
}
```

However, when I make changes (and it looks like VSO auto-saves), I must reload the forwarded port (which takes considerable time), in stead of updating on its own. Is there some other configuration to have forwarded ports react to this type of hot-reload?

---
**Edit:** It looks like the forwarded port did update, but it took several minutes. Is there some sort of regular refresh interval?

**Comment by jkeech** [comment]
Is the hot-reload implemented via websockets? If so, it's a limitation of the port-forwarding implementation in VSO web. If you use the VSO extension in the VS Code desktop application, however, web sockets should work. There is an issue tracking getting websockets and other protocols working in the web-based port-forwarding service: https://github.com/MicrosoftDocs/vsonline/issues/19

**Comment by ianjanicki** [comment]
[Yes](https://github.com/webpack-contrib/webpack-hot-client). Can confirm hot-reload works if using VSO in desktop app. Thanks for clear explanation. Closing.
