### ISSUE TITLE
Document self-host CLI 

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#310]
This is a placeholder issue to begin to capture details about the self-hosting CLI experience. Once ready, we can open a PR capturing the details outlined in this issue in a proper `.md` file.

**Comment by gregvanl** [comment]
@nikmd23 Has this been covered with https://docs.microsoft.com/en-us/visualstudio/online/how-to/self-hosting-cli?

**Comment by gregvanl** [comment]
Closing as I think this is done. Please reopen if more work is required.
