### ISSUE TITLE
Allow devcontainer.json to specify `--network host` in the `runargs`

### ISSUE THREAD

**Issue by stuartleeks** [MicrosoftDocs/vsonline#314]
A bunch of scenarios I've been using devcontainers for have involved running [kind](https://github.com/kubernetes-sigs/kind) for integration testing of components to run in Kubernetes. This has been a super-useful pattern and I'd love to be able to bring these scenarios to VSOnline :-)

Example `devcontainer.json` specifying the network in `runargs`:
https://github.com/microsoft/azure-databricks-operator/blob/master/.devcontainer/devcontainer.json#L21

With the above repo, the following commands should run successfully if the host networking is enabled:

```bash
make create-kindcluster
kubectl get nodes
```

**Comment by stuartleeks** [comment]
cc @edgonmsft (this is the scenario we discussed yesterday :smile: )

**Comment by lostintangent** [comment]
@chuxel Is this something that devcontainer.json should support “natively”, as opposed to relying on a runArgs setting?

**Comment by stuartleeks** [comment]
I did look to see if it had been added when I was setting up a devcontainer this week 😀

**Comment by jkeech** [comment]
Support for host networking in `runArgs` was checked in this week and should be rolling out next week. We will also soon be added host networking enabled by default on the default image.

**Comment by lostintangent** [comment]
@jkeech Awesome! 🙌

**Comment by lostintangent** [comment]
This support has been shipped! Next week, we’ll address #357, which will run containers in the host network by default 👍 Thanks for all the feedback!
