### ISSUE TITLE
Console.logging in published extension

### ISSUE THREAD

**Issue by connor4312** [MicrosoftDocs/vsonline#318]
I have the VS Online extension installed locally, and spend the better part of my day working on the js-debug extension for VS Code. When I debug the extension I'm working on, I always get a bunch of logs from the VS Online extension that I don't care about. It would be nice if these were disabled (or logged to a file) for the published extension; I don't get logs from any other extensions.

![image](https://user-images.githubusercontent.com/2230985/75380065-3fa99c00-588b-11ea-8b56-76707e6f375a.png)

**Comment by osortega** [comment]
Hi @connor4312 !
Thanks for reporting this, the fix should be already published now. Sorry for the inconvenient
