### ISSUE TITLE
Failed to register local environment: Sharing environment failed. [timeout exceeded]

### ISSUE THREAD

**Issue by fpintos** [MicrosoftDocs/vsonline#319]
I'm unable to register a self-host environment in VSOnline.
Exporting the logs I get the following messages:

[2020-02-28 01:57:52.743 Command:u I] Decorator starting: l
[2020-02-28 01:57:52.743 Command:u I] Decorator starting: a
[2020-02-28 01:58:51.413 Command:u E] Command [Register Local Environment]: Register Local Environment Failure: vso share timeout exceeded (30000 ms) (58669ms)
[2020-02-28 01:58:51.413 Command:u I] Decorator finishing: a. Duration: 1ms (0 + 1)
[2020-02-28 01:58:51.429 Command:u I] Decorator finishing: l. Duration: 282461ms (0 + 282461)
[2020-02-28 02:00:35.963 Command:p I] Decorator starting: l
[2020-02-28 02:00:35.963 Command:p I] Decorator starting: a

The first time I tried this I got the firewall dialog and enabled the port for both the domain and private networks.

The environments do show up in https://online.visualstudio.com/environments, but all in a 'creating' stage.

I've tried with different local folders, all without success.

VSCode Version:
Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19569

VSOnline Extension:
1.0.1672

%TEMP%\vso shows VSOAgent_win_3495655

From #284 , I do see credentials that start with "Microsoft_VS_LiveShare". I removed them all, closed all instances of VSCode, deleted all pending environments in the web page.

No success.

**Comment by Helianthella** [comment]
same issue here, have tried the steps in #284 to no avail
the logs only say `vso share timeout exceeded`

**Comment by OneCyrus** [comment]
same error here. doesn't work an all my systems.

**Comment by nervoy** [comment]
I am experiencing the same issue. vso share timeout exceeded

**Comment by taiyosogawa** [comment]
Thanks for reporting this issue. This looks like a known issue with Self-Hosted environments on Windows right now, but we are rolling out a fix. Please let me know if you're trying to host a non-Windows environment.

I'll post an update when the fix has been rolled out. Thanks for your patience!

**Comment by fpintos** [comment]
Thanks @taiyosogawa , the other environment I've tried was from WSL, but it sounds like that is not yet supported. Would the fix add support for it, or do we have an estimate of what that might come? Just wondering...

**Comment by cjackson234** [comment]
Any update on this?

**Comment by lisyoen** [comment]
This issue seems to be related to the azure account.
I have tried on several different Windows PCs with my account but they are all giving the same error.
Until a few days ago everything worked fine.

**Comment by cjackson234** [comment]
> This issue seems to be related to the azure account.
> I have tried on several different Windows PCs with my account but they are all giving the same error.
> Until a few days ago everything worked fine.

I tried signing up for a new account. This didn't help.

**Comment by taiyosogawa** [comment]
@fpintos, yes, unfortunately WSL is not supported at the moment and I can't say for sure when that will be available.

@lisyoen, I'm sorry it's not working on any of the PCs you've tried. Could you help me understand why you think it might be an Azure account issue? 

@cjackson234, thanks again for your patience for an update:

The fix has been partially rolled out. If you try registering your environment, you should see this folder under "%TEMP%\vso": VSOAgent_win_3495655

If you see this version (or later) and you're still encountering the same error message posted by @fpintos, please let me know. If you're still seeing an older version, the new one should be available in the next day or two.

**Comment by fpintos** [comment]
Hi @taiyosogawa ,

I've tried again just now and the environment still fails to register.
Do I need to update anything in VSCode or the rollout is on the service itself?
It could be that it just hasn't reached the servers handing my requests.
I'll try again later.

Meanwhile, I see these in the temp\vso folder:

2020-03-02  11:48 AM    <DIR>          .
2020-03-04  10:44 AM    <DIR>          ..
2020-02-27  05:51 PM    <DIR>          VSOAgent_win_3495655
2020-02-27  05:51 PM        34,170,756 VSOAgent_win_3495655.zip
2020-03-02  11:48 AM    <DIR>          VSOAgent_win_3512918
2020-03-02  11:48 AM        34,228,613 VSOAgent_win_3512918.zip

Still the same error in the logs:
[2020-03-04 18:46:52.422 Command:u E] Command [Register Local Environment]: Register Local Environment Failure: vso share timeout exceeded (30000 ms) (81605ms)

**Comment by taiyosogawa** [comment]
Hey @fpintos,

Good question - you shouldn't have to update vscode - the update was server-side only and it looks like you did get the latest version.

To help you troubleshoot, could you use [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to watch for a process called "vsls-agent" while you try registering?

1) Do you see the process start? Does it die right away or does it stay up for the full 30 seconds (or longer)?
2) Does it run out of the %TEMP%\vso\VSOAgent_win_3495655 directory?
3) Take note of the full command line (including arguments). After it times out, could you try running that same command from a terminal? What happens?

**Comment by cjackson234** [comment]
So far it's just saying "Registering Environment: [name here]" and that's been running for 10 minutes. Is there a new version of VS code or is the update purely server side?

**Comment by cjackson234** [comment]
![image](https://user-images.githubusercontent.com/2728668/75920232-f1693f80-5e2c-11ea-93ce-28f6d3580399.png)

This is what the process explorer looks like for me. Its running out of \temp\2

**Comment by fpintos** [comment]
This is my case:
![image](https://user-images.githubusercontent.com/4239171/75925802-3b96f480-5e1e-11ea-9f2d-70b7ae67962a.png)

It looks like it is running from the 3512918 directory.

**Comment by fpintos** [comment]
SOLVED.

I decided to kill my %temp%\vso directory after closing all instances of VSCode.
Windows told me files were in use.
Inspecting the running processes I saw (invisible) instances of vscode started with "-n" holding references to stuff in the folder, and vsls binaries loaded in them.

So I rebooted the machine to make sure I was starting on a clean slate, then I deleted the folder and tried again.

Registration then completed successfully and I was able to connect from another machine.

**Comment by taiyosogawa** [comment]
@fpintos - that's great. Glad to hear!

@cjackson, it looks like yours is stalling while trying to authenticate. This might be an issue with cached credentials. Could you try these?:

1) Going to the Credential manager (Windows Credentials) and deleting all the credentials that begin with "Microsoft_VS_Liveshare"
2) deleting the "%HOME%\.vs-liveshare-keychain" file if there is one

**Comment by cjackson234** [comment]
IT WORKS!

- Deleted the files. (needed to kill the live share agent process)
- Deleted the credentials.
- Deleted and failed environments on the account
- Restarted
- Registered new environment
