### ISSUE TITLE
I cannot register my local (self-hosted) environment in WSL.

### ISSUE THREAD

**Issue by khuongduybui** [MicrosoftDocs/vsonline#32]
I'm using VSCode on Windows but my workspace is in my WSL (WSL2 to be precise) using Remote WSL extension.

When I install VS Online extension pack, it installs Azure Account extension on my WSL remote.

I can run the Azure: sign in and Azure: select subscriptions commands, but when I try to run register local environment it errors out with "must install Azure Account extension".

**Comment by benc-uk** [comment]
Same error in WSL / WSL2

**Comment by taiyosogawa** [comment]
@khuongduybui, @benc-uk, thanks for the feedback and sorry to hear about the non-ideal registration experience. 

We don't yet support for registering self-hosted environments while connected to a [remote development environment](https://code.visualstudio.com/docs/remote/remote-overview) (WSL, WSL2, containers, etc.), but we ought to at least surface better messaging.

I completely understand why you would want to host your WSL workspace as a self-hosted environment. We'll use this feedback for prioritizing feature work.

**Comment by khuongduybui** [comment]
When I tried to run vscode directly on Ubuntu inside WSL2 (not VSCode on Windows with Remote WSL), I can install both VSOnline and Azure account extension.

However, when I run command Azure: Sign In, it opens Chrome (on Linux) and signs me in correctly
But when I run command VSOnline: Sign In, it opens Chrome (on Linux) but fails to sign me in.
At the end of the sign in process, Chrome asks if I want to open xdg-open, and when I clicked yes it just opened a new browser. I guess it's trying to call a `vscode:` URI behind the scene and failed.

Can we add a "Sign in with device code" to the VSOnline extension the way Azure Account extension does? Or if Christmas is early, can we have VSOnline extension use the account signed in with Azure Account extension and not ask me to sign in again?

**Comment by srivatsn** [comment]
>Can we add a "Sign in with device code" to the VSOnline extension the way Azure Account extension does? Or if Christmas is early, can we have VSOnline extension use the account signed in with Azure Account extension and not ask me to sign in again?

We hope to get to a single sign in instead of the two that we have today. That involves a bit of work but it's something we're actively exploring.

**Comment by taiyosogawa** [comment]
It looks like we have a couple of separate threads here. To consolidate, let's continue the conversation on:

Self-hosted environments: #116 
WSL sign in: #99
