### ISSUE TITLE
Can't go past 2-factor authentication screen

### ISSUE THREAD

**Issue by kytwb** [MicrosoftDocs/vsonline#321]
I opened the console to check because I had no visual feedback on what was happening when clicking the **Complete 2-factor authentication** button:

![ER3xJ8lWkAIrnrS](https://user-images.githubusercontent.com/412895/75573347-eee99d00-5a5c-11ea-8e20-07c111fa7852.jpeg)

**Comment by lostintangent** [comment]
@kytwb Thanks for reporting this! Just to confirm: are you running Chrome on Windows?

@legomushroom Any thoughts on what this issue could be?

**Comment by kytwb** [comment]
@lostintangent I am running Chrome on macOS.

**Comment by legomushroom** [comment]
@kytwb we saw these issues when browser blocks 3rd party cookies. Can you try to enable them for VSO website? What account do you use to sign in, is it an outlook one?

**Comment by kytwb** [comment]
@legomushroom You are right! I was actually on Brave, not Chrome, honest mistake. Enabling the blocked scripts did work.

**Comment by legomushroom** [comment]
Great to hear you are unblocked! We have a chance for our authentication that will fix the issue, meanwhile, we have to rely on 3rd party cookies. Thanks for reporting!
