### ISSUE TITLE
devcontainer extensions not consistently installed when using Dockerfiles

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/vsonline#334]
When using a Dockerfile to specify a devcontainer, extensions listed in `devcontainer.json` are not consistently installed into the new environment. I ran into this using the example at https://github.com/cgranade/quantum-research-template/tree/master (NB: takes a while to build due to installing TeX Live 2019) and with the example at https://github.com/microsoft/quantum.

**Comment by jkeech** [comment]
@cgranade, extensions are installed asynchronously. We don't block connection prior to all of the setup steps completing. So if you connect before the install finishes, it won't show up. VS Code in the web currently currently support detecting extension installs after it is running, so you have to reload to see the extensions. Can you confirm that they show up if you reload a few seconds after the environment is fully set up?

**Comment by cgranade** [comment]
@jkeech: Ah, that makes a lot of sense, thanks for the explanation! It took more than a few seconds, but they did definitely show up on a reload. Thank you for the help! 💕

**Comment by jkeech** [comment]
@cgranade, in the future, we might be able to reorder the initialization a bit to make this less likely to happen as well as get VS Code to be able to detect extension installs and hot reload in the web. I know this is currently a pain point that a lot of people hit, and the experience today is not ideal, so we aren't satisfied with the current behavior.

**Comment by abuchholtzau** [comment]
@bradygaster I think this is the issue you hit as well?

**Comment by jonnyhork** [comment]
I noticed this issue at well, though I didn't wait long enough or reboot my environment to see that they were actually installed just not visible.

**Comment by nikmd23** [comment]
I'm seeing reports of this issue on Twitter too. I'd like to prioritize getting this fixed ASAP.

In the meantime, @jkeech's [comment has the work around](https://github.com/MicrosoftDocs/vsonline/issues/334#issuecomment-595507805):

> So if you connect before the install finishes, [extensions] won't show up. VS Code in the web currently currently support detecting extension installs after it is running, **so you have to reload to see the extensions**.

**Comment by bradygaster** [comment]
@abuchholtzau yes, same issue. that said, the issue I ran into was **specific to extensions I expected to be there not being there until I performed a hard-refresh**, not as much about the Docker container components, which I think was the OG purpose for this thread. 

FWIW, **now** when I hard-refresh the environments page when my extensions aren't "just there," they're there. If you want sample repositories to party on and test with, I haz some.

**Comment by bradygaster** [comment]
> I'm seeing reports of this issue on Twitter too. _I'd like to prioritize getting this fixed ASAP._
> 
> > So if you connect before the install finishes, [extensions] won't show up. VS Code in the web currently currently support detecting extension installs after it is running, **so you have to reload to see the extensions**.

I couldn't agree more with @nikmd23 on his comment above. This experience is so, so close to doggone perfect for this style of development. To me, re-starting the environment twice is a paper cut. To new users, it's a laceration around which they cannot work because they don't have the teams on speed-dial the way we all do. FWIW I've worked with @squillace and @itowlson on some workarounds to mitigate some of the manual steps specific to the Kubernetes extension, which they own, but they're also deeply interested in some of the opportunities our cloud-native discussion has started.

**Comment by edgonmsft** [comment]
This should be much improved now, I'll close it and please reopen if you encounter it again.

Thanks!
