### ISSUE TITLE
When creating from container succeeds, connect automatically after short delay

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/vsonline#340]
Currently, when creating from a Dockerfile, you have to manually click "Connect" once the environment has completed building.

It would be a nice UX enhancement if in this case the environment would automatically connect after a certain amount of time - say, 3 or 5 seconds.

**Comment by nikmd23** [comment]
Great idea @bnb. This is something that we've already got in development! Look for an update to come soon.

**Comment by osortega** [comment]
Hi @bnb !
This experience is now released in VS Online Web, thanks for the feedback!
