### ISSUE TITLE
Issues with VS Online and Python Kernel version due to MS Python extension

### ISSUE THREAD

**Issue by leestott** [MicrosoftDocs/vsonline#342]
Hi I have come across some issues with the running VS Online and Jupyter Python 

I have a custom docker image which gets deployed as VS Online or can be used within VS Code if you installed the associated libraries. see https://github.com/leestott/MSLearn-DataScience you can use this for repo if required

The specific Library I have noticed a issue with is the datascience Library from UC erkeley https://pypi.org/project/datascience/

Specific issues are around the use of the datascience library

I'm seeing is a issues with the MS python vs code extension where it seems to be getting in the way of the Jupyter Python Kernel.. so you get errors like this 

![datascienceerror](https://user-images.githubusercontent.com/2511341/76352707-6514bc00-6307-11ea-836b-5032c77135e8.png)

 
ImportError: cannot import name 'Table' from 'datascience' (c:\Users\leestott\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\datascience\__init__.py)  See how its using ms-python>

The version of python which is the kernel is python 3 and I am running 3.7.4 within Code as defined by the docker image.

I am getting the same error in both VS Code and VS Online so this seems to make me think it is related to the MS-Python Extension. running the same code in Azure Notebooks works perfectly see https://mslearndatascience-leestottmicrosoft.notebooks.azure.com/j/notebooks/labs/scratchpad/scratchpad.ipynb 

I have confirmed that the libraries have been installed within my VS Code and VS online with python -c datascience from the terminal and inline !pip install which confirms the libraries are there.

**Comment by leestott** [comment]
Issue identified caused see https://github.com/microsoft/vscode/issues/92511 the VSCode team have a fix due a conflict of library names. This is being resolved.

**Comment by nikmd23** [comment]
Thanks for following back up on this @leestott.

For anyone else running into this issue, please follow along at microsoft/vscode#92511. I'll close this issue in favor of that one.
