### ISSUE TITLE
Web Sign-in (with Azure AD) is broken on multiple platforms

### ISSUE THREAD

**Issue by davide-rota** [MicrosoftDocs/vsonline#348]
Hello, it seems that trying to sign-in to aka.ms/vso-login or https://online.visualstudio.com/login results in a login request loop. **This happens when I'm already signed in to Azure AD in the browser session.**

- Edge(dev) on Win10 gives me an authentication loop
![image](https://user-images.githubusercontent.com/11763/76755698-97e60680-6784-11ea-9c8f-5a465e2d8ae1.png)
- Edge(dev) on MacOS does the same
- Safari on iPad does the same

Clearing online.visualstudio.com cookies does not solve the issue. Clearing all cookies sometimes solves the issue temporarily but it comes back.
Even using a brand new Edge profile seems to work only randomly.

**Comment by davide-rota** [comment]
As an update it seems that disabling the browser cache (edge developer tools -> disable cache) solves the issue.
It might be a call to https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration that is serviced by the cache that somehow stops the logon process.

**Comment by mikeclymer** [comment]
@davide-rota It looks like your issue may be related to #345 .

**Comment by nikmd23** [comment]
Making @davide-rota's [work around](https://github.com/MicrosoftDocs/vsonline/issues/348#issuecomment-599528484) a bit more visible as many people are running into this issue:

### Issue Workaround!

Open your browser's dev tools and disable the cache on the Network tab.

![image](https://user-images.githubusercontent.com/199026/77179793-f538cb00-6a96-11ea-95f8-f7b561946c81.png)

This will get you back up and running while we work on rolling out the fix.

**Comment by srivatsn** [comment]
This infinite loop issue has been fixed. There are still some changes that we are working to improve the signin experience but folks should be unblocked now.
