### ISSUE TITLE
No "VS Online: Register Local Environment" command found

### ISSUE THREAD

**Issue by Joouis** [MicrosoftDocs/vsonline#354]
Hi,

I want to try VS Online feature, read the document, installed the plugin, but no "VS Online: Register Local Environment" command found in my VS Code.

VS Code ver: 1.43.1
VS Online ver: 1.0.1801

![image](https://user-images.githubusercontent.com/8896124/77029281-39b06200-69d6-11ea-83d2-c3d5da444e16.png)

**Comment by jkeech** [comment]
We renamed the command recently. The self-hosted environment is an environment that runs on your own machines (your local machine in this case). Do the docs reference "Register local environment" somewhere? If so, we can fix them. Thanks!
