### ISSUE TITLE
Stale Screenshot in Personalizing Doc

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#359]
The screenshot of "Dotfiles install command" at https://docs.microsoft.com/en-us/visualstudio/online/reference/personalizing is stale.

It should show "install.sh" not "~/dotfiles/install.sh" or "~dotfiles/install.sh"

**Comment by gregvanl** [comment]
Looks like these were refreshed with https://github.com/MicrosoftDocs/vsonline/commit/2124fc78f7647b11a5f3ebebdff196536602f050
