### ISSUE TITLE
After downloading the app... It won't open

### ISSUE THREAD

**Issue by Dgatsby** [MicrosoftDocs/vsonline#363]
Hey everyone, 

I'm very new to coding, and i have downloaded this app "Visual Studio Code" and I've re downloaded it multiple times, and it just doesn't open. Not sure what steps i should take next.

**Comment by jkeech** [comment]
Hi Dgatsby! Sorry you are having problems getting VS Code to work. Can you file a new issue at https://github.com/microsoft/vscode? That's the repo for VS Code. Thanks!
