### ISSUE TITLE
Refuse to use dotfiles repo

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#366]
A few hours ago I created an environment with my dotfiles repo.

Now, I can't progress forward. I'm still logged into GitHub with my one and only account, and this repo (which is private) still exists.

![image](https://user-images.githubusercontent.com/199026/77806567-0e231c80-7053-11ea-8acc-a9f406795445.png)

**Comment by jkeech** [comment]
@nikmd23, did you try signing out to clear the cached oauth token and then retry?

**Comment by nikmd23** [comment]
signing out and back in again fixed the issue. I had to sign out of all of my accounts before it'd let me sign back into my main account which was painful though.

**Comment by jkeech** [comment]
Thanks for confirming. I'll go ahead and close this issue. Feel free to reopen or submit a new issue if it happens again. It would also be helpful if you have consistent repro steps. Thanks!
