### ISSUE TITLE
Deep link handler doesn’t retain parameters after creating a billing plan

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#377]
As a new user, when I see a deep link (from some arbitrary place), this is my experience:

![Slide2](https://user-images.githubusercontent.com/199026/78390297-f0513c80-75a9-11ea-939d-fbee32eec863.PNG)
![Slide3](https://user-images.githubusercontent.com/199026/78390312-f5ae8700-75a9-11ea-9e88-7297b3aff861.PNG)
![Slide4](https://user-images.githubusercontent.com/199026/78390323-f9420e00-75a9-11ea-95d0-fcde0e118720.PNG)
![Slide5](https://user-images.githubusercontent.com/199026/78390338-0101b280-75aa-11ea-99f0-20f9c9a2579e.PNG)
![Slide6](https://user-images.githubusercontent.com/199026/78390359-07902a00-75aa-11ea-8d65-8dc76198925d.PNG)

Expected behavior is that the "create environment" form is populated with the information from the deep link.

---

*Note: This awesome issue submitted by @GraemeMalcolm. Thanks!*

**Comment by kumarz** [comment]
I have made a fix for this by carrying out the Deeplink params from the billing plan creation to the environment creation panel. This should be rolled out in the upcoming release.
