### ISSUE TITLE
Register Self-hosted Environment: (Error 1) Unrecognized option '--vso-uri'

### ISSUE THREAD

**Issue by iuiaoin** [MicrosoftDocs/vsonline#387]
When I type "VS Online: Register Self-hosted Environment" command in the command palette, vsonline reports an error: Register Self-hosted Environment: (Error 1) Unrecognized option '--vso-uri'. And it cannot register environment successfully.

vsonline: 1.0.1968
vscode: 1.43.2
OS: Win10

![image](https://user-images.githubusercontent.com/12285381/78749224-67b70f80-79a0-11ea-887d-388b65f56cb3.png)
How do I deal with this issue and register successfully？

**Comment by taiyosogawa** [comment]
@iuiaoin, Thank you for reporting this issue and I apologize for disappointing experience. We made an error in our deployment strategy, which is causing this error to occur. 

The problem should be resolved within a day or so (no extension update required).

In the meantime, you can get around this error by installing the previous version of the extension: 1.0.1889

**Comment by danieltharris** [comment]
@taiyosogawa downgrading worked perfectly. Make sure to reload vs code after installing the previous version.

Was able to register my Surface Book 2 as a test, and can initially connect using Safari on an iPad Pro (unsupported right now). I do get a timeout once vscode is showing but that's a separate issue on my end.

Thanks for the quick response with a workaround

**Comment by taiyosogawa** [comment]
@iuiaoin, @danieltharris, thanks again for reaching out and helping us resolve this issue quickly. The fix has been deployed so feel free to switch back to the latest version of the extension.

@danieltharris, if you keep seeing timeouts when connecting to your surface on a supported browser, let us know.

**Comment by iuiaoin** [comment]
@taiyosogawa, thanks for the quick response, it helps a lot!
