### ISSUE TITLE
Unable to register Self-Hosted Environment - Unauthorized

### ISSUE THREAD

**Issue by ChrisTruncer** [MicrosoftDocs/vsonline#389]
Hi,

I currently have a windows 10 system that I am trying to register for a self-hosted environment. I am able to install VS Code fine along with the online plugin. I am able to authenticate into Azure where it sees my subscription, etc.

I get to the point where it asks for the folder to use for a workspace, it then asks for the name for the environment, and then how it should install (as a service or as a process). Regardless if I click on the service or process, I am never able to get past this step. I continually get the following error message:

"Register Self-hosted Environment: (Error 1) Error calling HTTP POST at 'https://online.visualstudio.com/api/v1/environments' ErrorCode : Unauthorized"

I am able to successfully login with the Azure functions plugin, etc. and I am able to push code through VS Code to azure functions, so it isn't a matter of me giving the incorrect credentials. Any help please? If you need any additional information on my end, just let me know what else I can provide.

**Comment by jkeech** [comment]
@ChrisTruncer, can you try running the `VS Online: Sign out` and `VS Online: Sign In` commands to ensure you are signed into VSO correctly? It currently requires a different sign in than the Azure account extension.

**Comment by ChrisTruncer** [comment]
Thanks for the fast response, I just did a sign out and then signed back in. 

<img width="463" alt="signedin" src="https://user-images.githubusercontent.com/1674822/78912201-8b339600-7a44-11ea-9732-f53c13baf436.png">

I created a new resource group and online plan as well (in case somehow something was messed up in that process). But I still get to the part where I select a service or a name and it is unable to log in.

<img width="453" alt="no login" src="https://user-images.githubusercontent.com/1674822/78912248-9981b200-7a44-11ea-9de0-7be455d00be5.png">

**Comment by ChrisTruncer** [comment]
In case it helps, I am using a work account to set this up which does have multi-factor authentication enabled. I could potentially see that causing some interference, so just want to make sure to provide that info as well in case there is a different way the environment is supposed to be registered.

**Comment by jkeech** [comment]
Thanks for trying and for the extra info. I wouldn't think this is related to 2FA. @taiyosogawa is going to take a look.

**Comment by taiyosogawa** [comment]
Hi @ChrisTruncer, we're taking a look into what happened. Thanks for reporting the issue.

**Comment by taiyosogawa** [comment]
We were able to repro this issue and are working on a fix now.

As a workaround, you can try using a plan that is in the same region as you at the time that you create the environment. For example, if you're working out of the US and the plan you used was in westus2, then use a plan in eastus.

If you don't feel like making extra plans, I completely understand. We'll have a fix out as soon as we can.

**Comment by jkeech** [comment]
@ChrisTruncer, for the workaround, you can detect the current region your are hitting by looking at the `current` property in the response from https://online.visualstudio.com/api/v1/locations. The bug is that for self-hosted registration, this currently needs to match the plan location you are trying to use.

For me the locations endpoint currently shows this, so I would need to use a plan in West US 2 until the bug fix is rolled out:
```
{"current":"WestUs2","available":["EastUs","SouthEastAsia","WestEurope","WestUs2"]}
```

**Comment by ChrisTruncer** [comment]
OK, thank you both for that information, I'll test that workaround out in the meantime.

**Comment by ChrisTruncer** [comment]
As a heads up, I am unable to get the workaround to work. I did modify the region based on what was being returned as my "current" region. However when I am being prompted to enter my password when installing the service, the install is failing. It is saying I am not providing the correct password, but I know that I am. It's possible I need to make a separate issue for this, so let me know if so, but just wanted to report this since it's a continuation of the first.

<img width="451" alt="service failed login" src="https://user-images.githubusercontent.com/1674822/78930209-f55a3400-7a60-11ea-985b-c41e091409d8.png">

**Comment by ChrisTruncer** [comment]
I should be a little more clear, I did not receive the original error message that I posted up top, so that error doesn't seem to be a problem anymore, but I am still encountering an error before I am able to register my environment now with the new message.

**Comment by jkeech** [comment]
@ChrisTruncer, It sounds like you are getting further and running into a different error ☹️. Can you file a new issue for that so we can keep this one tracking the original issue? Thanks!

**Comment by ChrisTruncer** [comment]
Certainly, will do now and I'll hold off on closing this until you guys say it's pushed.

**Comment by erinxocon** [comment]
I was getting the exact issue above and after creating a new plan in the region reported from the above endpoint, everything is working.  I mean to say; the workaround is working for now for me!  I literally tried creating an environment today about 2 hours after this issue was posted.  Will be happy to try out a fix if needed!

**Comment by taiyosogawa** [comment]
@erinxocon, thanks for offering - I hope I read that right and you weren't trying to create an environment for the full two hours!

@ChrisTruncer, @erinxocon, we're planning on releasing the fix in our CLI ([installation instructions](https://docs.microsoft.com/en-us/visualstudio/online/how-to/self-hosting-cli#installation))  today. It will be available via VS Code next week (exact day depends on your location; no extension update required). I'll post again with updates.

**Comment by ChrisTruncer** [comment]
That's great, thanks for all your guys work on this, it's been fun playing with it and now I am working on adding this into my workflow.

**Comment by lucaslie** [comment]
I ran into the same issue today when checking out `vso start` for Ubuntu 18.04.

None of the above steps fixed the problem for me but I found a different work-around:

1. Open up a ssh connection with X11 forwarding (`ssh -X`) and open your (default) browser
2. Run `vso start` 
3. When being prompted to open [https://microsoft.com/devicelogin](https://microsoft.com/devicelogin), instead of opening it locally, open it on the remote browser window and follow the steps to authenticate. 
4. Once I have done that, `vso start` proceeds as expected and creates an environment.

Hope the issue gets fixed soon. :) The work-around kind of defeats the purpose of having a headless CLI lol.

**Comment by erinxocon** [comment]
@taiyosogawa Lol no I was just very lucky in that I tried to create a self hosted environment, couldn't and saw this issue posted about 2 hours before I experienced it.  After the quick workaround fix I was able to create environments again! 

Will look out for the fix next week and post the results!

**Comment by bennycornelissen** [comment]
Looking at the workaround option, I noticed that even though my iMac is pretty stationary, and my external IP at home rarely changes, the `current` location as reported by https://online.visualstudio.com/api/v1/locations changes every few minutes. That makes it very hard to reliably use this workaround.

**Comment by taiyosogawa** [comment]
Hi all, this update should be fully available now, so please feel free to try again. If you're using the CLI directly, you may need to update your version of vso. If running via the extension, no update is required.
