### ISSUE TITLE
Service Installation Failure - Incorrect Password

### ISSUE THREAD

**Issue by ChrisTruncer** [MicrosoftDocs/vsonline#393]
As a continuation of #389, I am trying to register a self-hosted environment. I am getting to the point where I am installing Visual Studio Code without any issues (including the online plugin). I am now being prompted if I would like to install a service or run a process.

When I select to install a service, it is unable to do so. I am prompted for my password (which it verifies my password, i tried giving an incorrect password and it re-prompted me until I provided my correct password) and then it attempts to install the service (my assumption). Ultimately, it fails and says I am giving it incorrect credentials, which I have verified I am not doing so.

If you need any additional details from me, just let me know.

<img width="451" alt="service failed login" src="https://user-images.githubusercontent.com/1674822/78930209-f55a3400-7a60-11ea-985b-c41e091409d8.png">

**Comment by Davsterl** [comment]
Hi Chris,
Can you give us any details on if you're on a domain joined machine? Is it a local user? 
I'm just looking to narrow our repro down so we can figure out what's going on

**Comment by ChrisTruncer** [comment]
Hi, this is running as a local user (not domain joined)

**Comment by mikeburgh** [comment]
I am hitting the same issue... The log if it helps: 


[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:25.295 CLI I] vso v1.0.1954.49374 (pid: 7076)

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:25.459 CLI I] Using VSO URI: https://online.visualstudio.com/api/v1/

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:26.003 CLI I] Creating your environment...

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:27.525 CLI I] Saving local configurations...

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:27.730 CLI I] Authenticating...

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:28.794 CLI I] Starting agent...

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:28.796 CLI I] Creating service...

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:34.759 CLI I] Created service vso.xxxx.Mike
[2020-04-09 21:32:34.759 CLI I] Starting service vso.xxxx.Mike...

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:34.765 CLI E] [!ERROR] Failed to start service: Incorrect password for user.

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:34.765 CLI I] Deleting service vso.xxxx.Mike...

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:34.767 CLI I] Deleted service as part of cleanup

[StaticEnvironmentRegistration I] vso: [2020-04-09 21:32:34.783 CLI E] [!ERROR] Failed to register and start service/daemon: System.Exception: Incorrect password for user.
   at Microsoft.CloudEnvironments.CLI.Commands.StartLocalEnvironmentCommand.StartVmAgentServiceAsync(String user) in E:\A\_work\459\s\src\VSOnline\CLI\Commands\StartLocalEnvironmentCommand.cs:line 225
   at Microsoft.CloudEnvironments.CLI.Commands.StartLocalEnvironmentCommand.ExecuteAsync(RegisterEnvironmentParams parameters, String aadToken) in E:\A\_work\459\s\src\VSOnline\CLI\Commands\StartLocalEnvironmentCommand.cs:line 166

**Comment by Davsterl** [comment]
Hello,

You'll need to grant Log on as a service to your user account. 
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/log-on-as-a-service

We're sorry you ran into the issue!

**Comment by ChrisTruncer** [comment]
I can confirm that this fixed my issue. Thanks for letting me know the fix!

**Comment by taiyosogawa** [comment]
@ChrisTruncer, thanks for reporting it. We'll work on improving this aspect of the experience.
