### ISSUE TITLE
Service with Microsoft Account

### ISSUE THREAD

**Issue by OneCyrus** [MicrosoftDocs/vsonline#398]
it looks like it doesn't work when logging in to Windows with a Microsoft Account.

most likely it tries to use the username MicrosoftAccount\user@outlook.com as the service loginname and fails at that.

![image](https://user-images.githubusercontent.com/7747800/78979927-226c1c80-7b1d-11ea-913b-e5443cd6fb49.png)

**Comment by taiyosogawa** [comment]
@OneCyrus, could you see if this is the same as #393? You might need to grant your user "log on as a service" privileges: https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/log-on-as-a-service

**Comment by OneCyrus** [comment]
great that did the work. i had to add the backing user of the microsoftaccount. (not the one actually displayed at login window)

**Comment by taiyosogawa** [comment]
Glad to hear that did it, and I see what you mean in terms of the displayed username. We're making some improvements to the error messaging and can track further improvements in #393. I'll close this one out.
