### ISSUE TITLE
More explanation on self-hosted

### ISSUE THREAD

**Issue by dio** [MicrosoftDocs/vsonline#41]
I'm not sure what is self-hosted in this table. I just want to use an Ubuntu VM.

![image](https://user-images.githubusercontent.com/73152/68143007-158e4000-ff63-11e9-9c09-adf7612dc3be.png)

**Comment by taiyosogawa** [comment]
Hi dio,Self-hosted environments are a "bring your own" device option to create an environment on your machine.

**Comment by taiyosogawa** [comment]
If you're just looking for an Ubuntu VM, you can just refer to the Standard/Premium pricing depending on your HW spec needs. Thanks for asking and let us know if you have any other questions!

**Comment by scottymcraig** [comment]
I'm not sure if that's what he's asking - I had a similar question but assumed that it was not possible.  I think he is asking if you can create a self-hosted environment without a GUI - for example, if I have a box hosted somewhere that is just running Ubuntu server, can I stand up an instance without having a full Visual Studio Code instance on it (since there's no GUI).

**Comment by taiyosogawa** [comment]
Ah, I see your point - thanks for asking.

Presently, running the "Register" command via a full instance of VS Code is the only supported flow, but the scenario you described of hosting a server without a GUI is on the product roadmap.

**Comment by dmitshur** [comment]
I was just asking the same question about headless servers [on Twitter](https://twitter.com/dmitshur/status/1191549248191520768).

FWIW, I found that it is possible to install VS Code and the VS Online extension via command line (i.e., see https://code.visualstudio.com/docs/setup/linux and https://code.visualstudio.com/docs/editor/extension-gallery#_command-line-extension-management), but I didn't find a way to configure the VS Online extension. That seems to need a GUI right now.

**Comment by scottymcraig** [comment]
@taiyosogawa If you are looking for feedback on what users would prefer happen soon, I would vote for this.  Simply because I would love to use this functionality, but I already have my own infrastructure and don't need to spin up a new VM for this, which would be cost prohibitive for me.

I realize you all are swamped with requests, but just my two cents 😄

**Comment by taiyosogawa** [comment]
@dmitshur @scottymcraig, thanks for connecting the conversation on Twitter and sharing the features that would help you most. I'm excited about your interest in self-hosted environments and your feedback is immensely helpful in helping us prioritize. We've created a [tracking item](https://github.com/MicrosoftDocs/vsonline/issues/69) for command-line functionality, and I've linked to this item to capture all the support.

**Comment by OneCyrus** [comment]
but should self-hosted environments just be available in the browser version of vscode? or do we need internal network connectivity for this to work?

because currently i get ```Failed to connect to the remote extension host server```

**Comment by taiyosogawa** [comment]
@OneCyrus, you _should_ be able to connect to a self-hosted environment via the browser (no special setup required). Sorry to hear it didn't work for you. 😞 

We've seen some failures on the first connection but subsequent successful connections, so I've created a [tracking issue](https://github.com/MicrosoftDocs/vsonline/issues/87) for that. The same happens on the first connection after upgrading your version of VS Code or switching to/from insiders.

If you think you're seeing something different, we can create a separate issue.

**Comment by taiyosogawa** [comment]
It _looks_ like we have separate tracking issues for the points brought up in this thread. To help us keep things organized, I'm going to close this one, but let me know if I've missed anything.
