### ISSUE TITLE
Registering Microsoft.VSOnline provider appears to hang

### ISSUE THREAD

**Issue by nathankitchen** [MicrosoftDocs/vsonline#416]
I've got a couple of subscriptions that I'd like to use to host VSOnline public preview. The first was my VS MSDN subscription (offer ID MS-AZR-0063P), which has some free credit so seemed like a great place to try things out. I attempted to create an environment with it via VSCode VS Online Extension, but received an error stating that the resource provider "Microsoft.VSOnline" was not enabled.

I logged into the subscription and registered the resource provider, but it's been hung in the "Registering" state for over 3 hours now (started around 12:00GMT, 17/04). My typical experience of resource providers is that they register in a few seconds, maybe a few minutes.

As that seemed to not be working, and I wondered if there was some restriction on MSDN subscriptions, I tried the same thing on another subscription I'm owner of in an EA (offer ID MS-AZR-0017P). I've had the same experience there: VSO extension said the provider wasn't registered, and it has also been sat in "Registering" state for ~2 hours (again, around 13:00GMT, 17/04).

Unsure whether this is an intended subscription limitation in public preview, or a bug.

**Comment by jkeech** [comment]
Thanks for reporting this issue. The registration should only take a few seconds, like you suggest. We are looking into it. Do you mind sharing one of your subscription Ids?

**Comment by nathankitchen** [comment]
@jkeech - happy to share, I'll send the details over via email directly.

**Comment by jkeech** [comment]
@nathankitchen, small update: The resource provider registrations for the Microsoft.VSOnline RP are hanging in ARM prior to getting to our service. The ARM team is engaged and working on a fix.

**Comment by jkeech** [comment]
@nathankitchen, I'm still following up with the ARM team, but my test registrations have all been succeeding for the past hour. Can you retry and let me know if it's still hanging for you or not?

**Comment by nathankitchen** [comment]
@jkeech, I logged in and found that the provider was now showing as registered.

For completeness, I then unregistered which took a couple of seconds. I then registered again, which was successful. It took a longer than unregistering, but nothing out of the ordinary.

I then used the VSCode Extension to provision an environment, which was also successful. Though that latter step is probably outside the scope of the original issue raised, it's nice to have an end-to-end that shows the registration actually works, and it isn't mis-reporting success.

Much appreciate the assist. I'll leave you to close the issue, either now that I've reported it resolved or once the ARM team get back to you. Thanks again.

**Comment by jkeech** [comment]
Thanks for confirming everything is working for you! Let us know how it goes, and if you run into any other problems or have suggestions/feature requests don’t hesitate to open up another issue.

**Comment by jkeech** [comment]
@nathankitchen, following up here, I confirmed with the ARM team that this issue is fully resolved. There was a 7 hour window on Friday where the VSOnline resource provider configuration in ARM was in a state where it wasn't processing registration requests, and the ARM team pushed out a hotfix to fix it. Registrations have been working as expected since then.
