### ISSUE TITLE
Allow tweaking of suspend/tier settings

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/vsonline#42]
Currently, it doesn't seem like there are direct avenues to tweak the environment details like time to suspend or standard/premium tier.

Personally, as someone starting out I'm not entirely sure what the best suspension timing would be for my use case. Being able to adjust after creation would be super helpful in this context.

Additionally – and I know this one is likely harder – there are times where my development workflow is significantly more intense than others. Being able to switch between the tiers dynamically would be incredible.

**Comment by jkeech** [comment]
Both of these are on our roadmap. Switching the instance type will likely suspend the environment temporarily, and then it can be resumed on the other compute tier.

**Comment by cmbrose** [comment]
This feature has been added to both the VS Code extension and the VSO portal.  Please let us know if there are any further feature requests for it!
