### ISSUE TITLE
Self-Hosted Environment Stopped Working

### ISSUE THREAD

**Issue by allan-mobley-jr** [MicrosoftDocs/vsonline#431]
Up until yesterday, I have been running VS Online with self-hosted option without a problem for a couple of months now.

Then, perhaps after an update to my Visual Studio Code Insiders on the host machine, the whole process stopped working. Not a hundred percent that is what caused it, though.

My host machine is a high-powered Origin gaming desktop with Windows 10 Pro, kept up to date.
I use Visual Studio Code Insiders to set up the host environment on this machine and a Surface Book 2 to connect to my host machine via a Chrome browser and VS Online.

I have tried restoring the environment, removing it and recreating it. I have uninstalled and reinstalled Visual Studio Code Insiders, then recreating the environment. I have cleared browser cookies and history. All to no avail.

This has put a strain on my development process as I will now have to go back to having multiple Dev machines.

**Comment by taiyosogawa** [comment]
Hi @allan-mobley-jr, thanks for reporting the issue - understanding the troubleshooting steps you've taken is helpful. I've got a few more questions to better understand the situation:

1) Can you provide more detail on the exact failure you see? (Is it when you register an environment? Is it when you connect to it? Do you see an error message?, etc.)
2) Are you running the self-hosted environment as a process or service?
3) It sounds like you registered via the VS Code Insiders extension, right? Have you ever used the CLI to create a self-hosted environment?

**Comment by allan-mobley-jr** [comment]
1. Can you provide more detail on the exact failure you see? (Is it when you register an environment? Is it when you connect to it? Do you see an error message?, etc.)

When I open up my browser and go to visusal studio online, I select my self-hosted environment, and a vscode editor opens up. So far so good.

The editor appears to be trying to open up the remote folder on the self-hosted machine, but after a minute or two it times out: 
* Failed to connect to the remote extension host server (Error: Object reference not set to an instance of an object.)

2. Are you running the self-hosted environment as a process or service?

Originally, when I first set this up, there was not an option, so it would be which ever the default was when visual studio online first went into public preview.

Since the issue arose, I have tried restoring the environment, as well as starting over and tried both options to no avail.

3. It sounds like you registered via the VS Code Insiders extension, right? Have you ever used the CLI to create a self-hosted environment?

Yes, but have tried with the default VS Code editor also. No, I have not tried via CLI.

**Comment by taiyosogawa** [comment]
Thanks for the additional info - it looks like you're seeing issue #421, which we're working to deploy the fix for. I know it's not ideal, but a workaround would be to:

1) Unregister the existing environment via the extension
2) kill all running instances of 'vsls-agent'
3) Install the CLI version and run `vso start`: https://docs.microsoft.com/en-us/visualstudio/online/how-to/self-hosting-cli 

Since we're tracking on #421, I'll close this issue to keep things organized. I apologize for the inconvenience, and would be happy to carry on the conversation over there.

**Comment by taiyosogawa** [comment]
@allan-mobley-jr,

Sorry - it looks like this update has already been deployed. Could you just try:
1) killing all running instances of the vsls-agent process
2) trying restore and connect one more time

Let me know if that works.

**Comment by allan-mobley-jr** [comment]
Unable to open 'Mobsites': Unable to read file 'vscode-remote://vsonline+fa473e29-94cd-477c-826f-d3d5512a9aa0/c:/Users/me/source/repos/Mobsites' (Error: Object reference not set to an instance of an object.).

Failed to connect to the remote extension host server (Error: Object reference not set to an instance of an object.)

![vscode](https://user-images.githubusercontent.com/38449003/80400326-a269e480-8888-11ea-9531-08077ab6503e.png)

**Comment by allan-mobley-jr** [comment]
Spinning indefinitely now, after showing it was restored

**Comment by allan-mobley-jr** [comment]
That's with the latest update to VS Code Insiders

**Comment by taiyosogawa** [comment]
Thanks for the update. Just to clarify, did you unregister+register or just restore (or both)?

I'm wondering what version of the agent was running. Could you check the contents of `%USERPROFILE%\.vsonline\cli`? There should be some directories that indicate agent versions - let me know what you see.

**Comment by allan-mobley-jr** [comment]
VSOAgent_win_3669160

**Comment by allan-mobley-jr** [comment]
Register Self-hosted Environment: (Error 1) Failed to start service: Service Configuration Manager failed with exit code (2). , Failed to register and start service/daemon: System.Exception: Service Configuration Manager failed with exit code (2).

**Comment by allan-mobley-jr** [comment]
Just re-registered and tried as a process and was successful.

**Comment by taiyosogawa** [comment]
That's great! Looks like the original issue is resolved, but I am curious what happened with registering as a service. SCM Exit code 2 means that the service manager was unable to find the executable specified. I'll take a look into why that might have happened.

**Comment by allan-mobley-jr** [comment]
Yes, I would like to run it as a service so I don't have to worry about restarts on the host machine.

**Comment by allan-mobley-jr** [comment]
Self-hosted as a service is working for now

**Comment by taiyosogawa** [comment]
Thanks for reporting, @allan-mobley-jr. My best guess at the moment is that the executable got moved/deleted at some point but was reinstalled. It's hard to say, but I haven't seen that error happen elsewhere. I'll close this for now, but will be on the lookout for similar scenarios. Feel free to re-open if you see the issue again.
