### ISSUE TITLE
Old environment won't start

### ISSUE THREAD

**Issue by Quantumplation** [MicrosoftDocs/vsonline#434]
Hello!

I created a standard linux environment back in November.  It's still listed in my environments, and I've been trying to connect to it to recover some code that was on it.  However, the startup seems to stall indefinitely.  Anything I can do to access the files on this VM to recover the code changes I had made?

**Comment by jkeech** [comment]
@Quantumplation, can you share the environment Id (or the full url when trying to connect to the environment in the browser)? We can look at the logs to see what is going on.

**Comment by Quantumplation** [comment]
Hi!

Sure! I wanted to provide more information with the initial report, but wasn't sure what specifically to provide.

4e89d1fd-e665-4a00-98e2-1b74e0142cf9

https://online.visualstudio.com/environment/4e89d1fd-e665-4a00-98e2-1b74e0142cf9

**Comment by edgonmsft** [comment]
Hi Pi!

Just to let you know that we are working on your environment. I'll let you know as soon as its back up.

Since this is an old environment we had to perform a migration, and due to the size of the container we ran out of space. We are doing the migration manually now.

Thanks!

**Comment by Quantumplation** [comment]
Awesome, thanks!  I appreciate the effort.

I *love* these online environments, btw! Really great work!

**Comment by edgonmsft** [comment]
Hi Pi!

I just finished the migration, can you start your environment again?

FYI you are very very close to the storage limit. Creating more files might tip the storage limit.

Please close the issue if it works again. If not let me know!

Thanks!

**Comment by Quantumplation** [comment]
Hey!

I'm still having trouble connecting, unfortunately.  It seems to get further, but this appears:

![image](https://user-images.githubusercontent.com/49870/80549973-9404f100-898c-11ea-9825-ad06d32585c5.png)

and on hovering, it says "Unable to resolve workspace folder".

It's also worth noting that I don't plan on using this particular environment long term, I've moved over to another environment.  I'm just trying to recover some partially written code that I believe is on the machine.

**Comment by edgonmsft** [comment]
Ok thanks! 

Let me take a look and I'll get back to you.

**Comment by edgonmsft** [comment]
Hi Pi!

I just made an additional fix, could you try again?

Thanks and sorry for the inconvenience.

**Comment by Quantumplation** [comment]
Still no luck.

And it's not too big an inconvenience :)

**Comment by edgonmsft** [comment]
It seems that the container was still running out of space, I deleted some unnecessary files. 

Can you try again? Lets hope third time's the charm.

**Comment by Quantumplation** [comment]
Thank you! It worked this time.
