### ISSUE TITLE
Need PowerShell support

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/vsonline#44]
The PowerShell Extension gets installed, but pwsh isn't in the container image so the terminal doesn't work

**Comment by sharma-anuradha** [comment]
Hi @SteveL-MSFT , thank you for reporting this issue. Are you using Windows based VSO environment?

**Comment by lostintangent** [comment]
@SteveL-MSFT Yeah this is a total omission, so we're planning to add Powershell Core to our default environment images within the next week or two. Stay tuned!

**Comment by jkeech** [comment]
This is fixed now in our base image. All new environment creations have `pwsh` installed and on the `PATH`, and VS Code also detects it as a potential default shell that users can select.
