### ISSUE TITLE
Failed to connect to the remote extension host server (Error: handshake timeout) 

### ISSUE THREAD

**Issue by itsmordecai** [MicrosoftDocs/vsonline#443]
I am fairly new to WSL but everytime after creating a file within WSL Terminal, on attempting to open with VS Code (e.g code hello*) I get the titled error thus I am unable to edit the file from VS Code. Also the file appears empty on VS Code unlike on nano.

**Comment by itsmordecai** [comment]
![image](https://user-images.githubusercontent.com/39312305/80665522-5c886880-8aa2-11ea-93e4-54cd1b394d61.png)

**Comment by taiyosogawa** [comment]
Hi @itsmordecai, thanks for reporting this issue. Could you provide a bit more context on the steps you took to get to this state? Are you using the Visual Studio Online extension?

**Comment by itsmordecai** [comment]
Hi @taiyosogawa  I have VS Code installed on Windows 10.

I reach the mentioned error everytime I create a file in WSL lets say `echo "hello" > hello.txt`

On opening the file with VS Code via `code hello.txt`
I get the screenshoted error and the file is empty (doesn't have the "hello".)

The same error appears when I open VS code from Windows and start the connection to WSL. 

I run Kali on my WSL

**Comment by jkeech** [comment]
@itsmordecai, This sounds like an issue with Remote WSL, which is slightly different from Visual Studio Online / Visual Studio Codespaces. Please file an issue at https://github.com/microsoft/vscode-remote-release for Remote WSL. Thanks!
