### ISSUE TITLE
Cannot clone git git repo

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/vsonline#45]
One of my repos doesn't seem to be able to be cloned:

![image](https://user-images.githubusercontent.com/502396/68146114-46d82300-ff05-11e9-9448-f82b4fd08c1c.png)

Here's the [link to the repo](https://github.com/cutenode/1x.engineer). It's a relatively straightforward git repo with no dependencies – it's just an HTML site served via GitHub Pages.

The error isn't particularly helpful as to *why* the repo isn't able to be cloned as an environment. Would be great to be able to create an environment from this repo, though ❤️

**Comment by osortega** [comment]
Thanks for reporting this @bnb 

This seems to be an issue in the web platform only. We will work on having that fixed.
In the meantime, you could create the environment in VS Code and access it from the web browser without any problems.

**Comment by plisy** [comment]
@bnb fix has been deployed now.
