### ISSUE TITLE
Support user supplied version of Docker Compose

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#457]
When I specify version 3.4 in my `docker-compose.yml`, I am unable to create an environment in VS Codespaces. This is the error I get:

```
COMMAND: docker-compose --project-name vsonline-compose -f docker-compose.yml -f /root/.vsonline/.vsoshared/docker-compose.vsonline.yml up -d --build
Version mismatch: file ./docker-compose.yml specifies version 3.4 but extension file /root/.vsonline/.vsoshared/docker-compose.vsonline.yml uses version 3.0
docker-compose process exited with exit code 1
Running docker-compose up failed. Please inspect the logs for more information.
```

The error leads me to believe that I'm forced to use version 3.0 - though there are lots of features and capabilities that extend beyond 3.0 that would be great to leverage. 

It's also unclear if I could use an *older* version of the compose schema (if I have an existing file) given that the error specifically mentions 3.0.

**Comment by edgonmsft** [comment]
I used version 3.0 as a minimum one, I'll make changes to allow usage of higher versions.

**Comment by Chuxel** [comment]
This affects the dapr dev containers as well.  See https://github.com/microsoft/vscode-dev-containers/blob/master/containers/codespaces.md

**Comment by edgonmsft** [comment]
Released! 🚀
