### ISSUE TITLE
Mount property ignored, breaks kubernetes-helm

### ISSUE THREAD

**Issue by Chuxel** [MicrosoftDocs/vsonline#459]
(Note that mount points is my current theory as to what is going on here without knowing what is going on under the hood.)

The Docker-in-Docker definition in the vscode-dev-containers repository allows developers to use a Docker from within a container.  The kubernetes-helm definition is similar.  In both cases, the containers fail to start for slightly different reasons.

1. <strike>In the [Docker-in-Docker](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-in-docker) case, the docker socket is expected to be mounted at `/var/run/docker-host.sock`, not `/var/run/docker.sock`.  Consequently the scripts go haywire.</strike> 
2. In the Kubernetes-Helm case, there are `.bashrc` scripts that optionally copy local config to the right place. When the source folders are not found (the mount points), bash fails to start.

Note that in the [Docker in Docker Compose](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-in-docker-compose) case, things actually work as expected because Compose does the mounting for us.

Repro: 
1. <strike>Open https://github.com/Chuxel/codespace-test in a Codespace to see Docker-in-Docker</strike>
2. Open https://github.com/Chuxel/codespace-test2 in a Codespace to see Kubernetes-Helm

//cc: @edgonmsft @jkeech

**Comment by jkeech** [comment]
@edgonmsft we need to change to only bind mount the docker socket for kitchensink images, not for custom containers. Users can explicitly opt in to bind mounting the docker socket in `devcontainer.json` for custom containers if they want.

**Comment by edgonmsft** [comment]
PR for what @jkeech mentions is out.

The second part would be reading the mounts from devcontainer.json.

**Comment by edgonmsft** [comment]
I have a PR for the second part, the interesting issue is what to do when this mounts don't make sense in our context or won't work.

One example is repos that mount the Kubernetes configuration from the VM to the container, in this case if that doesn't exist then the creation would fail with a mount error.

**Comment by jkeech** [comment]
@edgonmsft, I think that's OK. But it does open up some other questions. How would users specify different types of host configurations/setups for remote containers vs Codespaces, etc. Or even for different types of host setups in remote containers. The single `devcontainer.json` file which is expected to work in all situations doesn't work in that case.

But as a starting point, I think using the mounts exactly as they are provided, and having it fail if a provided mount doesn't work seems like a reasonable solution.

We do not want to end up in a place where we try supporting every possible mount config by building a giant "kitchensink" equivalent on the host VM. We intend to keep the host VM a clean docker host running Ubuntu, so as long as we document that, users can provide mounts that will work on a base Ubuntu image.

**Comment by Chuxel** [comment]
Yeah, I've updated the definition to check for the existence of the folder so this won't fail if the mount is not present. The confusion for me came from the fact that it appeared to work, but actually didn't.  It took me a while to track down that this was what was actually going on.  If the mount had just failed outright, I would have commented it out and moved on.

Mounts are a general consideration even locally for this particular definition since "~/.minikube" won't exist on a mac or Windows machine running Kubernetes in Docker Desktop, but would for anyone using Minikube on Linux.  Right now there's comments in the devcontainer.json on it.

**Comment by Chuxel** [comment]
@edgonmsft FYI - @orph pointed out that always mounting the docker socket also breaks full docker in docker.

**Comment by edgonmsft** [comment]
Thanks! That change is in progress already.

**Comment by orph** [comment]
The other side of dropping the docker socket mount is running the devcontainer docker itself with `—privileged` (or supporting that option passed in `runArgs`). Is this planned as well?

**Comment by edgonmsft** [comment]
Yep, with this change I'm also adding the option to add `--privileged` on the run arguments.

**Comment by edgonmsft** [comment]
Released! 🚀
