### ISSUE TITLE
I Can`t create a new plan

### ISSUE THREAD

**Issue by julioarruda** [MicrosoftDocs/vsonline#461]
Today i tried to use this one on first time, but, when i tried to create my new plan, the codespaces can`t to show my azure subscriptions, show only an older one.

Anyone know what happen here?

![image](https://user-images.githubusercontent.com/5204009/81217039-528acc00-8fb2-11ea-9ed8-9801e6888f93.png)

**Comment by jkeech** [comment]
Codespaces only works currently with the default AAD tenant on your account. You will be able to see and use Azure subscriptions in your default tenant, but not other tenants that you are a guest of. We are tracking multi-tenant support in #39. Thanks!

**Comment by julioarruda** [comment]
Oh, ok. 

Thanks
