### ISSUE TITLE
Cannot add new instances after using "suspend" button in azure portal

### ISSUE THREAD

**Issue by nimamahmoudi** [MicrosoftDocs/vsonline#467]
I wanted to rename one on self-hosted VSCode Codespaces instances, so I tried suspending the worker in order to access its configuration. After that, I can no longer add any instances to my account. I always get the following error for the `vso` CLI tool:

[!ERROR] Error calling HTTP POST at 'https://eastus.online.visualstudio.com/api/v1/environments' ErrorCode : Forbidden

**Comment by jkeech** [comment]
@nimamahmoudi, you might be running into the [quota limit](https://docs.microsoft.com/en-us/visualstudio/online/resources/faq#what-are-visual-studio-onlines-quotas). If so, try deleting one of your Codespaces and then re-registering.

**Comment by nimamahmoudi** [comment]
That's the issue for my account, thanks. I didn't see that in the documentation.
