### ISSUE TITLE
Dotnet tools should work by default in the base image

### ISSUE THREAD

**Issue by jkeech** [MicrosoftDocs/vsonline#472]
Currently, dotnet tools do not work in the base image by default since the tools directory is not on the `PATH`, and the `DOTNET_ROOT` environment variable is not set to a dotnet core runtime. The base image should be augmented to include the following:

```bash
export DOTNET_ROOT=$(dirname $(realpath $(which dotnet)))
export PATH=$PATH:$DOTNET_ROOT/tools
```

Reference: https://github.com/dotnet/runtime/issues/3810#issuecomment-575597178

**Comment by jcansdale** [comment]
I think the 2nd `export` should have been:

```
export PATH=$PATH:$HOME/.dotnet/tools
```

Not sure what I was thinking there. :blush:

**Comment by dmgardiner25** [comment]
Fix has been deployed.
