### ISSUE TITLE
"overrideCommand" property does not override ENTRYPOINT like it does in Remote - Containers

### ISSUE THREAD

**Issue by Chuxel** [MicrosoftDocs/vsonline#477]
Currently the Remote - Containers extension overrides both the CMD and ENTRYPOINT whenever `overrideCommand` is set to `true` (which is the default) in devcontainer.json.

It appears that in codespaces is either ignoring the overrideCommand property or is not following the same behavior in Remote - Containers.

Repro:

1. Open https://github.com/Chuxel/codespace-test in a Codespace and note that the creation fails with an exit code of 100.  The log will contain `(!!!) I was fired and did an exit code of 100`
2. Open this same repository in the Remote - Containers extension and the message will not appear.

@chrmarti - I assume it is intentional that Remote - Containers is overriding the ENTRYPOINT here as well?

//cc:  @edgonmsft 

(This is what was breaking Docker-in-Docker originally - not #459 like I had originally thought. I've since fixed the error that caused the break, but this behavior difference remains.)

**Comment by chrmarti** [comment]
@Chuxel Yes, that's intentional. The intent of `overrideCommand` is to override what the container would normally do which includes the entrypoint.

**Comment by edgonmsft** [comment]
Released! 🚀
