### ISSUE TITLE
POST requests on port forwarded port has no body in web browser

### ISSUE THREAD

**Issue by 74th** [MicrosoftDocs/vsonline#478]
1. Create new codespaces environment with git repository https://github.com/74th/vscode-typescript-handson.
2. A connection in first time always reaches time limit, so do `Reload Window` (it is small problem.).
3. Run task `webpack build`
4. Launch debug `Launch Server(ts-node)` (It launches web application.)
5. Click Forwarded Ports , localhost:8080

![image](https://user-images.githubusercontent.com/1060011/81465955-e81f9900-9208-11ea-97a7-05454ec05d30.png)

6. Add breakpoint src/server/api.ts L:72

![image](https://user-images.githubusercontent.com/1060011/81466012-36349c80-9209-11ea-9eb5-b50e47797d50.png)

7. fill task name and push add button. It requests has json body.

![image](https://user-images.githubusercontent.com/1060011/81465988-0be2df00-9209-11ea-8076-94cddf934abb.png)

![image](https://user-images.githubusercontent.com/1060011/81466066-86136380-9209-11ea-824f-7d3d6d16faaa.png)

8. But req.body on the breakpoint has no body.

![image](https://user-images.githubusercontent.com/1060011/81466275-5a917880-920b-11ea-9f64-cc6ac01a2b79.png)

On the other hand、
I connected to Codespaces instance in VS Code, and used Portforwarded Ports (localhost:8080), it worked fine.

![image](https://user-images.githubusercontent.com/1060011/81466237-eb1b8900-920a-11ea-8c69-43e6c7ce6e2b.png)

**Comment by plisy** [comment]
Hello, thanks for reporting the issue. Sending request body currently doesn't work in port forwarding on web. We are tracking the issue already here #213.

We are working on more complete port forwarding solution for web as well. In the meantime, please use desktop VSCode.

I'm closing this issue as a duplicate.

**Comment by Prottoy2938** [comment]
@plisy , any solution/ workaround yet?
