### ISSUE TITLE
Can't create environment from ADO Git Repo HTTPS 'Clone' Url

### ISSUE THREAD

**Issue by ryandle** [MicrosoftDocs/vsonline#48]
1. Go to an Azure Dev Ops git repo & click the 'Clone' button.
2. Copy the HTTPS Url.
3. Paste that into the `Git Repository` field of the `Create Environment` dialog in VSO Web (https://online.visualstudio.com/environments/new).

**Expected:** This Url works for creating an environment from a git repo.

**Actual:** You see red error text below the field "We are unable to clone this repository automatically."

**Comment by wangjaso** [comment]
Hi Ryan, thanks for reporting this.

Currently we only support auto-cloning private GitHub repos. Support for other sources will be added later. For Azure DevOps, we suggest to Create an empty environment and clone from there.

**Comment by nathansoz** [comment]
I was able to do this from the actual VSCode extension and then open it in the online editor FWIW.

**Comment by edgonmsft** [comment]
We do have support for Azure DevOps repositories from the VSCode extension, the website support is in progress.

**Comment by ryandle** [comment]
Thanks for the update! Using the extension worked for me too.

Perhaps the documentation could be updated to call out what providers are
supported where? If it’s there and I missed it, my apologies.

**Comment by tspascoal** [comment]
> Hi Ryan, thanks for reporting this.
> 
> Currently we only support auto-cloning private GitHub repos on the website. Support for other sources will be added later. For Azure DevOps, we suggest to Create an empty environment and clone from there.

When you clone from there there is no  .devcontainer support. Is there any way to force the use of  .devcontainer when we clone locally?

**Comment by nikmd23** [comment]
@ryandle:

The docs covering which Git scenarios are supported at in the how-to docs: [VS Code](https://docs.microsoft.com/en-us/visualstudio/online/how-to/vscode#cloud-hosted) & [browser-based editor](https://docs.microsoft.com/en-us/visualstudio/online/how-to/browser#create-an-environment)

**Comment by nikmd23** [comment]
@tspascoal would you mind clarifying your question? I'm having difficulty following it.

**Comment by jkeech** [comment]
@tspascoal, there's currently no way to re-evaluate .devcontainer.json after environment creation. That feature request is being tracked in #51.

**Comment by judyanndixon** [comment]
I was able to clone the Azure DevOps repo by just using the terminal online and running the git clone from there, but when I attempted to push a commit , it fails authentication every time.  I can make the same change and use the same password from desktop version of VS Code without issue.

**Comment by judyanndixon** [comment]
Also, I can only clone public Azure DevOps repos.  Private ones ask for the password and also cannot authenticate.

**Comment by jkeech** [comment]
We are working on adding support in the VSO web portal for private ADO repos. Stay tuned!

**Comment by mchelen** [comment]
Glad to hear this is a planned feature! Are the types of private repos that are supported (GitHub only?) documented anywhere?

**Comment by nikmd23** [comment]
They are listed here: https://docs.microsoft.com/en-us/visualstudio/online/how-to/browser#create-an-environment

**Comment by srivatsn** [comment]
This now supported in the browser as well.
