### ISSUE TITLE
Extension for VS Code seems to download megabyte of data and fills my RAM

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/vsonline#49]
Hello,

I just noticed with the announced VSO extension fro VSCode seems to start downloading data. It is a lot. Within 2 minutes I have a VSCode process running with 10GB of RAM and it nearly crashes my desktop PC.

I am not really sure what I can provide you so you know what the problem is. I can only tell you what I did generally:

* accessing the new VSO portal an created an environment with linux (4core, 8GB ram)
* connecting to a git repo
* opening VS Code in the browser and play around
* open the same environment from the VSO dashboard to VS-Code
* being asked to install the extension
* playing around (not sure what I did, but just opening files and editing)
* noticing that PC slows down and seeing the following process constantly consuming a lot of resources

![image](https://user-images.githubusercontent.com/7256168/68156182-9b05f600-ff4b-11e9-89f9-4511ca055fe4.png)

If I can provide a more proper dump or anything, then please tell me.
But also with instructions on what and how I can provide that.

thanks already!

**Comment by bjbennet** [comment]
Hi @SebastianSchuetze, we have not been able to reproduce the issues you were seeing. Can you make sure you have the latest version `(1.0.1424)` of the extension installed and retry?

**Comment by SebastianSchuetze** [comment]
@bjbennet I will check again and report back!

**Comment by jkeech** [comment]
@SebastianSchuetze, have you seen this happen again?

**Comment by SebastianSchuetze** [comment]
@jkeech thanks for notifying me. No it has not happened to me again. In case it does. I will open again. Just for the next time, is there any additional logs that I can provide from the extension to give you a better understanding of any problem that might appear?

For now I will close my issue.
