### ISSUE TITLE
.devcontainer.json settings object

### ISSUE THREAD

**Issue by tonyeung** [MicrosoftDocs/vsonline#490]
In the https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring page, the description of the "settings" property is: "Adds VS Code settings.json values into the environment."

I took this to mean I can load default settings into this object and see it in visual studio code, so I created a .devcontainer.json file in my project repo:

```
{
    "extensions": [
      "dbaeumer.vscode-eslint"
    ],
    "settings": {
      "files.autoSaveDelay": 999
    } 
}
```

Was my interpretation of the docs wrong?
The eslint extension was installed correctly, but the settings object did not get applied when i looked at the settings (ctrl+, and view code).

**Comment by edgonmsft** [comment]
Hi @tonyeung!

The settings get copied as-is to a default path where vscode remote server is installed. When you connect to the environment, if you go to the settings panel you should see your setting in the Remote tab.

Can you see if it got applied?

Let me try yours but for reference this is an example that changes the theme and sets the default terminal for vscode.

"settings": { 
		"workbench.colorTheme": "Monokai",
		"terminal.integrated.shell.linux": "/bin/bash"
	},

![image](https://user-images.githubusercontent.com/51725820/81716490-4b3e4500-942e-11ea-8c4a-6d8dcc23502f.png)

**Comment by tonyeung** [comment]
@edgonmsft Hello! thanks for the quick reply. Yes it was in Remote. Looks like I have more reading to do to figure out the order! 😄
