### ISSUE TITLE
Can't edit root-owned files within the editor

### ISSUE THREAD

**Issue by lostintangent** [MicrosoftDocs/vsonline#491]
While investigating #486, I tried to open a root-owned file from the terminal and edit it with VS Code. Unfortunately, when I try to save the file, I get a dialog prompt indicating a permission issue, and there doesn't appear to be a way to "elevate". When working with VS Code locally, you can typically perform a "run as admin" to edit/save root-owned files, but the same doesn't appear to be possible in a Codespace. This might also be a limitation of VS Code desktop on Linux (I haven't checked), but macOS/Windows definitely let you elevate to save root/admin owned files.

**Steps to reproduce:**

1. Open a terminal within a Codespace
2. Run `code-insiders /etc/sysctl.conf` (or `code /etc/sysctl.conf`, depending on the VS Code web build you're using)
3. Simply add a space and try to save it
4. When you get the following dialog, attempt to hit the `Retry` button

![image](https://user-images.githubusercontent.com/116461/81715902-999f1400-942d-11ea-8e94-e2846e71e90c.png)

**Expected:** To be able to "elevate" and save the file somehow

**Actual:** Clicking the `Retry` button doesn't do anything, and so I had to resort to using `sudo vim /etc/sysctl.conf` in order to edit the file.

**Comment by jkeech** [comment]
@lostintangent you said this is in VS Code desktop on Linux, right? Which distro? I would expect this to only be a server-side issue though, independent of the client used to connect.

I've tried this in the web several weeks ago, and it worked at this time. Maybe something regressed, or something else is different. Are you using the default image or a custom image via a `devcontainer.json`?

**Comment by tashbaugh** [comment]
Using the default image via the web I can:

- update the file permission on sysctl.conf
- modify the file and add an entry to it
- save the file
- open the file again and see the modification made to the file.

In the case of #486, I can add the vm.max_map_count setting to the sysctl.conf file, but it does not seem to be applied to the kernel.

**Comment by jkeech** [comment]
@tashbaugh, I don't think you'll be able to update `vm.max_map_count` since that's the kernel level setting on the host, and it won't be reflected when just updating inside the container. That's a different issue that the one that @lostintangent is describing.

**Comment by tashbaugh** [comment]
> @tashbaugh, I don't think you'll be able to update `vm.max_map_count` since that's the kernel level setting on the host, and it won't be reflected when just updating inside the container. That's a different issue that the one that @lostintangent is describing.

@jkeech, correct it is a different issue, as detailed in #486. If you have any ideas on how to solve that problem I would appreciate your input on #486 

The point I was trying to make with my comment here is that, as you indicated, you can modify this file via the web and to let @lostintangent know that if while investigating #486 he was trying to set that value in sysctl.conf it was all for not.

**Comment by dmgardiner25** [comment]
@lostintangent I'm going to go ahead and close this as it seems to be an issue on VS Code's side. Check out https://github.com/microsoft/vscode-remote-release/issues/1688.

**Comment by lostintangent** [comment]
Sounds good. Thanks!
