### ISSUE TITLE
Is there a way I can change the theme of the zsh within the vscode online?

### ISSUE THREAD

**Issue by Brucius** [MicrosoftDocs/vsonline#496]

**Comment by jkeech** [comment]
@Brucius, you can create your Codespace with a dotfiles repo, which can be used to configure personalized settings, such as shell configuration, etc. You could include a `.zshrc` file with any customizations you want. More info is available at https://docs.microsoft.com/en-us/visualstudio/online/reference/personalizing.

**Comment by Brucius** [comment]
Thanks @jkeech. Closing this now
