### ISSUE TITLE
Could not find VSCode installation

### ISSUE THREAD

**Issue by NCC1701M** [MicrosoftDocs/vsonline#498]
When I try open my Codespace in VSCode, I get the message
> Could not find VSCode installation

![image](https://user-images.githubusercontent.com/7260053/81812233-2927ee00-9526-11ea-9bf5-aae177cd7c6f.png)

But VSCode is installed and the following extensions are enabled:

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-sqlite|ale|0.8.2
sqlformatter|bre|0.0.7
xml|Dot|2.5.0
gitlens|eam|10.2.1
beautify|Hoo|1.5.0
docomment|k--|0.1.9
csharp|ms-|1.21.18
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
powershell|ms-|2020.4.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.2167
createGUID|nwa|0.0.2
quicktype|qui|12.0.46
sass-indented|rob|1.5.1
css-auto-prefix|spo|0.1.7

Information about my System:
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jkeech** [comment]
@chkn, I think something regressed with the protocol handler detection in the web portal.

**Comment by NCC1701M** [comment]
What is the state of this issue?

**Comment by chkn** [comment]
@NCC1701M We are investigating and will post any updates here. Thanks for reporting this!

**Comment by chkn** [comment]
This should be fixed now. Thanks for your patience!

**Comment by NCC1701M** [comment]
> This should be fixed now. Thanks for your patience!

I can confirm the fix. Thanks
