### ISSUE TITLE
Self-hosted environments need to be restored after reboot

### ISSUE THREAD

**Issue by Chuxel** [MicrosoftDocs/vsonline#5]
While registering a self-hosted environment from VS Code works as expected, if the host is rebooted, the environment does not automatically reconnect to VS Online. The result is that, while the environment will show as available, it cannot be reached.  Trying to connect to it from either VS Code or VS Online's browser-based editor will fail Azure relay error in a notification.

```
Failed to connect to the remote extension host server (Error: Failed to connect to relay: ...
```

The only current workaround is to use the [VS Online: Restore Local Environment](https://review.docs.microsoft.com/en-us/visualstudio/online/resources/troubleshooting?branch=master#restore-a-self-hosted-environment) command after a restart.

**Comment by jkeech** [comment]
We just released some improvements that allow you to install the self-hosted agent as a service so that it can survive reboots. You shouldn't have to manually restore anymore. Give it a shot, and feel free to file a new issue if you run into any problems.
