### ISSUE TITLE
http request payload failed 

### ISSUE THREAD

**Issue by KennyChen0909** [MicrosoftDocs/vsonline#506]
I'm using Azure repo to create code space with code spaces extension on VS code.

However, when I select the repo and it returned the following message:

![image](https://user-images.githubusercontent.com/40878442/82036671-c5432800-96d3-11ea-986a-4953341c0bda.png)

But there's no detail message showed below. Any ideas?

**Comment by jkeech** [comment]
@KennyChen0909 this looks like an error with the latest extension release. @cmbrose is working on pushing out a fixed extension, but in the meantime you could try installing an older version of the extension.

**Comment by jkeech** [comment]
@KennyChen0909 a new extension version was just published to the marketplace. Can you confirm that it fixes this issue?

**Comment by KennyChen0909** [comment]
@jkeech Thanks, it fixed the issue. But I encounter another error when cloning the repo:
![image](https://user-images.githubusercontent.com/40878442/82176919-abd7f100-990a-11ea-8542-1cfb49417e73.png)

I selected SouthEast Asia for the plan.

**Comment by jkeech** [comment]
@KennyChen0909, thanks for confirming the original issue is fixed! I split out the new problem into a separate issue to track from there.
