### ISSUE TITLE
cannot login using an account with an alias

### ISSUE THREAD

**Issue by lucamorelli** [MicrosoftDocs/vsonline#507]
my @outlook.com account has an alias with my main email address as main address.
when I connect with the azure plugin, whatever name use in the login mask, the @outlook address is detected and used.
when I try to login with the codespaces plugin, the  non outlook address is selected and the plugin gives and error because the email address of the azure and codespaces plugins are differents, but point to the same account

**Comment by jkeech** [comment]
@jasongin, @cmbrose, we might need to make the email check more flexible a check additional claims in the token, or provide a warning saying they don't match and allowing the user to continue anyway.

@lucamorelli, we are working on switching to single sign on using the ARM/Azure login, so this issue is only temporary until that change happens. But hopefully we can provide you with a workaround in the meantime.

**Comment by cmbrose** [comment]
@lucamorelli we unfortunately don't have an immediate solution for supporting aliased accounts in the vs code extension, although we are currently working on SSO which will allow it like @jkeech mentioned.

In the meantime, our [portal](https://online.visualstudio.com/environments) does support these types of accounts so you can use that to create plans and codespaces.  Once created, you can then use the vs code client to access and use the codespace.

**Comment by lucamorelli** [comment]
Ok, thanks. I'll try that way.  Just a question. I don't remember how to connect to a my existing Vs online repo so i can work to an.existing project both singolo codespaces andare local clones

**Comment by cmbrose** [comment]
@lucamorelli sorry, I'm not fully understanding the question.  Are you trying to clone an Azure Dev Ops repo into a codespace?  If so, you can paste the full git clone url into the `Git Repository` textbox of the codespace creation pane in the portal.

**Comment by lucamorelli** [comment]
Hi, I tried twice, first with an angular app and second with an asp.net core solution, but in both cases gives me error while cloning

**Comment by cmbrose** [comment]
Since that issue isn't related to the email aliases, I've forked #528 to track it and will close this one
