### ISSUE TITLE
Cannot create more than 3 codespaces in 1 plan?

### ISSUE THREAD

**Issue by chunliu** [MicrosoftDocs/vsonline#508]
I have 3 codespaces in 1 plan. When I created the 4th, I hit the error: `You have exceeded the Codespace quota`. I have to remove an existing codespace to create a new one. 

Is there a quota for the Codespaces plan? Is it documented somewhere? I can't seem to find it with google. Is there a way to increase the quota?

**Comment by jkeech** [comment]
https://docs.microsoft.com/en-us/visualstudio/online/resources/faq#what-are-visual-studio-codespacess-quotas

>**What are Visual Studio Codespaces's quotas?**
Codespaces, by default, allows users to create 3 environments per plan, and 2 plans per subscription.

We are working on integrating with the Usage and Quotas section on the Subscription blade in the Azure portal, which will also allow making support requests to increase the quota.
