### ISSUE TITLE
Download large files

### ISSUE THREAD

**Issue by nbarkhina** [MicrosoftDocs/vsonline#509]
When trying to download a large file from the browser interface by doing right click -> download from the sidebar I get a "Failed - No file" error in chrome. The file I'm trying to download is a 140 megabyte zip. However smaller files download without issue. Does Visual Studio Online support large file downloads? How else could I download the file if not via the browser interface. I also tried using the Live Server VS Code Extension and that also was not able to download the file.

Thanks

**Comment by jkeech** [comment]
@nbarkhina, have you tried connecting from VS code on the desktop and performing the download from there? I'm not sure if you'll see different results.

@bpasero, are there any known file size limits on the browser-based file downloads?

**Comment by nbarkhina** [comment]
@jkeech yes it worked when I did it from VS Code on the desktop

**Comment by bpasero** [comment]
@jkeech VSCode has 2 strategies for downloading:
* up to 1 MB files are downloaded via blob URI (see https://github.com/microsoft/vscode/blob/4af9b3e29a2d23941cd70bd26366a394407d5403/src/vs/workbench/contrib/files/browser/fileActions.ts#L1099)
* larger files are downloaded by producing an anchor tag with download attribute

You are still seeing https://github.com/MicrosoftDocs/vsonline/issues/292 when files are large. Maybe you should consider to reopen that issue. It does not reproduce in our own local web version so I think it is related to using service workers.

**Comment by jkeech** [comment]
Thanks. I've reopened #292. We can track this issue over there and close this one.
