### ISSUE TITLE
my codespace does not resume

### ISSUE THREAD

**Issue by agocorona** [MicrosoftDocs/vsonline#514]
(My codespace does  not resume)
After two months of working fine, my environment haskelldev2 does not start since a day ago.  I tried many times. I have valuable commits still not pushed to my Github  repo.  Other test environment works fine.

**Comment by jkeech** [comment]
Hi @agocorona, sorry to hear that. Can you provide your environment Id (or the url in the browser when it’s on the loading page)? We will look into what is going on and try to recover it.

We have seen this once before if the disk usage fills up to the maximum size. Sometimes the container cannot restart if the disk is full. Is it possible that you have used all 64 GB of disk space?

**Comment by agocorona** [comment]
#jkeech  thanks a lot for your feedback.
It  should not have filled the disk. Maybe by some bug I don't know yet. 

The URL is:
https://online.visualstudio.com/environment/28660be8-34ee-455c-a499-787d922b3a4b

**Comment by legomushroom** [comment]
@agocorona could you try again and let us know if you are able to resume now. 

cc @edgonmsft

**Comment by agocorona** [comment]
It does resume, but the content has disappeared and it appears to be a blank codespace, with README only. I wanted to recover my content...

**Comment by edgonmsft** [comment]
@agocorona 
Hi, let us check the data in your storage account and get back to you.

**Comment by agocorona** [comment]
@edgonmsft  thanks a lot!

**Comment by legomushroom** [comment]
@agocorona can you try now? The files should be back.

**Comment by agocorona** [comment]
Seems that it does not resume now...

**Comment by edgonmsft** [comment]
Hi @agocorona!

Sorry for the delay, it appears that there was some filesystem corruption.

Can you validate now? 

By the way I noticed that this was an environment created a long time ago, we have made improvements since then to avoid this kind of issue but to get them you need to create a new environment. If possible I recommend you migrate to a new one.

Can you let me know if its working now?

**Comment by agocorona** [comment]
It    works. Thanks  a  lot

Sure. I just  want the code. I have  a new environment and I  will delete this as soon as I have the code out of it.  
You can close the issue.  Thanks  again.

**Comment by edgonmsft** [comment]
Great!
