### ISSUE TITLE
Sign-in loop for Chrome 81 on MacOS Mojave 10.14

### ISSUE THREAD

**Issue by gro1m** [MicrosoftDocs/vsonline#522]
Same as in https://github.com/MicrosoftDocs/vsonline/issues/362, but for:
Chrome 81 on macOS Mojave 10.14.

**Comment by klvnraju** [comment]
Thanks for reporting. We are looking into it and will get back to you shortly.

**Comment by legomushroom** [comment]
I was not able to repro in `Chrome 81`, `Catalina 10.15.4` @plisy are you using Mojave by chance?

**Comment by gro1m** [comment]
It is a colleague of mine that had the issue (therefore I can unfortunately not give you full details), but the hardware is 7 years old and he can apparently also not access the Microsoft Learning Websites. But he can still use the Azure Portal. As the problems are not VSO-only, I think we could close this issue.

**Comment by gro1m** [comment]
It is a colleague of mine that had the issue (therefore I can unfortunately not give you full details), but the hardware is 7 years old and he can apparently also not access the Microsoft Learning Websites. But he can still use the Azure Portal. As the problems are not VSO-only, I close the issue.
