### ISSUE TITLE
When i attempt to install Codespaces extention I receive error message.

### ISSUE THREAD

**Issue by sterlingssmith** [MicrosoftDocs/vsonline#524]
Connect to Codespace: Fetch workspace list request failed with status 404

**Comment by jkeech** [comment]
@sterlingssmith, can you provide some more context on the steps you took to get this error?

* Was this in the browser or on the desktop VS Code?
* Did it happen after the extension install?
* Did you do any sort of sign in first?
* Are you using VS Codespaces or Codespaces in GitHub?
* If Codespaces in GitHub, are you in the beta?

It looks like this error would only ever happen for Codespaces in GitHub.

**Comment by sterlingssmith** [comment]
Sure, @jkeech-  
- This occurs on the desktop version of VS Code.
- It happened after the extension install
- I did authenticate via github
- I'm using VS Codespaces (but would prefer to use Codespaces in Github) just sayin' :)
- I've applied to Beta, awaiting response.

**Comment by sterlingssmith** [comment]
@jkeech- Steps to test:
1. Open VSCode
2. Open Command Palette
3. Click on 'Connect to Codespaces'
4. Error Message model pops up in bottom right hand corner stating: Connect to Codespace: Fetch workspace list request failed with status 404

**Additional info:** I've uninstalled extension and re-installed as well as uninstalled VS Code and reinstalled. I'm able to login to web version of VS Code via onlin.vscode.com and spin up an instance (so i know what it should look like / how it should function) but am unable to replicate success on my desktop

Thanks in advance!

**Comment by jkeech** [comment]
@sterlingssmith, thanks for the info. For VS Codespaces, ensure that the `vsonline.accountProvider` setting is set to `Microsoft`. Based on the error message, I suspect it is set to `GitHub` currently. The `GitHub` setting will only work after you are accepted to the Codespaces beta in GitHub.

When the account provider setting is set to `Microsoft`, it will show your VS Codespaces (the same ones that you see on https://online.visualstudio.com). When the provider is set to `GitHub`, you'll see your Codespaces in GitHub, which are visible at https://github.com/codespaces after you are accepted into the beta.

Let me know if that fixes it for you 😃

**Comment by sterlingssmith** [comment]
That did it! Thanks my man.

**Comment by jkeech** [comment]
Glad to hear! I'm going to close this issue, but please open up another one if you hit any other issues.
