### ISSUE TITLE
Multi-root workspaces not working.

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#525]
Reported by @CarlKinghorn at https://twitter.com/CarlKinghorn/status/1263263547112542211?s=20

---

Steps to reproduce:
- new codespace
- add 'src' folder
- add 'Project1' sub folder
- add 'Project2' sub folder
- Right-click "Add folder to workspace" and select the 'Project1' folder
- Browser reloads and "No Folder Opened" is in the explorer pane

**Comment by jkeech** [comment]
Closing as a duplicate of #449
