### ISSUE TITLE
'Create Environment' UX — Errors should not shift UI around

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#53]
**repo**
1. Go to create a new environment
1. In the `Git repository` section, start typing

**Bug**
Everything gets shifted around as you type because the error pops in and out

![Nov-04-2019 14-03-42](https://user-images.githubusercontent.com/12821956/68162085-19db3e80-ff0c-11e9-8fba-98ac1569da31.gif)

**Comment by wy1024** [comment]
Hi Matt, thanks for reporting. We went through some design discussions and updated the create environment experience. The error message no longer frequently pops up. We also added a top-level error message for anything else.
