### ISSUE TITLE
VSCode git controls not compatible with installed git

### ISSUE THREAD

**Issue by ryuuji3** [MicrosoftDocs/vsonline#539]
When trying to use "Stash" command in VSCode UI, git fails to stash because the git doesn't have support for `git stash push`

Git logs:
```
> git stash push
usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
		       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear
```

Installed git version is 2.11.0.

I've considered installing from source, as there are no packages available for the installed linux distro.

``` cat /proc/version

Linux version 5.3.0-1020-azure (buildd@lgw01-amd64-055) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020
```

Is there a good way to update git on the codespace?
I'm using a desktop VSCode client if that makes a difference.

**Comment by jkeech** [comment]
@dmgardiner25, we should update the version of `git` that ships with the base image.

@ryuuji3, you could always install from source or use a custom image that has a newer version of git, but the right fix is for us to just update to the latest version of git in the base image so you don't have to make any other changes. When we make updates to the base image, you will have to recreate the Codespace to apply the latest updates (that leaves you in full control of the Codespace contents after it is created).

Connecting from the desktop vs the web should not make a difference in this case -- it's only based on which version of git is installed inside the container that is running the Codespace.

**Comment by ryuuji3** [comment]
Thank you! For now to avoid having to rebuild since I have some secrets I had to import, I will opt to build from source.

**Comment by dmgardiner25** [comment]
@ryuuji3 The fix for this has been deployed and should be reflected in any new codespace you create!
