### ISSUE TITLE
Add more default tiers

### ISSUE THREAD

**Issue by shawnfunke** [MicrosoftDocs/vsonline#54]
Currently there are only 2 tiers, the standard and premium tier it would be nice if there where more options as I don't think all environments need at least 4 Cores and 8GB RAM.

My suggestion is to add more tiers such as a instance with 2 Cores and 4GB RAM or even a instance with 1 Core and 2 GB RAM. This would make it more viable for using it to quickly review pull requests or make other minor code changes that don't require many computing resources.

**Comment by lostintangent** [comment]
@shawnfunke Thanks for the feedback! We've been discussing adding a "Basic" tier, that would provide 2 cores and 4 GB RAM, for the exact reason you mentioned. For certain scenarios, we believe this could be totally sufficient, and so we'd love to hear more feedback from the community 👍

**Comment by bnb** [comment]
For a bunch of tasks I do daily, 2 cores and 4gb of RAM wouldn't work for a personal machine *but* would absolutely be sufficient as a dedicated VM for my development time. Additionally, I often run workshops or set up environments for others that it would also be sufficient for.

**Comment by carterbryden** [comment]
Personally, I would strongly prefer to use one instance per project, and use dozens of instances rather than a few overpowered instances that share multiple projects. Then I'm not potentially polluting one project environment with another. 

1 core/2gb ram would be plenty for almost every project I've ever worked on, though I could understand it needing more due to VSO's resource reqs.

**Comment by bnb** [comment]
@carterbryden what kind of projects have you typically worked on?

**Comment by abuchholtzau** [comment]
@carterbryden and @bnb it'd be awesome if you could list a few of the scenarios or types of projects you expect to use 1 core/2gb machines for. I'm coming up with a list of scenarios to test on a more "basic" environment and ensure that level of power works for key use cases :)

**Comment by bnb** [comment]
Working on https://github.com/cutenode/1x.engineer, working on VS Code extensions, building a node.js module or CLI (for example: https://github.com/cutenode/good-first-issue or https://github.com/cutenode/libgfi)

**Comment by dalemartyn** [comment]
I'd potentially use it for building WordPress sites / themes, including build scripts with gulp/rollup/sass/babel.

**Comment by carterbryden** [comment]
@bnb Mainly web development, which could range from Wordpress or static sites to NodeJS, Elixir, PHP/Laravel projects, Go, Ruby. I've had projects with all of those. 

I've run many of these projects on $5 and $10 digital ocean droplets with 512mb to 2gb of memory with no resource issues so it seems like it should be no problem to run my solo dev env under those conditions, unless VSO uses up a lot of resources in general. Most of these languages these days are pretty efficient and can do a lot with a little.

**Comment by lostintangent** [comment]
FYI, we’re in the process of adding a new “basic” SKU, that includes 2 cores and 4 GB of RAM. After doing a bunch of testing, we believe this will provide a great developer experience, and allow folks to have more smaller environments, as opposed to one large one. Stay tuned for updates here soon!

**Comment by srivatsn** [comment]
Basic sku has been released.
