### ISSUE TITLE
Connect to Visual Studio Codespaces(private preview only) option is missing in Visual Studio 2019 Community Preview

### ISSUE THREAD

**Issue by subhankars** [MicrosoftDocs/vsonline#542]
I have signed up for Codespaces private preview and received a confirmation mail as below -

![image](https://user-images.githubusercontent.com/17920161/83016551-c4998280-a03f-11ea-8ad2-5b21a96f77af.png)

I followed the instruction as written in https://docs.microsoft.com/en-us/visualstudio/online/quickstarts/vs

When I try to enable Connect to Visual Studio Codespaces(private preview only) option from Preview Feature, I do not see the option 

![image](https://user-images.githubusercontent.com/17920161/83017216-e3e4df80-a040-11ea-8bed-f260ea8fe68e.png)

I'm blocked at 1.Install >> 5. Enable codespace section

I'm using Visual Studio 2019 Community Preview 16.7.0 Preview 1

I'm not sure whether its a CodeSpace Private preview activation issue or its a Visual Studio version issue.

**Comment by vennim** [comment]
I have the same issue. Any update on this?

**Comment by snickler** [comment]
Same on both Community and Enterprise.

**Comment by acangialosi** [comment]
There are a couple bugs we need to wrap before we could publish the preview feature for Codespaces. The option to enable connecting to a Codespace in Visual Studio 2019 will be in 16.7 preview 2 that will release in a few days. 
You also need access to create Windows Codespaces to create and work with Codespaces in Visual Studio 2019. We're slowly starting to add users to private preview of Windows Codespaces on the service side. We'll send you a confirmation email once your account has been enabled on the service side.

**Comment by subhankars** [comment]
@jkeech @acangialosi I can create a billing plan from the Connect to a CodeSpace window, but can't select the created one to proceed. See screenshot -
![image](https://user-images.githubusercontent.com/17920161/86514042-92442780-be2c-11ea-9668-5c77362e7569.png)

Question - How do I know that I have CodeSpaces Private preview request is granted by Microsoft

**Comment by jkeech** [comment]
@subhankars, sorry for the confusion. You are not in the private preview yet. You should receive an email once you are in the private preview, and the message under the "Codespaces" section of that UI will change. We are still working on ramping up to more users as we address early feedback and iterate before opening it up for everyone. Thanks for your patience!
