### ISSUE TITLE
Add CODESPACES environment variable to all containers to detect when running in a Codespace

### ISSUE THREAD

**Issue by jkeech** [MicrosoftDocs/vsonline#545]
Sometimes tools need to have special behavior when running in a Codespace vs running locally, so we should provide an easy way for any tool or VS Code extension to determine when it is running in a Codespace.

To do this, we should add an environment variable `CODESPACES=true` to the main container that is spun up, both for the default container and for custom containers.

**Comment by nikmd23** [comment]
Let me yes-and this. 😊

A `CODESPACES_INSTANCE_TYPE=[Basic|Standard|Premium|GPU|SelfHost]` (or some better name) would be useful as well. Users have indicated a desire to alter their dev environment in various ways (use emulated hardware, change out an underlying library, etc) depending on the place the Codespace is running.

**Comment by jkeech** [comment]
> A `CODESPACES_INSTANCE_TYPE=[Basic|Standard|Premium|GPU|SelfHost]` (or some better name) would be useful as well.

If we were to do this, it would have to be done slightly differently, since it can change over the lifetime of the Codespace. For the main `CODESPACES=true` variable, I was planning on having `CODESPACES` be at the container level, but you can't change that after the container is created. The benefit is that it's visible to all processes in the container, even those not tied to the VS Code Server process tree (which is helpful for some custom container scenarios with other apps/databases/etc running).

If we were to add a `CODESPACES_INSTANCE_TYPE`, it would need to be done at the VS Code Server process level inside the container. That probably works for most purposes. It would cover VS Code extensions and any terminal instances in VS Code, but it wouldn't be visible to standalone processes launched in the container outside of the context of VS Code.

Also note that for self-hosted, we do not currently set any environment variables or tweak the machine/environment config in any way beyond installing the agent. We just provide connectivity from your existing environment that you've configured however you want. So we would not set the `CODESPACES` or `CODESPACES_INSTANCE_TYPE` variable for self-hosted Codespaces in the current design.

**Comment by lostintangent** [comment]
In order to alter their behavior based on SKU, I'd imagine that it would be more reliable for tools to feature-detect hardware directly, as opposed to relying on our SKU definitions to do it (e.g. you can call Linux commands to detect a CPU, core count, RAM). So it feels like it might actually be better if we have recommendation on how to do that (e.g. a doc that shows the shell commands), but not initially encourage a dependency on our SKUs until we know folks need that. For example, I want to be able to add a new SKU and have tools "light up" based on the hardware of that SKU automatically meeting their needs or supporting an enhanced behavior.

**Comment by jcansdale** [comment]
It would be great if there was a way to detect the WebUI as well. This is the hack I'm currently using. I'm not sure how relyable it is. 🤔 

https://github.com/jcansdale/ghvs/pull/39/files#diff-c8371ce388541ae49aa0fc39c61178a6R67

**Comment by jkeech** [comment]
> It would be great if there was a way to detect the WebUI as well. This is the hack I'm currently using. I'm not sure how relyable it is. 🤔

That's out of scope for this issue, because it's dependent on the client, not the Codespace. The Codespace exists independent of the connected client, and in fact two different clients can be connected simultaneously. So from your tool's perspective, if the tool is run outside of the context of VS Code editor, it doesn't know anything about which type of client invoked it.

**Comment by jcansdale** [comment]
@jkeech ,

> So from your tool's perspective, if the tool is run outside of the context of VS Code editor, it doesn't know anything about which type of client invoked it.

Isn't a terminal in a VS Code tool window, someone associated with that instance?

I'm interested to know what the `CLOUDENV_SERVICE_ENDPOINT` envvar is used for? Isn't this different between webui and extension instances? It appears to be `https://online.visualstudio.com/api/v1/environments` when using the extension and `https://online.visualstudio.com/api/v1` when using the webui.

**Comment by rrelyea** [comment]
Nuget team was looking for something similar.
Some discussion here:

https://teams.microsoft.com/l/message/19:ed8d3a2848564585a6c133347df93a49@thread.skype/1592254953790?groupId=b9ce1a3e-cc2e-4374-890b-653118638c01

Debate about env bar name: codespaces vs nuget_do_not_show_ui, or the like

**Comment by jkeech** [comment]
Deployed :rocket:
