### ISSUE TITLE
Self-hosted Azure hosted VM Start/Deallocate

### ISSUE THREAD

**Issue by 35359595** [MicrosoftDocs/vsonline#554]
Include functionality for Azure hosted under same subscription but "self-hosted" Codespace to be:
- Started on connect if shutdown/deallocated;
- Deallocate on Suspend of current Codespace;

PS: Sorry if doubled of planned feature - didn't found anything relevant.

**Comment by jkeech** [comment]
Hi @35359595, we do not have any plans to manage the lifecycle of self-hosted Codespaces. If you do not want to worry about the lifecycle management yourself, our recommendation is to use the Cloud-hosted Codespaces where we manage the VM for you.

Self-hosted gives you full control of the underlying VM/hardware, and the Codespaces agent merely provides connectivity from the machine you manage to make it connectable from the browser or a remote machine via VS Code.

**Comment by 35359595** [comment]
I don't have option to create codespace based on Windows machine...
And that's what I need for 'native' apps for Windows. Is this limitation of my subscription or Win machines are not [yet] available?

**Comment by jkeech** [comment]
Cloud-hosted Windows Codespaces are not broadly available yet, but it is in private preview. You can sign up here: https://visualstudio.microsoft.com/vs/private-preview/

For now you can use self-hosted on Windows, but the service will not manage the lifecycle of the VM. Hope that helps!

**Comment by 35359595** [comment]
I still think that this feature will be useful for self-hosted VMs, which requires some specific setup. For example AD domain/forest presence in mixed cloud enterprice.

**Comment by jkeech** [comment]
We will have support for custom configurations of the Windows VM for the cloud-hosted Codespaces. I'd love to see what we can do there to support whatever requirements your organization has, although that would probably be best in a separate issue.

I'm going to go ahead and close out this issue since lifecycle management of self-hosted Codespaces is not on our roadmap.
