### ISSUE TITLE
Documentation: Unable to find information on setting up URL for badge

### ISSUE THREAD

**Issue by jobullen** [MicrosoftDocs/vsonline#56]
In the demo there was a badge on the readme.md page for the repo, how is this generated/configured?

**Comment by jkeech** [comment]
More information is provided in #37. We are working on getting formal documentation added for this feature. Thanks!

**Comment by lostintangent** [comment]
Closing this as a duplicate of #37, which we're using to track API enhancements as well as documentation of the existing deep link URL. Please re-open this if you think they're different issues. Thanks!
