### ISSUE TITLE
Add note that ADO can be used as connected repository

### ISSUE THREAD

**Issue by profexorgeek** [MicrosoftDocs/vsonline#563]
@abuchholtzau and @gregvanl  - Oliver Doerr recommended that we add a note to this page:

> https://github.com/MicrosoftDocs/vsonline/blob/master/vs-online/reference/repository.md

...indicating that it is possible to use Azure DevOps as a connected Repository.

**Comment by abuchholtzau** [comment]
Yup we've been meaning to add that! I believe Nik created an issue for it a couple of weeks ago as well.

**Comment by gregvanl** [comment]
Looks like duplicate of https://github.com/MicrosoftDocs/vsonline/issues/494

**Comment by OliCSADoerr** [comment]
Great to see the light speed response! Looking forward to the updated documentation.

**Comment by gregvanl** [comment]
Closing as duplicate
