### ISSUE TITLE
Question: setup private npm and nuget feeds

### ISSUE THREAD

**Issue by elonmallin** [MicrosoftDocs/vsonline#564]
Hi,

Is there some neat way to setup and authenticate private npm, nuget and other common feeds from Azure or elsewhere (but mainly npm and nuget in Azure ;))?

Really psyched about the impact on contributions to open source however would like to see some docs and how-tos on setting up common scenarios like mentioned above.

For example in a company settings where every user generates a private token to access the npm feed and puts it on their localhost, how can this be solved easily with `.devcontainer`? Maybe there already is something?

**Comment by jkeech** [comment]
We are working on #50, which will allow you to setup some secrets (PATs, connection strings, etc) that can be injected into Codespaces at creation/resume time. At first it will only support environment variables, and files (.npmrc, etc) will be added later. Once the environment variable support is in place though, you could have a `postCreateCommand` that reads the variable and modifies whatever files on disk that you need.

**Comment by jkeech** [comment]
Secrets support is now available via #50. We'd love for you to give it a shot and see if it solves your need for setting up nuget/npm credentials. You should be able to set a PAT as an env variable in the secrets settings, and then you can have a `postCreateCommand` in devcontainer.json transform your nuget config or npmrc using the PAT.

**Comment by elonmallin** [comment]
Nice, that should work. I've already switched from having a `%usrprofile%/.npmrc` with the credentials to having only the projects `.npmrc` with `$NPM_TOKEN` that is replaced by an env var by npm automatically.

Maybe it would be nice with some docs on this because even though it's possible you still have to figure quite some stuff out. Would probably be helpful to have a `.npmrc` file in the sample repos for nodejs projects too that has this setup (except all commented out, just as an example).
