### ISSUE TITLE
"(refusing to allow an OAuth App to create or update workflow `.github/workflows/rc-docker-web.yaml` without `workflow` scope)"

### ISSUE THREAD

**Issue by mikemol** [MicrosoftDocs/vsonline#568]
Originally filed over at https://github.com/microsoft/vscode/issues/99546 ... here's the filled out template for there.

- VSCode Version: 1.45.1 (Commit ID 5763d909d5f12fe19f215cbfdd29a91c0fa9208a )
- OS Version: Visual Studio Codespaces. `/etc/os-release` reads: Debian GNU/Linux 9 (stretch)

Steps to Reproduce:

1. Open Visual Studio Codespaces workspace tied to Github repository
2. Create a GitHub Actions workflow control file, commit
3. `git push` in terminal

Observed result:

```
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (8/8), 2.51 KiB | 0 bytes/s, done.
Total 8 (delta 0), reused 0 (delta 0)
To https://github.com/rosettacode/docker-web
 ! [remote rejected] build/workflow -> build/workflow (refusing to allow an OAuth App to create or update workflow `.github/workflows/rc-docker-web.yaml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/rosettacode/docker-web
```

Does this issue occur when all extensions are disabled?: Visual Studio Codespaces; I don't have a way to check. `Report Issue` brings me here. _(**Note:** "here" was in reference to Visual Studio Code's repository. I'll file a separate issue around sending the user to the correct issue tracker.)_

**Comment by jkeech** [comment]
Hi @mikemol, it looks like we just need to update the OAuth app to increase the requested scopes to include the `workflow` scope. This is not a scenario we have considered/tried before, but I don't see why we couldn't add it. cc @legomushroom

**Comment by jcansdale** [comment]
We needed to quickly fix this in GitHub for VS, see https://github.com/github/VisualStudio/pull/2462.

Not having the `workflow` scope can cause a world of pain. As well as not being able to touch workflow files, you can't push workflow changes that have been merged from master. Users can easily end up with branches that they can't push. 😨 

I just wanted to flag the severity of this problem.

**Comment by legomushroom** [comment]
PR is on auto-complete, should be deployed with the next portal release. cc @jkeech

**Comment by mikemol** [comment]
What are the timings of portal releases?

**Comment by jkeech** [comment]
@mikemol, we deploy weekly, with staged rollouts for different regions, so by the end of the week this fix should be deployed globally since it will be included in this week's deployment.

**Comment by paolosalvatori** [comment]
I'm having this issue in Visual Studio Code and it's a huge problem. Are you planning to fix this problem soon?

**Comment by jcansdale** [comment]
@paolosalvatori,

>  I also tried with Microsoft Visual Studio Enterprise 2019, Version 16.6.2, same outcome. I tried to re-login to GitHub and nothing has changed.

Make sure you're using the the latest version of GitHub for VS. We've had a problem with the auto-update recently. You might need to trigger it using the Extension Manager. You'll then need to re-login. Sorry about the inconvenience!

**Comment by jkeech** [comment]
@paolosalvatori, this issue is specifically about the web client. Desktop clients use different auth flows. Please file a new issue for the desktop VS Code issue you are seeing. One question I have for the new issue: are you only seeing this when using Codespaces or directly in VS Code outside of Codespaces as well? If you are seeing it outside of Codespaces, it is likely something related to VS Code or permissions on your overall Git credentials that are stored locally in your credential manager -- they might not have the right scopes/permissions.

**Comment by jkeech** [comment]
The fix for this issue has been deployed to all regions 🚀
