### ISSUE TITLE
Will a containerized (docker) version be released?

### ISSUE THREAD

**Issue by jgbradley1** [MicrosoftDocs/vsonline#58]
Very cool work. I've been following and contributing to other open source projects like [Eclipse Theia](https://github.com/eclipse-theia/theia) and the [work](https://github.com/cdr/code-server) that Coder.com has done in attempting to mimic this type of product. Are there any plans to release a docker image so VS Code can be deployed on private infrastructure outside of Azure?

Or generally speaking, will the code for this be open sourced for others to configure and deploy in their own offline environments?

**Comment by luqiang360** [comment]
I think there should have many people do really want to deploy the vsonline on their own infrastructure, just like what coder-sever does.

**Comment by lostintangent** [comment]
Out of curiosity: have y'all seen the [self-hosted environments](https://docs.microsoft.com/en-us/visualstudio/online/how-to/vscode#self-hosted) support? It would be great to know if that would be sufficient for your use cases. Additionally, we plan to support registering "headless" environments very soon, and we're tracking that work via #66.

**Comment by BirkhoffLee** [comment]
@lostintangent That is absolutely a great news. Thank you.

**Comment by BirkhoffLee** [comment]
It’s #69, by the way

**Comment by BirkhoffLee** [comment]
It’s #69, by the way

**Comment by taiyosogawa** [comment]
@jgbradley1 thanks for the feedback! It sounds like you have some good insight regarding cloud IDEs. To consolidate and organize our feature requests, we would love to continue the conversation on #69.
