### ISSUE TITLE
Azure subscription not detected and cannot be associated when trying to use 'Visual Studio Codespaces'

### ISSUE THREAD

**Issue by xinyu91xyz** [MicrosoftDocs/vsonline#584]
Hello,

I was trying to follow experiment instructions (https://docs.microsoft.com/en-us/learn/modules/detect-objects-images-custom-vision/3-create-object-detection-solution)
to experiment Azure AI computer vision services. 

I signed up a free Azure subscription and was trying to use 'Visual Studio Codespaces' (https://online.visualstudio.com/environments/plan?showCreateEnvironmentPanel=true&redirectUrl=%3Fname%3Dai-fundamentals%26repo%3DMicrosoftDocs%252Fai-fundamentals) as instructed in the documentation link above. 

However, even though I signed in to my Azure account, Visual Studio Codespaces won't let me create a new billing plan to get started using it, simply because it cannot detect the Azure subscription associated with my Azure account. See screenshot attached below - the subscription dropdown was grayed out and it always asks me to creat a new free Azure account even though I've already signed in to the free account I created.

Could anyone provide some insights regarding how I can resolve this issue and use Visual Studio Codespaces with my free trial Azure subscription? Thanks!

<img width="1274" alt="Screen Shot 2020-06-15 at 2 25 34 PM" src="https://user-images.githubusercontent.com/7937018/84720523-193f6780-af33-11ea-82cc-0cfbce1239d5.png">

**Comment by LaurentLesle** [comment]
I have the same issue and I think it is related to my account being connected to multiple Azure AD tenants. There is no options to select the Directory tenant to target.

**Comment by xinyu91xyz** [comment]
> I have the same issue and I think it is related to my account being connected to multiple Azure AD tenants. There is no options to select the Directory tenant to target.

Agreed with your thinking. I have 2 directory under my account, and the trial subscription was under the default directory, but it always selects the other directory by default and not allowing me to select the default directory.

**Comment by jkeech** [comment]
This looks like the same issue as #39. We are actively working on supporting this scenario. I'm going to close this issue so we can track in #39. Thanks!
