### ISSUE TITLE
Quickstart sample called vsonline-quickstart

### ISSUE THREAD

**Issue by gregvanl** [MicrosoftDocs/vsonline#586]
The browser and VS Code quickstarts use the https://github.com/microsoft/vsonline-quickstart sample which still references VS Online.

Updating the sample itself doesn't look too bad:
"Visual Studio Online" - 2 instances
"VS Online" - 7 instances, mostly README but also .devcontainers.json and server.js response
"vsonline" - none

Remote Explorer section in README might need to be updated (is view still called Environment Details?)

**Comment by abuchholtzau** [comment]
@nikmd23 you seem to be the owner on this repo. Do you want to add me/Greg as contributors so we can edit it?
Also we should probably rename this the vsonline-quickstart repo?

**Comment by gregvanl** [comment]
@abuchholtzau You mean rename the repo to vscodespace-quickstart?
I'm happy to update the sample since it is tightly couple to the doc quickstarts.

**Comment by nikmd23** [comment]
I've made you both admins of that quickstart repo. 😏

**Comment by gregvanl** [comment]
@nikmd23 Thanks. I've updated the README and other files to use "Codespaces".

**Comment by gregvanl** [comment]
@nikmd23 @abuchholtzau Any reservations with me renaming the vsoneline-quickstart repo to 'vscodespaces-quickstart' today and updating the Codespaces quickstart docs to match the new repo name?
I believe GitHub handles redirects in case anyone has a bookmark to the repo.

**Comment by abuchholtzau** [comment]
None from me! I say go for it! :D GH handles the redirects really well for a renaming so no concerns there.

**Comment by gregvanl** [comment]
Renamed repo https://github.com/microsoft/vscodespaces-quickstart

**Comment by gregvanl** [comment]
Update README (Codespace Details panel, add macOS keybinding) with https://github.com/microsoft/vscodespaces-quickstart/commit/dce1ce83471822fcf0c06292497845847965aaec
