### ISSUE TITLE
EnvironmentProvider found no cached tokens

### ISSUE THREAD

**Issue by mrozekma** [MicrosoftDocs/vsonline#599]
I'm able to connect to my self-hosted codespaces through a browser, but any attempt to connect from vscode pops up an error tooltip: "EnvironmentProvider found no cached tokens".

I exported the Codespaces logs and found this:

```
2020-06-19 05:03:33.422 EnvironmentInfo E] Failed to fetch environments
EnvironmentProvider found no cached tokens
Error: EnvironmentProvider found no cached tokens
    at t.VsoEnvironmentsApi.getTokenOrThrow (/home/mrozekma/.vscode/extensions/ms-vsonline.vsonline-1.0.2361/src/partners/vso/vsoEnvironmentsApi.ts:349:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at t.VsoEnvironmentsApi.getEnvironmentList (/home/mrozekma/.vscode/extensions/ms-vsonline.vsonline-1.0.2361/src/partners/vso/vsoEnvironmentsApi.ts:250:15)
    at updateEnvironmentsInfo (/home/mrozekma/.vscode/extensions/ms-vsonline.vsonline-1.0.2361/src/EnvironmentInfo.ts:62:22)
```

**Comment by osortega** [comment]
Hello, thanks for reporting this.
Are you seeing this particular issue when clicking Open in VS Code button in the browser?

If so, this is a known issue that we are currently working on. For now, a workaround is signing out and sign back in to Codespaces extension on VS Code.

**Comment by mrozekma** [comment]
No, this is starting from within VS Code; I sign in and see the list of available spaces in the Codespaces remote connections panel, and when I double-click one it opens a new window and I get that error in a tooltip. So far I've been unable to connect to a Codespace from within a desktop VS Code session, I've been using the web-based version instead.

**Comment by cmbrose** [comment]
@mrozekma I'm taking a look at this, but having trouble reproing.  Can you provide some more details:

- What OS are you on?
- What vscode version?
- What Codespaces extension version?
- Does this also repro for you when trying to connect to a non-self-hosted codespace?

**Comment by mrozekma** [comment]
VSCode: 1.45.1 (5763d909)
Codespaces: 1.0.2390
OS: Linux x64 4.19.113-08528-g5803a1c7e9f9

Normally I'm on a Pixelbook running ChromeOS, with VSCode running in a Debian 9 container, which I realize is an uncommon configuration. I just tried on a Windows PC and everything is fine. Now that I'm comparing with Windows I realize that Codespaces remembers my session once I login once. On the Pixelbook I have to login every time I open VSCode, and when it opens a new window to make the remote connection and fails, if I check the Codespaces tab it's logged out again, so I think that's the cause of the error. I'm not sure where my login info is supposed to be stored under Linux, but if it depends on another service it's possible I don't have it running.

**Comment by cmbrose** [comment]
Thanks @mrozekma!  Since it's working on Windows, it sounds like there's something wrong with how we cache credentials on Linux.  I'll get a Linux environment set up and try a repro there.

**Comment by cmbrose** [comment]
@mrozekma I was able to repro this in a Debian VM and it looks like it's fixed by setting up a keyring:

- `sudo apt install gnome-keyring`
- You should be prompted to set up a password for a new keyring
- Reboot (maybe not needed, but for good measure :))
- Open vscode, sign back into Codespaces
- Connect to a Codespace

FWIW these steps worked for me for a brand new VM - I'm not sure what will happen if there is already a keyring set up (although it seems there isn't one)

**Comment by mrozekma** [comment]
@cmbrose Yep, that fixed it. No need to reboot, and I didn't get prompted to make a keyring password until first use (when I logged into Codespaces and VSCode tried to save my credentials). Possibly VSCode should popup a warning about the failure to save credentials if no keyring is available, but that's up to you all. Thanks very much for the help
