### ISSUE TITLE
Codespaces hate the name, Visual Studio Online sounds so much better

### ISSUE THREAD

**Issue by morgzz** [MicrosoftDocs/vsonline#603]
Please change the product name back to Visual Studio Online.

**Comment by abuchholtzau** [comment]
Hi there! Thanks for the feedback.

Naming always seems to be one of the hardest parts of a product. While we appreciate your preference for the old name, our research indicated that it was confusing for many other users while Codespaces worked well in terms of clarifying the value of the service. You can learn more in our [blog](https://devblogs.microsoft.com/visualstudio/introducing-visual-studio-codespaces/#new-name).

We'll close this suggestion for now but we encourage you and others to re-open if you feel strongly about it.
