### ISSUE TITLE
Cannot login from Safari

### ISSUE THREAD

**Issue by ztolley** [MicrosoftDocs/vsonline#614]
I am unable to use visual studio online via Safari on iPad and Desktop Safari.

To reproduce:
1. Visit online.visualstudio.com
2. Select Get Started
3. Select Sign In
4. Sign in with account

The app then returns to visual studio codespaces and says
`Login failed due to an unexpected error. Please log out and try again`

If I connect desktop Safari dev tools I can see I get a 404 for workbench.web.api.nls.js.map and 401 for keychain-keys

Tried on an iPad and also same issue from iPad simulator. Reset the data on the iPad, no change. Tried the same from Desktop safari and same issue.

Am able to sign in from Edge browser but need to use Safari on iPad.

**Comment by DAddYE** [comment]
Same, I can login from ipad Safari but not macos safari.

**Comment by ztolley** [comment]
Duplicate of #607
