### ISSUE TITLE
Set environment by file config

### ISSUE THREAD

**Issue by renatoassis01** [MicrosoftDocs/vsonline#62]
set environment per file (yaml, toml, ..) at the root of the repository.
ex: 
plan, region, ...
keyboard layout (en_US, pt_BR, ...)
list of extensions to install.
initial commands to execute after and before.

**Comment by plisy** [comment]
You can configure the environment itself using `devcontainer.json` file ([more information here](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring)). This way, you are able to specify for example a list of extensions to be installed and post install command(s).

For personalization we support dotfiles repos ([more information here](https://docs.microsoft.com/en-us/visualstudio/online/reference/personalizing)). This would allow you to specify for example the keyboard layour.

You can specify plan (which is tied to a region) in a deep link for environment creation and put that deep link as a button in repo readme file.
This link could look like this

`https://online.visualstudio.com/environments/new?plan=vso-plan-westus2&repo=microsoft%2Fvsonline-quickstart&name=vsonline-quickstart`

**Comment by renatoassis01** [comment]
Yess, that's exactly what I was wanting! Thank!

**Comment by lostintangent** [comment]
@renatoassis01 Awesome! I'm going to close this as resolved then, but please feel free to re-open this issue 👍
