### ISSUE TITLE
Can I update codespace after updating base image in .devcontainer.json?

### ISSUE THREAD

**Issue by smallhaes** [MicrosoftDocs/vsonline#621]
I could create the customized codespace quickly with .devcontainer.json. It's exciting.
However, can I update my codespace after updateing the base image used in .devcontainer.json ? I don't want to create a new codespace again

**Comment by abuchholtzau** [comment]
Hi there!

Closing this as its a duplicate of Issue #51, which covers refreshing a Codespace when the .devcontainer changes.

Thanks for your feedback!
