### ISSUE TITLE
Exceeding Codespace quota

### ISSUE THREAD

**Issue by Blickensdoerfer-J** [MicrosoftDocs/vsonline#638]
In my visual studio codespaces i have two plans. One with two Codespaces and one with zero. If i try to create a new Codespace i get a out of quota error. This happens in both plans.
![outOfquota](https://user-images.githubusercontent.com/67747781/86370613-45235280-bc80-11ea-9d67-fd87e7a2e540.png)

Furthermore i can only open one codespace at a time. If i try to open my second codespace i get an erro as well.
![OOQ](https://user-images.githubusercontent.com/67747781/86370841-7ef45900-bc80-11ea-8f3f-8840b15350b4.png)

**Comment by cmbrose** [comment]
Hi @Blickensdoerfer-J - are you using a trial Azure subscription?  Trial subscriptions are only allowed to have one active codespace at a time across all plans.  Additionally, they aren't allowed to create Premium Linux SKU codespaces.

**Comment by Blickensdoerfer-J** [comment]
Okay thanks. I did not know that. Then the behavior is to be expected. I think in the beginning i could have more active at the same time.

**Comment by cmbrose** [comment]
Thanks for confirming - I'll go ahead and close this one up then
