### ISSUE TITLE
My codespaces cannot be resumed

### ISSUE THREAD

**Issue by tszkanlo** [MicrosoftDocs/vsonline#647]
My codespaces is https://online.visualstudio.com/environment/177aefca-5f28-40f8-89b6-6f4bfc6bf15d
I was using it yesterday and today it cannot be resumed. Please help on the issue and thank you.

**Comment by osortega** [comment]
Hello @tszkanlo 
Thanks for reporting this, it is a known issue that we are working on fixing ASAP.
I will update this issue once it's fully fixed.

**Comment by osortega** [comment]
@tszkanlo We had an outage under your plan's region.
It should be mitigated by now.

Sorry about the inconvenience!
