### ISSUE TITLE
doc bug report: "runArgs" in devcontainer.json

### ISSUE THREAD

**Issue by smallhaes** [MicrosoftDocs/vsonline#652]
I'd like to access Docker within a custom container. However, the doc is wrong. It should be "-v" rather than "--v"
![](https://note.youdao.com/yws/public/resource/d68209b5672655918654069ad86b7ac0/xmlnote/9B288A76A59F45AAA46A267EA1AA046A/74441)

**Comment by gregvanl** [comment]
Thanks for pointing this out!
