### ISSUE TITLE
Default dotnet sdk set to LTS which breaks ASP.NET Core 3.0 apps

### ISSUE THREAD

**Issue by pheuter** [MicrosoftDocs/vsonline#67]
Looks like the default VS Online dotnet sdk is set to LTS [1] which breaks my ASP.NET Core 3.0 project in an interesting way. The initial startup Oryx build succeeds [2] but the Omnisharp dotnet restore command fails [3]. When I try to manually set `/opt/dotnet/sdks/3.0` in **.bashrc** it still inserts the LTS version first in PATH.

[1] In default **~/.bashrc**: `PATH=$PATH:/opt/oryx:/opt/nodejs/lts/bin:/opt/dotnet/sdks/lts`

[2]
```
Source directory : /home/vsonline/workspace

Using .NET Core SDK Version: 3.0.100

Restoring packages...

Welcome to .NET Core 3.0!
```

[3]
```
/opt/dotnet/sdks/2.1.802/sdk/2.1.802/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0. Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0
```

**Comment by lostintangent** [comment]
@pheuter Thanks for reporting this! We'll take a look at this, and see if we can smooth over this seam.

**Comment by JeffSinclair** [comment]
Also having this issue. Can't get my .Net Core 3.0 to work.

Executing task: dotnet build /home/vsonline/workspace/User Interface Core/SCS.WebClient.Core.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/opt/dotnet/sdks/2.1.802/sdk/2.1.802/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/home/vsonline/workspace/Constant/SCS.Constant.core.csproj]

**Comment by rajkumar42** [comment]
New environments created now will have 1.1, 2.1, 2.2, 3.0 sdks installed.

see #127

**Comment by pheuter** [comment]
@rajkumar42 Nice. [.NET Core 3.1](https://dotnet.microsoft.com/download/dotnet-core/3.1) was released the other day as the new LTS, any chance of getting that supported as well?

**Comment by tclzcja** [comment]
Yeah ditto above, how about .Net Core 3.1?
