### ISSUE TITLE
Support setting up self-hosted environments from the command line

### ISSUE THREAD

**Issue by Chuxel** [MicrosoftDocs/vsonline#69]
Currently self-hosting can only be setup using VS Code. While this is convenient, there are scenarios like Linux servers without X installed or where you only have SSH access where this will not work. This issue is to track supporting a command line install and setup mechanism.

**Comment by taiyosogawa** [comment]
Seeing a lot of interest for this [over here](https://github.com/MicrosoftDocs/vsonline/issues/41), too. Adding a link to this issue for tracking.

**Comment by erinxocon** [comment]
Love this!  I would love to be able to self host on a central digital ocean droplet my coworkers and I all have access to!

**Comment by BirkhoffLee** [comment]
This is definitely a must!

**Comment by jgbradley1** [comment]
Just reviewing a few ways other "cloud IDEs" out there provide this capability

[Jupyter](https://jupyter.org) - [releases binaries](https://jupyter.org/install) as pip/conda packages
[Coder.com](https://coder.com/) - [releases linux binaries](https://github.com/cdr/code-server/releases) that are installable by standard package managers
[Eclipse Theia](https://theia-ide.org) - released as a npm package but also distributed as [rpm](https://github.com/theia-ide/theia-apps/tree/master/theia-rpm-build-docker)/[deb](https://github.com/theia-ide/theia-apps/tree/master/theia-deb-build-docker) packages that are installable by standard linux package managers

**Comment by gh67uyyghj** [comment]
Yes please support some containerized or packaged solution that can be installed with only CLI commands. I really believe that VSCode online is going to be a real game changer in the history of IDEs but the ability of having easy self-hosted solution is a must. Please make it happen

**Comment by smikitky** [comment]
With [AWS Cloud9 SSH Environments](https://docs.aws.amazon.com/cloud9/latest/user-guide/create-environment-ssh.html), you only have to add a public RSA key to `authorized_keys` in a self-hosted machine to get started. After clicking "Open IDE" for the first time, all dependencies (~100MiB) will be installed under `~/.c9` via plain old SSH.

Almost the same workflow is already possible with VSCode's "Remote - SSH" today, so TBH I was disappointed to find VSO doesn't work this way. Is this type of workflow already on the VSO's roadmap?

(The downside of this approach is that you have to publicly open an SSH port, but it also means there will no longer be problems like #5...)

**Comment by kitaev-chen** [comment]
It looks like this thread is the right place :)

Let me provide a detailed scenario.

-----------------------

Strongly agree with this!!!

there are lots of problems when registering the local environment (self-hosted), especially the local environment is a remote server (I believe the reason that lots of people seek to use vsonline is that they usually have to work on the remote (GPU) server).

When registering the remote server we have to find a way to launch a VNC or X11 server (typically users have no permission to do this), then ssh forward to the local laptop, then launch a vscode, then register the remote server inside vscode. The vscode will request to sign in Azure through a web browser several times and invoke vscode through a link such as "vscode:// xxx" (fail to invoke usually). The whole procedure has many steps that are extremely easy to fail and heavily rely on GUI.

The best way for this scenario is to provide a pure command-line and GUI free solution. Hope it will come soon.

**Comment by lostintangent** [comment]
@kitaev-chen Out of curiosity, would #192 be of interest to you? I just ask since you mentioned needing a GPU server, and we're keen to get more feedback on that item as well (e.g. use cases, etc.)

**Comment by kitaev-chen** [comment]
> @kitaev-chen Out of curiosity, would #192 be of interest to you? I just ask since you mentioned needing a GPU server, and we're keen to get more feedback on that item as well (e.g. use cases, etc.)

It's definitely interesting! I will follow that.

**Comment by MichalCz** [comment]
Ok, so my findings:

```
ssh user@server
snap install --classic code
code --install-extension ms-vsonline.vsonline
```

The next steps are somewhat more complex - I did get x11 forwarded code to register to azure, but it required catching the vscode:// url in network tab in chromium and entering it with `> Developer: open url`.

Still I'm stuck on #96

**Comment by offbeatful** [comment]
Found this thread by looking into creating my own self-hosted development environment... So adding my use cases:

1. As remote development started spinning around, i've created a simple dockerfile with the tools I want, configuration I like that runs on linux I love. Now, what I want - add a capability to run this container anywhere (on my local desktop, on my mac/linux server in the garage or in the cloud if I need more power). When it runs - it should register itself allowing me to connect from browser or VsCode and start working with my private repos anywhere.

2. I like the way how I can specify docker image in `devcontainer.json` (but it seems I can only checkout public github repositories). So let's say I have a private repo with `devcontainer.sjon` that uses my devbox image. Then I want to be able to pass it to coworker, so he/she can checkout the code and run that container anywhere (locally, remotely or in the cloud so she can continue working from other place).

**Comment by alessionossa** [comment]
Is there any update?

**Comment by nikmd23** [comment]
Not yet, but keep your eyes peeled, as well have announcements in the space soon! 👀 

cc @taiyosogawa

**Comment by contention** [comment]
Hey! Any news on when we can at least expect an announcement against this ticket? :o)

**Comment by jkeech** [comment]
@contention later this week 😃

**Comment by contention** [comment]
@jkeech That could be the best news I’ve heard so far in 2020 (admittedly the bar is set low). 😃

**Comment by lucaslie** [comment]
haven't tried it yet but looks great :D 

https://docs.microsoft.com/en-us/visualstudio/online/how-to/self-hosting-cli#sign-up

**Comment by jkeech** [comment]
This just launched today 🚀 https://devblogs.microsoft.com/visualstudio/bring-your-own-machine-to-visual-studio-online/

Please give it a shot and let us know what you think! I'm going to go ahead and close this issue. Please file new issues if you encounter any problems. Thanks!

**Comment by davide-rota** [comment]
@jkeech Hi John, tried to login via `vso start` but it seems that that only supports work accounts and not MSA accounts (@live.com, @hotmail.com etc..) Since the rest of VS Online supports MSA accounts this seems a problem. Any idea? Thanks!

![image](https://user-images.githubusercontent.com/11763/78989145-0a9f9300-7b33-11ea-8410-f7c01dc5d913.png)

**Comment by definitelycarter** [comment]
@jkeech It looks like this issue is being tracked under https://github.com/MicrosoftDocs/vsonline/issues/394.
