### ISSUE TITLE
Environments seeded with pull request urls are not cloning the proper branch

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vsonline#7]
It appears that when an environment is created based on a PR URL (e.g. `https://github.com/nikmd23/node/pull/1`), the master branch is the one checked out, instead of the branch the PR is based on.

**Comment by bjbennet** [comment]
@nikmd23 - I was able to clone a PR branch into a newly created environment. I used the git repo `https://github.com/vsls-contrib/guestbook/pull/11`. Once the environment started up I used `git status` to determine I was on branch `pr-11`.

Can you try the scenario again and use `git status` to show what branch you are on?

**Comment by nikmd23** [comment]
It is not. 

Here's a scenario to illustrate the behavior I'm expecting. Feel free to push back if you feel like this is wrong:

- I have two branches, `master` and `new-feature`. I have a PR where I want to merge X commits into `master` from `new-feature`.
- If I create an environment from the PR URL, I am expecting the environment to be in a state where `new-feature` is the checked out branch, and it's current. 
- Further, I expect that if I commit a change and simply call `git push` that the upstream will be correctly configured and those changes will be pushed to my remote. 

Today, I do get the commits that are in the PR, but on a newly created branch (not `new-feature`) and the new branch doesn't have an upstream configured. 

Let me know if you have questions.

**Comment by jkeech** [comment]
We also need to consider forks. In general, I think the behavior should be that if you create an environment from a PR, then the source branch for the PR is the one that is checked out, so that you can push changes to the branch and update the PR. If the source of the PR is a fork, we should likewise clone and checkout the correct branch from that fork.

**Comment by jkeech** [comment]
This behavior is fixed now. We clone the source of the PR, not the target.
