### ISSUE TITLE
Allow logging out from the management portal

### ISSUE THREAD

**Issue by gjsjohnmurray** [MicrosoftDocs/vsonline#70]
Using my Chrome browser I logged in at https://online.visualstudio.com/ using the credentials of one of my Microsoft accounts.

I now want to log out and instead use a different Microsoft account. But the circular avatar in the top right of the https://online.visualstudio.com/environments page doesn't offer a logout. Closing and relaunching my browser doesn't help.

I tried https://online.visualstudio.com/logout but that only gave a blank page, and next time I went to https://online.visualstudio.com/ it still saw me as logged in.

I'd probably have to clear cookies to get back to the login dialog for https://online.visualstudio.com/

Certainly if I launch a new incognito window in Chrome I can use this to authenticate using a different account.

Am I overlooking the logout mechanism? Or is it missing?

**Comment by lostintangent** [comment]
@gjsjohnmurray We don't currently have a log out gesture, but we'll be adding this very soon!

**Comment by jkeech** [comment]
We've added a "Sign out" command on the profile in the top right corner. If you click on the profile icon, and then click "Sign out", you will be signed out and eventually taken back to the login page (after signing out in AAD as well).

![image](https://user-images.githubusercontent.com/746020/68520008-7a8ab400-0249-11ea-9442-2dccad6f4714.png)
