### ISSUE TITLE
Provide a way to opt-in to the "insiders" feature channel

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/vsonline#73]
Currently, to enable using a Docker image you need to turn on experimental features via `.cloudenv-settings.json` in a weird directory. These experimental features currently control what you can and can't do in `devcontainer.json`.

It would be ideal to centralize on one JSON file rather than two. I personally found the configuration confusing, and would love to be able to control what is and isn't enabled in `devcontainer.json` directly from `devcontainer.json` itself.

**Comment by lostintangent** [comment]
@bnb This isn't really a file that's meant to be used TBH, so it shouldn't have actually been documented. I'm going to remove this right now :)

That said, the plan is to introduce a new VS Code setting called `vsonline.features`, that by default is `stable`, but you could set it to `insiders` and enable all of the experimental features. This is exactly how Live Share behaves, and so we want to be consistent with VS Online.

**Comment by JamesGreenaway** [comment]
In the meantime, what is the best way to enable experimental features?

**Comment by bnb** [comment]
Absolutely love that approach @lostintangent, especially if y'all end up doing blog posts or something along those lines to assert to the community when new features are added :)

**Comment by jkeech** [comment]
In the VS Code extension, we now have the `vsonline.featureSet` setting which can be set to `insiders`. The web portal also has a settings page with an insiders toggle. Both of these can be used to opt-in to insiders/preview features before they are on-by-default in the stable feature set.
