### ISSUE TITLE
dockerFile / customContainers "can only be used from within the Visual Studio Code based experience"

### ISSUE THREAD

**Issue by asw101** [MicrosoftDocs/vsonline#74]
It is not sufficiently clear in the [Configuring environments](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring) docs that dockerfile / customContainers "can only be used from within the Visual Studio Code based experience"

The default [Visual Studio Online configuration sample](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring#visual-studio-online-configuration-sample) specifies the `dockerfile` property (which linting complains should be `dockerFile`):

```jsonc
  // Use the dockerfile in .devcontainer directory
  "dockerfile": "Dockerfile"
```

We then scroll down to [Exprimental features](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring#experimental-features) and see we need to enable those, via a `.cloudenv-settings.json` (which I too expected might have been something in `.devcontainer/devcontainer.json`, per https://github.com/MicrosoftDocs/vsonline/issues/73) and that "These features can only be used from within the Visual Studio Code based experience".

This means if I am using Visual Studio Online in my browser I might try to configure it more declaratively  using `dockerFile` or `image` in the `.devcontainer/devcontainer.json`, rather than `postCreateCommand` bash script, and be wondering why this doesn't appear in the integrated terminal, etc. This would be one of my favorite parts of Visual Studio Online once available in the browser.

**Comment by jkeech** [comment]
The goal is to enable this by default in both VS Code and VSO. We are fine-tuning the custom Dockerfile experience and will be enabling it soon once it's stable. Thanks!

The experimental features section you referenced in the docs is a file meant for internal use within the team and should have never been documented. See #73 for more details.

**Comment by lostintangent** [comment]
I'm going to close this issue, since as @jkeech mentioned, the "experimental features" weren't meant to be documented. We've since removed these docs, and we'll be addressing #73, which will provide a more accessible way of opting into our "insiders" channel. Apologies for the confusion!

**Comment by asw101** [comment]
@jkeech that's excellent news regarding the custom Dockerfile experience, thank you for the clarification!

@lostintangent no worries, thank for the confirmation and I look forward to opting into the "insiders" channel (which I run full-time for VS Code itself) when available.
