### ISSUE TITLE
Revoking GitHub OAuth token does not allow for re-authorization

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/vsonline#79]
I recently encountered an issue with my GitHub authorization for VS Online, and in an attempt to diagnose, revoked the VS Online OAuth token with the intent of reauthorizing VS Online to use my GitHub account. On attempting to create a new environment from the web portal, however, the Create button stays disabled and the browser developer console presents a long string of 401 errors (e.g.: screenshot below):

![image](https://user-images.githubusercontent.com/31516/68245115-51b5b500-ffe4-11e9-8d72-c02c556ddaa9.png)

**Comment by jkeech** [comment]
We've added a sign out command on the top-right corner profile. If you click on the profile, then click "Sign out", it will sign out and clear all stored browser state, including any cached GitHub tokens.

![image](https://user-images.githubusercontent.com/746020/68520040-b45bba80-0249-11ea-9598-c392af510dec.png)

**Comment by cgranade** [comment]
That did it, thanks for all the help, @jkeech!
