### ISSUE TITLE
Xaml design tools, too?

### ISSUE THREAD

**Issue by PascalS86** [MicrosoftDocs/vsonline#80]
Hey fellows,

I wanted to know, if the design tools for xaml will be available in vs online, too?
Or what your ideas are for UI design/development?

**Comment by jkeech** [comment]
VS Online currently supports pretty much everything that VS Code can do on the desktop. Are you referring to the XAML design tools in Visual Studio? If so, those won't be immediately available in the browser unless there is an equivalent VS Code extension.

The Visual Studio support for VS Online environments will be starting a private preview soon ([sign up here](https://aka.ms/vsfutures-signup)). Initially in Visual Studio, you will be able to connect a local install of Visual Studio to a cloud-hosted Windows environment, and many of the features of Visual Studio will work against the remote environment. You will also be able to connect to the same Windows environment from the browser in online.visualstudio.com, but the editor will be powered by VS Code in that case. Hope that helps!

**Comment by PascalS86** [comment]
ok, cool. good to know. thanks you 😊 

so, can I say it's more like a vscode experience? with more build, debug and analyzing?

**Comment by jkeech** [comment]
There will be three different clients you can use to access VS Online Environments.

1) VS Code desktop client
2) VS desktop client (currently in private preview)
3) VSO browser client

The VSO browser client is based on VS code, so the editor itself will have the functionality of VS Code. For VS client-specific functionality, at least in the near term, the VS desktop client would need to be used.

**Comment by PascalS86** [comment]
Thank you very much for answering my questions. appreciate it.
