### ISSUE TITLE
Create environment on specific branch / commit

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#81]
**Feature Request**
Using the `create environment` UI, allow specifying a specific branch (and commit) to use for seeding the environment

Github supports the following for referencing a commit:

```
microsoft/vscode@SHA
```

Github does not supporrt branch references AFAIK. One idea would be to use full path like so:

```
microsoft/vscode/tree/release/1.40
```

**Comment by cmbrose** [comment]
Adding the discussion tag as there are a few ways to handle specifying the branch/commit/PR to clone from:

- Make it an explicit setting in environment creation in addition to the repo url
   - Pro: very obvious, agnostic of the url form the repo uses
   - Con: an extra step to setting up the environment

- Parse it from the url (both short and long form)
   - Example: `my/repo@123456`, `https://github.com/my/repo/tree/MyBranch`
   - Pro: probably this is what most users would naturally try to do
   - Con: it may need special handling for the standards of each repo's url structure

@nikmd23, @lostintangent - your thoughts here are appreciated

**Comment by lostintangent** [comment]
I’d love to parse this from the URL, since that would not only prevent us from having to add extra config, but it would make it easy for someone to copy/paste a URL from GitHub, and spin up an environment for it.

**Comment by cmbrose** [comment]
Agree - so here are the cases that I know of to support:

- `<repo>/pull/<id>` => PR #\<id\>
- `<repo>/commit/<id>` => Commit with SHA \<id\>
- `<repo>@<id>` => Commit with SHA \<id\>
- `<repo>/tree/<branch>` => Branch \<branch\>

**Comment by jkeech** [comment]
@lostintangent, @cmbrose, in the SHA case, are you expecting just to land in a detached HEAD state? It would be up to the user to pick a branch afterwards if they wanted to make any changes and commit?

In the PR case, we are already tracking that with #7. I think that case should support checking out the _source_ branch of the PR rather than the _target_. The source could be from a fork as well, so that's something to consider.

**Comment by lostintangent** [comment]
@jkeech Yep, that’s my expectation. And I agree with you regarding the PR workflow as well.

**Comment by jkeech** [comment]
This is supported for GitHub repos now. If you create the environment from a full GitHub url with `tree` or `commit`, then it will check out that ref or commit. The easiest way is to navigate to the branch or commit you want to start the environment from, copy the url, and create the environment from using that url.

### Examples
* `https://github.com/microsoft/vscode/tree/release/1.43`

![image](https://user-images.githubusercontent.com/746020/75578735-3bab8480-5a19-11ea-8d53-1b0c7cc38b96.png)
* `https://github.com/microsoft/vscode/commit/40cd953770733307e17b946e47ab9904ba487993`

![image](https://user-images.githubusercontent.com/746020/75578910-9cd35800-5a19-11ea-80c7-0c4b5cd702f7.png)

**Comment by nikmd23** [comment]
@ziahamza - I wanted to make sure you saw that we supported this now. 😊
