### ISSUE TITLE
Escape key should always dismiss `Create Environment`

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#82]
**Repo**
1. Create a new environment using UI
1. With the panel focused but without any text boxes focused, press esc

**Expected**
This closes the create environment UI

**Actual**
Nothing happens

Escape works if you have a text box focused

**Comment by mjbvz** [comment]
@smvanderweide Was this fixed?

**Comment by srivatsn** [comment]
A fix was checked in but hasn't been deployed yet. Keeping the issue open until the fix is deployed to production.

**Comment by smvanderweide** [comment]
The fix has been deployed.
