### ISSUE TITLE
More clear visual indication of focus in `Create Environment` UI

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#83]
**Repo**
1. Open create environment UI
1. Try tabbing trough the input boxes

**Bug**
Focus is indicated by turning the box's 1px border blue

![Screen Shot 2019-11-05 at 3 39 54 PM](https://user-images.githubusercontent.com/12821956/68255660-b1ab5c00-ffe2-11e9-8e92-53fd961083f5.png)

This looks very similar to the default black color on certain screens, making visually tracking what is focused difficult

**Comment by smvanderweide** [comment]
The form inputs are Office UI Fabric React elements, and their styling is defined within the UI Fabric library. The UI Fabric team would need to be the ones to address your issue. If you would like to file an issue with them, please do so on their [GitHub](https://github.com/OfficeDev/office-ui-fabric-react/issues).
