### ISSUE TITLE
Error: Could not detect the language from repo.

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#85]
## Repo
1. Create new environment without a repo
1. Connect on VSO

## Bug
On connect, a terminal pops up with the contents:

```
vsonline:~$ OPERATION_ID=ec178eee-94ca-4f25-adfc-aa99f9a8e1d3 /.vsonline/bin/vso exec oryx build --manifest-dir /home/vsonline/.oryx --log-file /home/vsonline/.oryx/build.log /home/vsonline/workspace
[2019-11-05 23:37:12.500 CLI I] vso v1.0.1200.7639 (pid: 102)
Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20191028.3, Commit: 9474e19db8cd77821d2d17444e26d1a4fdc2a006, ReleaseTagName: 20191028.3
Build Operation ID: |ZJ91Buseqsk=.b3e8bff0_

Enumerating repo to find any files with extension 'csproj'...
Error: Could not detect the language from repo.
[VS Online][ec178eee-94ca-4f25-adfc-aa99f9a8e1d3] Process exited with non - zero result (1).
vsonline:~$ 
```

Not sure if the error is causing the terminal to pop up but as far as I can tell this error doesn't actually matter and there is no action that the user should be taking from it

**Comment by edgonmsft** [comment]
Hi Matt!

Like you mention its not really a critical error.

We run oryx build command on a new environment if your repository doesn't include a devcontainer.json file.

The intent is to see if we can get ahead doing things like npm install to get you started faster. If the logic can't decide what to do it gives out that message.

Thanks!

**Comment by mjbvz** [comment]
The main issue is that automatically pops up a non-interactive terminal this error. This terminal is super annoying as I always mistakenly try typing in it and then wonder for a second or two why nothing is being entered. If this info were dumped to a output channel instead, it'd be much better

(PS: I already reported that I do not think VSO should automatically run npm install/build in #25. )

**Comment by edgonmsft** [comment]
Hi Matt, thanks for the feedback!

I'll be working on making this terminal less intrusive.

**Comment by jkeech** [comment]
This specific issue has been fixed. We no longer run Oryx build on empty environments.

There's a separate discussion happening about whether we should show the read-only terminal when we do run Oryx build, or whether it should just happen in the background. And then #25 is discussing when and if we should run Oryx build at all. But for now, we will at least not show this terminal with an error message if you create an empty environment.
