### ISSUE TITLE
Cannot log in to VSO because OAuth Flow Issue

### ISSUE THREAD

**Issue by bglick** [MicrosoftDocs/vsonline#86]
I cannot log into VS Online via the extension because my browser does not redirect the last step of the OAuth flow back to VS Code.  I run VS Code in a linux container so my desktop browser does not have access to send the flow back.  I believe the extension needs the token based login that is used by the Azure auth capabilities:

OS: ChromeOS 77
VS Code Version: 1.39.2

**Comment by doggy8088** [comment]
I have the same issue, but happen in the browser login process. I recorded a short clip to demonstrate it. 

https://youtu.be/QocgFMM6R8w

**Comment by srivatsn** [comment]
@doggy8088 looks like Chrome's popup blocker blocked a popup. Could you try by allowing popup?

**Comment by doggy8088** [comment]
@srivatsn No, I don't think any of the window been blocked popup.

**Comment by legomushroom** [comment]
Hi @bglick @doggy8088 , thanks for filing the issue! From the youtube clip, I see that the auth flow completes in the popup and something going wrong afterward. Do you see any errors in the dev tools console?

**Comment by doggy8088** [comment]
@legomushroom 
![image](https://user-images.githubusercontent.com/88981/68322925-4e631c00-00ff-11ea-8e7a-f3840316d401.png)

**Comment by ku-suke** [comment]
I have same issue on LXDE environment. Chrome shows a popup with `Open xdg-open?` but vscode does not respond.

![noVNC - SUBID 31051866 - Google Chrome 2019-11-09 01 26 04](https://user-images.githubusercontent.com/232455/68493534-fc053500-028f-11ea-8502-ab423fffd7ff.png)

I installed vscode with snap command. The .desktop file seems correctly described x-scheme-handler.
```bash /var/lib/snapd/desktop/applications/code_code-url-handler.desktop 
[Desktop Entry]
X-SnapInstanceName=code
Name=Visual Studio Code - URL Handler
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/code_code-url-handler.desktop /snap/bin/code --force-user-env --no-sandbox --open-url %U
Icon=/snap/code/19/meta/gui/com.visualstudio.code.png
Type=Application
NoDisplay=true
StartupNotify=true
Categories=Utility;TextEditor;Development;IDE;
MimeType=x-scheme-handler/vscode;
Keywords=vscode;
```

**Comment by bglick** [comment]
For completeness, here's the screenshot of the same behavior on a Chromebook.  Installed VS Code from the .deb.

![image](https://user-images.githubusercontent.com/535182/68510043-7ad28180-0240-11ea-9b70-ecd621b1e965.png)

**Comment by legomushroom** [comment]
There are 2 separate issues mixed in this thread:

1. VSO Web client info parsing from base64 string.
2. VSCode protocol handler registration on the Debian distro and Chromium notebook.

The `2.` seems to be a VSCode issue. // cc @bpasero @jrieken

**Comment by ku-suke** [comment]
I found workaround for `2.` 

- Press `F12` to open Chromium DevTools on final step.
- Switch `Network` tab.
- Click `Continue` button on web page, an error request will shown.
- Copy url and open terminal. Then, paste as a argument for `xdg-open`.

```
$ xdg-open 'vscode://ms-vsonline.vsonline/signin?code=<VAL1>&state=<VAL2>'
```
( Make sure quote your link. )

It worked for me.

![noVNC - SUBID 31068725 - Google Chrome 2019-11-09 21 49 15](https://user-images.githubusercontent.com/232455/68528945-6a073600-033c-11ea-8072-ba5c6be39c54.png)

**Comment by legomushroom** [comment]
@ku-suke interesting.. So chrome fails to find the protocol handler but you are able to invoke it directly. That might mean the Chrome protocol handler flow. We need to implement a nice fallback experience to automate the steps you'we done above. Such experience will mean we provide you with a code you can copy and paste it into the vscode instance.

**Comment by smikitky** [comment]
I have the same issue with Chrome (ku-suke's workaround worked for me too), but **also with Firefox**. After clicking "Open link" at the point of the following screenshot, VSCode does not respond (it does not even show the "Allow an extension to open this URI?" dialog).

![image](https://user-images.githubusercontent.com/7779406/70185936-21218200-172e-11ea-9fd0-8f23959343a4.png)

As you can see, Firefox recognizes the `vscode://` protocol handler itself, which is defined in `/var/lib/snapd/desktop/applications/code_code-url-handler.desktop`.

- Ubuntu 18.04 LTS
- Xfce 4 + xrdp
- VSCode installed via Snap
- Firefox installed via Snap

Here's all I did for a newly-installed Ubuntu 18.04 LTS:

```bash
sudo apt-get update
sudo apt-get -y install xfce4

sudo apt-get -y install xrdp
sudo systemctl enable xrdp
echo xfce4-session >~/.xsession
sudo service xrdp restart

sudo apt-get -y install xdg-utils
sudo snap install code --classic
sudo snap install firefox
```

**Comment by legomushroom** [comment]
@smikitky 

> VSCode does not respond

Does VSCode app gets focused or after invoking the protocol handler nothing happens at all?

**Comment by smikitky** [comment]
@legomushroom No, it didn't get focused. And for some reason, the "Launch Application" dialog did not close after clicking "Open link", either.

**Comment by legomushroom** [comment]
@smikitky thanks for confirming, looks like VSCode protocol handler on Linux to me. Could you specify your distro and how did you install the VSCode on your machine? Thanks!

**Comment by smikitky** [comment]
@legomushroom The distro and the installation steps are listed in my previous comment. It was on MS Azure's VM (I already deleted it, but Standard D2s v3 if I remember correctly).

**Comment by legomushroom** [comment]
@smikitky my bad, see it now, thanks!

**Comment by legomushroom** [comment]
closing as dup of https://github.com/MicrosoftDocs/vsonline/issues/136
