### ISSUE TITLE
Can not connect to self-hosted environment for .Net Core/.Net framework WPF

### ISSUE THREAD

**Issue by TrentXu** [MicrosoftDocs/vsonline#89]
After I registered a self-hosted environment for .Net Core/.Net framework WPF, then it can not connect to the self-hosted environment using VS Code or web-browser.
```
Failed to connect to the remote extension host server (Error: The environment is currently offline.)
```

I tried to restore the local environment in the VS Code, it displays error messages:
```
Unabled to restore local environment: read ECONNRESET
Source: Visual Studio Online (Extension)

Unabled to restore local environment: Sharing environment failed.
```

Besides, I tried to register a self-hosted environment for .Net Core Console, which can work normally.

Does it not support .Net Core WPF, Winform or .Net framework in the self-hosted environment right now?

**Comment by taiyosogawa** [comment]
@TrentXu, apologies for the tremendously late response.

Could you let me know if you are still experiencing this issue? If so, there are some things you could do to help us understand the problem:

When you register your environment, could you check to see if the process `vsls-agent` is running? The "environment is currently offline" message makes me think that the process is not running when you connect, but I am wondering if it dies or just never starts.

**Comment by taiyosogawa** [comment]
I'm afraid we are unable to address this issue without more information. I'm closing it out, but if you continue to see it, please don't hesitate to re-open or file a new issue.
