### ISSUE TITLE
Self-Hosted Environments using AKS

### ISSUE THREAD

**Issue by ThorstenHans** [MicrosoftDocs/vsonline#93]
I really enjoyed using VSO so far. However, I think it is mission-critical that I can spin up environments in my existing AKS cluster. 

From my point of view, a sidecar container that runs the VSO extension in a headless mode would be awesome. Developers can spin up development environments on AKS in seconds and the small sidecar container  does whatever it needs to do to wire up with VSO service and populates a new environment on the fly ❤️

**Comment by taiyosogawa** [comment]
@ThorstenHans, thanks so much for the interest and feedback! A headless mode for self-hosted environments is on our roadmap, and we are tracking in issue #69. If there's something specific you'd like to see for your use case, (ex: is it important for you that it run in a separate container?) we'd love to hear it in that conversation 😄
