### ISSUE TITLE
.devcontainer.json (in repo root) ignored 

### ISSUE THREAD

**Issue by ThorstenHans** [MicrosoftDocs/vsonline#94]
Hey,

I added a `.devcontainer.json` file to the root of a repository to install some extensions, configure settings and execute a shell script during provisioning. 

When I create a new environment based on this repository, `.devcontainer.json` is ignored. 

Using the alternative approach (`{repository-root}/.devcontainer/devcontainer.json`), everything works as expected.

### Steps to reproduce

- Create a new repository
- add a valid `.devcontainer.json` to the root of the repository
- spin up a new environment in VSO pointing to the previously created repo

**Comment by edgonmsft** [comment]
Thanks for the report Thorsten! 

This is a bug that we are working on currently.

**Comment by cmbrose** [comment]
The fix for this has rolled out today - we should now check for `.devcontainer.json` and `.devcontainer/devcontainer.json` for the config.  Let me know if you don't see this behavior working!

**Comment by ThorstenHans** [comment]
still broken if you specify a postCreateCommand... 

settings are applied and extensions are installed

However, postCreateCommand isn't invoked
