### ISSUE TITLE
FailedToRegisterResourceProvider when logging in

### ISSUE THREAD

**Issue by nickmccurdy** [MicrosoftDocs/vsonline#98]
I'm a developer using a personal Microsoft account, and I'd like to try out Visual Studio Online. I'm able to log in at https://online.visualstudio.com/environments, but when I try to create an environment's billing plan, my only subscription option is "DreamSpark" and creating the plan errors with "FailedToRegisterResourceProvider". I'm no longer studying but my Microsoft account may have previously been linked to my university's Dreamspark account, so I wonder if this is causing issues. I don't use Dreamspark any more so I'd be fine with using whatever developer preview is publicly available.

**Comment by bjbennet** [comment]
It is possible that your user under the DreamSpark subscription does not have the access permissions to register a Resource Provider. Registering for the resource provider is required and happens automatically when you create your first Plan. Access to a valid Azure subscription in which you can register resource providers is also required. If you are unsure if your user has sufficient permissions, you can create a free Azure subscription to use here: https://azure.microsoft.com/en-us/free/

**Comment by nickmccurdy** [comment]
I created a free Azure subscription successfully and I’m having the same issue. I don’t  know what a resource provider is. I’d like to disable Dreamspark and use the normal version of Azure and VSO.

**Comment by bjbennet** [comment]
Is your newly created subscription available in the drop down? You should select that one when creating Plans. If that subscription is not availbe then your Microsoft account is not connected to that subscription. There is nothing you need to do for the resource provider it is enabled for you when using VSO. We will create your Plan resource for you in your azure subscription for billing.

**Comment by jkeech** [comment]
This might be related to #39 if your account is registered in multiple AAD tenants. Currently we always pick the first one. The other issue is tracking a fix to allow you to pick the directory to use when you sign in.

**Comment by nickmccurdy** [comment]
This seems to be working now, I just had to change my plan to `Free Trial` after the above steps, thanks.
