### ISSUE TITLE
VS Online Extension Sign In does not open the browser (Connected to WSL)

### ISSUE THREAD

**Issue by mdekoster** [MicrosoftDocs/vsonline#99]
Pressing F1 in VS Code, selecting VS OnlIne: Sign In does open the default browser (being Edge on my machine)

**Comment by mdekoster** [comment]
This happens if code has remote connected to WSL

**Comment by legomushroom** [comment]
Hi @mdekoster, thanks for the feedback! Sorry for the long reply. Are you still experiencing the issue? Just to clarify - the browser `does not open` (you seem to have a typo in the first comment).

**Comment by mdekoster** [comment]
Hi @legomushroom. The problem is solved after some updates of Visual Code and the VS Online extensions.
